// REPOSITORY SOURCE: diplomat-bit/Fuckyou | PATH: diplomat-bit-Fuckyou-70f83c5/components/GasPriceCorrelation.tsx
================================================================================

import React, { useMemo } from 'react';
import { 
  LineChart, 
  Line, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  Legend, 
  ResponsiveContainer, 
  ReferenceArea,
  AreaChart,
  Area
} from 'recharts';
import { TrendingUp, Activity, Flame, Coins } from 'lucide-react';
import { motion } from 'motion/react';

interface DataPoint {
  date: string;
  gasPrice: number;
  defenseStockIndex: number;
  conflictEvent: string | null;
}

const mockData: DataPoint[] = [
  { date: '2023-01', gasPrice: 3.20, defenseStockIndex: 100, conflictEvent: null },
  { date: '2023-04', gasPrice: 3.50, defenseStockIndex: 105, conflictEvent: 'Appropriation 1' },
  { date: '2023-07', gasPrice: 3.80, defenseStockIndex: 115, conflictEvent: 'Iran Escalation' },
  { date: '2023-10', gasPrice: 3.60, defenseStockIndex: 125, conflictEvent: 'Appropriation 2' },
  { date: '2024-01', gasPrice: 4.10, defenseStockIndex: 135, conflictEvent: 'Conflict Termination' },
  { date: '2024-04', gasPrice: 4.25, defenseStockIndex: 142, conflictEvent: null },
];

export default function GasPriceCorrelation() {
  const chartData = useMemo(() => mockData, []);

  return (
    <div className="w-full max-w-5xl mx-auto p-10 bg-slate-950 rounded-[3rem] border border-white/5 shadow-2xl overflow-hidden font-sans">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-12 border-b border-white/5 pb-10">
        <div>
          <div className="flex items-center gap-4 mb-4">
            <div className="p-3 bg-red-600/10 text-red-500 rounded-2xl border border-red-500/20">
              <TrendingUp className="w-6 h-6" />
            </div>
            <h2 className="text-2xl font-black text-white uppercase tracking-tight">Economic Correlation Matrix</h2>
          </div>
          <p className="text-[10px] text-slate-500 font-black uppercase tracking-[0.3em] leading-relaxed max-w-xl">
            Real-time synchronization between retail energy costs and defense contractor equity indices. 
            Tracing the financial friction generated by artificial conflict events.
          </p>
        </div>
        
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-black/50 p-4 rounded-2xl border border-white/5">
            <div className="flex items-center gap-2 mb-1">
              <Flame className="w-4 h-4 text-red-500" />
              <span className="text-[8px] font-black text-slate-500 uppercase tracking-widest">Energy Friction</span>
            </div>
            <p className="text-lg font-black text-white font-mono">+32.8%</p>
          </div>
          <div className="bg-black/50 p-4 rounded-2xl border border-white/5">
            <div className="flex items-center gap-2 mb-1">
              <Coins className="w-4 h-4 text-emerald-500" />
              <span className="text-[8px] font-black text-slate-500 uppercase tracking-widest">Contractor Yield</span>
            </div>
            <p className="text-lg font-black text-white font-mono">+42.0%</p>
          </div>
        </div>
      </div>

      <div className="h-[450px] w-full bg-black/30 rounded-[2rem] p-6 border border-white/5 shadow-inner">
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={chartData} margin={{ top: 20, right: 30, left: 20, bottom: 20 }}>
            <defs>
              <filter id="shadow" height="200%">
                <feGaussianBlur in="SourceAlpha" stdDeviation="3" result="blur" />
                <feOffset in="blur" dx="0" dy="4" result="offsetBlur" />
                <feMerge>
                  <feMergeNode in="offsetBlur" />
                  <feMergeNode in="SourceGraphic" />
                </feMerge>
              </filter>
            </defs>
            <CartesianGrid strokeDasharray="3 3" stroke="#ffffff10" vertical={false} />
            <XAxis 
              dataKey="date" 
              stroke="#ffffff30" 
              fontSize={10} 
              fontWeight="black" 
              tick={{ fill: '#64748b' }}
              axisLine={{ stroke: '#ffffff10' }}
            />
            <YAxis 
              yAxisId="left" 
              stroke="#ffffff30" 
              fontSize={10} 
              fontWeight="black" 
              tick={{ fill: '#64748b' }}
              axisLine={{ stroke: '#ffffff10' }}
              label={{ value: 'RETAIL GAS PRICE ($)', angle: -90, position: 'insideLeft', style: { fill: '#64748b', fontSize: '9px', fontWeight: 'black' } }}
            />
            <YAxis 
              yAxisId="right" 
              orientation="right" 
              stroke="#ffffff30" 
              fontSize={10} 
              fontWeight="black" 
              tick={{ fill: '#64748b' }}
              axisLine={{ stroke: '#ffffff10' }}
              label={{ value: 'DEFENSE INDEX (X)', angle: 90, position: 'insideRight', style: { fill: '#64748b', fontSize: '9px', fontWeight: 'black' } }}
            />
            <Tooltip 
              contentStyle={{ 
                backgroundColor: '#020617', 
                border: '1px solid rgba(255,255,255,0.1)', 
                borderRadius: '1rem',
                fontSize: '10px',
                fontWeight: 'black',
                color: '#fff',
                textTransform: 'uppercase'
              }}
              itemStyle={{ padding: '2px 0' }}
            />
            <Legend 
              verticalAlign="top" 
              align="right" 
              iconType="circle" 
              iconSize={8}
              wrapperStyle={{ paddingBottom: '20px', fontSize: '9px', fontWeight: 'black', textTransform: 'uppercase', letterSpacing: '0.1em' }}
            />
            
            <Line 
              yAxisId="left" 
              type="monotone" 
              dataKey="gasPrice" 
              stroke="#f43f5e" 
              strokeWidth={4}
              dot={{ r: 4, fill: '#f43f5e', strokeWidth: 2, stroke: '#000' }}
              activeDot={{ r: 8, fill: '#f43f5e', stroke: '#fff' }}
              name="Retail Energy Cost" 
            />
            <Line 
              yAxisId="right" 
              type="monotone" 
              dataKey="defenseStockIndex" 
              stroke="#10b981" 
              strokeWidth={4}
              dot={{ r: 4, fill: '#10b981', strokeWidth: 2, stroke: '#000' }}
              activeDot={{ r: 8, fill: '#10b981', stroke: '#fff' }}
              name="Defense Equity Index" 
            />

            {chartData.map((entry, index) => (
              entry.conflictEvent && (
                <ReferenceArea 
                  key={index} 
                  x1={entry.date} 
                  x2={entry.date} 
                  stroke="#ffffff10" 
                  fill="#ffffff05"
                  label={{ 
                    position: 'top', 
                    value: entry.conflictEvent, 
                    fill: '#f59e0b', 
                    fontSize: 8, 
                    fontWeight: 'black',
                    letterSpacing: '0.1em'
                  }} 
                />
              )
            ))}
          </LineChart>
        </ResponsiveContainer>
      </div>

      <div className="mt-12 flex flex-col md:flex-row items-center justify-between gap-8 text-[9px] font-black uppercase tracking-[0.4em] text-slate-600">
        <div className="flex items-center gap-6">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-red-500" />
            <span>High Elasticity Range</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-emerald-500" />
            <span>Capital Capture Threshold</span>
          </div>
        </div>
        <div className="text-slate-500 italic">
          Audit Status: Critical Discrepancy Detected in Appropriation Timelines
        </div>
      </div>
    </div>
  );
}