// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/IdentityVerificationGetPostRequest.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdentityVerificationGetPostRequest
 */
export interface IdentityVerificationGetPostRequest {
    /**
     * 
     * @type {string}
     * @memberof IdentityVerificationGetPostRequest
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityVerificationGetPostRequest
     */
    secret?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityVerificationGetPostRequest
     */
    identityVerificationId?: string;
}

/**
 * Check if a given object implements the IdentityVerificationGetPostRequest interface.
 */
export function instanceOfIdentityVerificationGetPostRequest(value: object): value is IdentityVerificationGetPostRequest {
    return true;
}

export function IdentityVerificationGetPostRequestFromJSON(json: any): IdentityVerificationGetPostRequest {
    return IdentityVerificationGetPostRequestFromJSONTyped(json, false);
}

export function IdentityVerificationGetPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityVerificationGetPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'identityVerificationId': json['identity_verification_id'] == null ? undefined : json['identity_verification_id'],
    };
}

export function IdentityVerificationGetPostRequestToJSON(json: any): IdentityVerificationGetPostRequest {
    return IdentityVerificationGetPostRequestToJSONTyped(json, false);
}

export function IdentityVerificationGetPostRequestToJSONTyped(value?: IdentityVerificationGetPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'secret': value['secret'],
        'identity_verification_id': value['identityVerificationId'],
    };
}

