// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/IdentityVerificationCreatePostDefaultResponseTemplate.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdentityVerificationCreatePostDefaultResponseTemplate
 */
export interface IdentityVerificationCreatePostDefaultResponseTemplate {
    /**
     * 
     * @type {string}
     * @memberof IdentityVerificationCreatePostDefaultResponseTemplate
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof IdentityVerificationCreatePostDefaultResponseTemplate
     */
    version?: number;
}

/**
 * Check if a given object implements the IdentityVerificationCreatePostDefaultResponseTemplate interface.
 */
export function instanceOfIdentityVerificationCreatePostDefaultResponseTemplate(value: object): value is IdentityVerificationCreatePostDefaultResponseTemplate {
    return true;
}

export function IdentityVerificationCreatePostDefaultResponseTemplateFromJSON(json: any): IdentityVerificationCreatePostDefaultResponseTemplate {
    return IdentityVerificationCreatePostDefaultResponseTemplateFromJSONTyped(json, false);
}

export function IdentityVerificationCreatePostDefaultResponseTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityVerificationCreatePostDefaultResponseTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function IdentityVerificationCreatePostDefaultResponseTemplateToJSON(json: any): IdentityVerificationCreatePostDefaultResponseTemplate {
    return IdentityVerificationCreatePostDefaultResponseTemplateToJSONTyped(json, false);
}

export function IdentityVerificationCreatePostDefaultResponseTemplateToJSONTyped(value?: IdentityVerificationCreatePostDefaultResponseTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'version': value['version'],
    };
}

