// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/InvoiceInstallmentsCard.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface InvoiceInstallmentsCard
 */
export interface InvoiceInstallmentsCard {
    /**
     * N/A
     * @type {boolean}
     * @memberof InvoiceInstallmentsCard
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the InvoiceInstallmentsCard interface.
 */
export function instanceOfInvoiceInstallmentsCard(value: object): value is InvoiceInstallmentsCard {
    return true;
}

export function InvoiceInstallmentsCardFromJSON(json: any): InvoiceInstallmentsCard {
    return InvoiceInstallmentsCardFromJSONTyped(json, false);
}

export function InvoiceInstallmentsCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceInstallmentsCard {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function InvoiceInstallmentsCardToJSON(json: any): InvoiceInstallmentsCard {
    return InvoiceInstallmentsCardToJSONTyped(json, false);
}

export function InvoiceInstallmentsCardToJSONTyped(value?: InvoiceInstallmentsCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
    };
}

