// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/InvoicesPaymentSettings.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoicesPaymentMethodOptions } from './InvoicesPaymentMethodOptions';
import {
    InvoicesPaymentMethodOptionsFromJSON,
    InvoicesPaymentMethodOptionsFromJSONTyped,
    InvoicesPaymentMethodOptionsToJSON,
    InvoicesPaymentMethodOptionsToJSONTyped,
} from './InvoicesPaymentMethodOptions';

/**
 * N/A
 * @export
 * @interface InvoicesPaymentSettings
 */
export interface InvoicesPaymentSettings {
    /**
     * N/A
     * @type {string}
     * @memberof InvoicesPaymentSettings
     */
    defaultMandate?: string;
    /**
     * 
     * @type {InvoicesPaymentMethodOptions}
     * @memberof InvoicesPaymentSettings
     */
    paymentMethodOptions?: InvoicesPaymentMethodOptions;
    /**
     * N/A
     * @type {Array<string>}
     * @memberof InvoicesPaymentSettings
     */
    paymentMethodTypes?: Array<string>;
}

/**
 * Check if a given object implements the InvoicesPaymentSettings interface.
 */
export function instanceOfInvoicesPaymentSettings(value: object): value is InvoicesPaymentSettings {
    return true;
}

export function InvoicesPaymentSettingsFromJSON(json: any): InvoicesPaymentSettings {
    return InvoicesPaymentSettingsFromJSONTyped(json, false);
}

export function InvoicesPaymentSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoicesPaymentSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultMandate': json['default_mandate'] == null ? undefined : json['default_mandate'],
        'paymentMethodOptions': json['payment_method_options'] == null ? undefined : InvoicesPaymentMethodOptionsFromJSON(json['payment_method_options']),
        'paymentMethodTypes': json['payment_method_types'] == null ? undefined : json['payment_method_types'],
    };
}

export function InvoicesPaymentSettingsToJSON(json: any): InvoicesPaymentSettings {
    return InvoicesPaymentSettingsToJSONTyped(json, false);
}

export function InvoicesPaymentSettingsToJSONTyped(value?: InvoicesPaymentSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default_mandate': value['defaultMandate'],
        'payment_method_options': InvoicesPaymentMethodOptionsToJSON(value['paymentMethodOptions']),
        'payment_method_types': value['paymentMethodTypes'],
    };
}

