// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInner-1.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataInstitution } from './LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataInstitution';
import {
    LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataInstitutionFromJSON,
    LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataInstitutionFromJSONTyped,
    LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataInstitutionToJSON,
    LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataInstitutionToJSONTyped,
} from './LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataInstitution';
import type { LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataAccountsInner } from './LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataAccountsInner';
import {
    LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataAccountsInnerFromJSON,
    LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataAccountsInnerFromJSONTyped,
    LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataAccountsInnerToJSON,
    LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataAccountsInnerToJSONTyped,
} from './LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataAccountsInner';

/**
 * 
 * @export
 * @interface LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInner
 */
export interface LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInner {
    /**
     * 
     * @type {Array<LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataAccountsInner>}
     * @memberof LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInner
     */
    accounts?: Array<LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataAccountsInner>;
    /**
     * 
     * @type {LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataInstitution}
     * @memberof LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInner
     */
    institution?: LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataInstitution;
    /**
     * 
     * @type {string}
     * @memberof LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInner
     */
    publicToken?: string;
}

/**
 * Check if a given object implements the LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInner interface.
 */
export function instanceOfLinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInner(value: object): value is LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInner {
    return true;
}

export function LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInnerFromJSON(json: any): LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInner {
    return LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInnerFromJSONTyped(json, false);
}

export function LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'accounts': json['accounts'] == null ? undefined : ((json['accounts'] as Array<any>).map(LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataAccountsInnerFromJSON)),
        'institution': json['institution'] == null ? undefined : LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataInstitutionFromJSON(json['institution']),
        'publicToken': json['public_token'] == null ? undefined : json['public_token'],
    };
}

export function LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInnerToJSON(json: any): LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInner {
    return LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInnerToJSONTyped(json, false);
}

export function LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInnerToJSONTyped(value?: LinkTokenGetPost200ResponseLinkSessionsInnerResultsItemAddResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accounts': value['accounts'] == null ? undefined : ((value['accounts'] as Array<any>).map(LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataAccountsInnerToJSON)),
        'institution': LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessMetadataInstitutionToJSON(value['institution']),
        'public_token': value['publicToken'],
    };
}

