// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/LinkTokenGetPost200ResponseLinkSessionsInner-1.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LinkTokenGetPost200ResponseLinkSessionsInnerEventsInner } from './LinkTokenGetPost200ResponseLinkSessionsInnerEventsInner';
import {
    LinkTokenGetPost200ResponseLinkSessionsInnerEventsInnerFromJSON,
    LinkTokenGetPost200ResponseLinkSessionsInnerEventsInnerFromJSONTyped,
    LinkTokenGetPost200ResponseLinkSessionsInnerEventsInnerToJSON,
    LinkTokenGetPost200ResponseLinkSessionsInnerEventsInnerToJSONTyped,
} from './LinkTokenGetPost200ResponseLinkSessionsInnerEventsInner';
import type { LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccess } from './LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccess';
import {
    LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessFromJSON,
    LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessFromJSONTyped,
    LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessToJSON,
    LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessToJSONTyped,
} from './LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccess';
import type { LinkTokenGetPost200ResponseLinkSessionsInnerResults } from './LinkTokenGetPost200ResponseLinkSessionsInnerResults';
import {
    LinkTokenGetPost200ResponseLinkSessionsInnerResultsFromJSON,
    LinkTokenGetPost200ResponseLinkSessionsInnerResultsFromJSONTyped,
    LinkTokenGetPost200ResponseLinkSessionsInnerResultsToJSON,
    LinkTokenGetPost200ResponseLinkSessionsInnerResultsToJSONTyped,
} from './LinkTokenGetPost200ResponseLinkSessionsInnerResults';

/**
 * 
 * @export
 * @interface LinkTokenGetPost200ResponseLinkSessionsInner
 */
export interface LinkTokenGetPost200ResponseLinkSessionsInner {
    /**
     * 
     * @type {Array<LinkTokenGetPost200ResponseLinkSessionsInnerEventsInner>}
     * @memberof LinkTokenGetPost200ResponseLinkSessionsInner
     */
    events?: Array<LinkTokenGetPost200ResponseLinkSessionsInnerEventsInner>;
    /**
     * 
     * @type {Date}
     * @memberof LinkTokenGetPost200ResponseLinkSessionsInner
     */
    finishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof LinkTokenGetPost200ResponseLinkSessionsInner
     */
    linkSessionId?: string;
    /**
     * 
     * @type {LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccess}
     * @memberof LinkTokenGetPost200ResponseLinkSessionsInner
     */
    onSuccess?: LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccess;
    /**
     * 
     * @type {LinkTokenGetPost200ResponseLinkSessionsInnerResults}
     * @memberof LinkTokenGetPost200ResponseLinkSessionsInner
     */
    results?: LinkTokenGetPost200ResponseLinkSessionsInnerResults;
    /**
     * 
     * @type {Date}
     * @memberof LinkTokenGetPost200ResponseLinkSessionsInner
     */
    startedAt?: Date;
}

/**
 * Check if a given object implements the LinkTokenGetPost200ResponseLinkSessionsInner interface.
 */
export function instanceOfLinkTokenGetPost200ResponseLinkSessionsInner(value: object): value is LinkTokenGetPost200ResponseLinkSessionsInner {
    return true;
}

export function LinkTokenGetPost200ResponseLinkSessionsInnerFromJSON(json: any): LinkTokenGetPost200ResponseLinkSessionsInner {
    return LinkTokenGetPost200ResponseLinkSessionsInnerFromJSONTyped(json, false);
}

export function LinkTokenGetPost200ResponseLinkSessionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkTokenGetPost200ResponseLinkSessionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'events': json['events'] == null ? undefined : ((json['events'] as Array<any>).map(LinkTokenGetPost200ResponseLinkSessionsInnerEventsInnerFromJSON)),
        'finishedAt': json['finished_at'] == null ? undefined : (new Date(json['finished_at'])),
        'linkSessionId': json['link_session_id'] == null ? undefined : json['link_session_id'],
        'onSuccess': json['on_success'] == null ? undefined : LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessFromJSON(json['on_success']),
        'results': json['results'] == null ? undefined : LinkTokenGetPost200ResponseLinkSessionsInnerResultsFromJSON(json['results']),
        'startedAt': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
    };
}

export function LinkTokenGetPost200ResponseLinkSessionsInnerToJSON(json: any): LinkTokenGetPost200ResponseLinkSessionsInner {
    return LinkTokenGetPost200ResponseLinkSessionsInnerToJSONTyped(json, false);
}

export function LinkTokenGetPost200ResponseLinkSessionsInnerToJSONTyped(value?: LinkTokenGetPost200ResponseLinkSessionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': value['events'] == null ? undefined : ((value['events'] as Array<any>).map(LinkTokenGetPost200ResponseLinkSessionsInnerEventsInnerToJSON)),
        'finished_at': value['finishedAt'] == null ? value['finishedAt'] : value['finishedAt'].toISOString(),
        'link_session_id': value['linkSessionId'],
        'on_success': LinkTokenGetPost200ResponseLinkSessionsInnerOnSuccessToJSON(value['onSuccess']),
        'results': LinkTokenGetPost200ResponseLinkSessionsInnerResultsToJSON(value['results']),
        'started_at': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
    };
}

