// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/PortalFeatures.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PortalCustomerUpdate } from './PortalCustomerUpdate';
import {
    PortalCustomerUpdateFromJSON,
    PortalCustomerUpdateFromJSONTyped,
    PortalCustomerUpdateToJSON,
    PortalCustomerUpdateToJSONTyped,
} from './PortalCustomerUpdate';
import type { PortalSubscriptionCancel } from './PortalSubscriptionCancel';
import {
    PortalSubscriptionCancelFromJSON,
    PortalSubscriptionCancelFromJSONTyped,
    PortalSubscriptionCancelToJSON,
    PortalSubscriptionCancelToJSONTyped,
} from './PortalSubscriptionCancel';
import type { PortalSubscriptionUpdate } from './PortalSubscriptionUpdate';
import {
    PortalSubscriptionUpdateFromJSON,
    PortalSubscriptionUpdateFromJSONTyped,
    PortalSubscriptionUpdateToJSON,
    PortalSubscriptionUpdateToJSONTyped,
} from './PortalSubscriptionUpdate';
import type { PortalInvoiceList } from './PortalInvoiceList';
import {
    PortalInvoiceListFromJSON,
    PortalInvoiceListFromJSONTyped,
    PortalInvoiceListToJSON,
    PortalInvoiceListToJSONTyped,
} from './PortalInvoiceList';
import type { PortalPaymentMethodUpdate } from './PortalPaymentMethodUpdate';
import {
    PortalPaymentMethodUpdateFromJSON,
    PortalPaymentMethodUpdateFromJSONTyped,
    PortalPaymentMethodUpdateToJSON,
    PortalPaymentMethodUpdateToJSONTyped,
} from './PortalPaymentMethodUpdate';

/**
 * N/A
 * @export
 * @interface PortalFeatures
 */
export interface PortalFeatures {
    /**
     * 
     * @type {PortalCustomerUpdate}
     * @memberof PortalFeatures
     */
    customerUpdate: PortalCustomerUpdate;
    /**
     * 
     * @type {PortalInvoiceList}
     * @memberof PortalFeatures
     */
    invoiceHistory: PortalInvoiceList;
    /**
     * 
     * @type {PortalPaymentMethodUpdate}
     * @memberof PortalFeatures
     */
    paymentMethodUpdate: PortalPaymentMethodUpdate;
    /**
     * 
     * @type {PortalSubscriptionCancel}
     * @memberof PortalFeatures
     */
    subscriptionCancel: PortalSubscriptionCancel;
    /**
     * 
     * @type {PortalSubscriptionUpdate}
     * @memberof PortalFeatures
     */
    subscriptionUpdate: PortalSubscriptionUpdate;
}

/**
 * Check if a given object implements the PortalFeatures interface.
 */
export function instanceOfPortalFeatures(value: object): value is PortalFeatures {
    if (!('customerUpdate' in value) || value['customerUpdate'] === undefined) return false;
    if (!('invoiceHistory' in value) || value['invoiceHistory'] === undefined) return false;
    if (!('paymentMethodUpdate' in value) || value['paymentMethodUpdate'] === undefined) return false;
    if (!('subscriptionCancel' in value) || value['subscriptionCancel'] === undefined) return false;
    if (!('subscriptionUpdate' in value) || value['subscriptionUpdate'] === undefined) return false;
    return true;
}

export function PortalFeaturesFromJSON(json: any): PortalFeatures {
    return PortalFeaturesFromJSONTyped(json, false);
}

export function PortalFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortalFeatures {
    if (json == null) {
        return json;
    }
    return {
        
        'customerUpdate': PortalCustomerUpdateFromJSON(json['customer_update']),
        'invoiceHistory': PortalInvoiceListFromJSON(json['invoice_history']),
        'paymentMethodUpdate': PortalPaymentMethodUpdateFromJSON(json['payment_method_update']),
        'subscriptionCancel': PortalSubscriptionCancelFromJSON(json['subscription_cancel']),
        'subscriptionUpdate': PortalSubscriptionUpdateFromJSON(json['subscription_update']),
    };
}

export function PortalFeaturesToJSON(json: any): PortalFeatures {
    return PortalFeaturesToJSONTyped(json, false);
}

export function PortalFeaturesToJSONTyped(value?: PortalFeatures | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customer_update': PortalCustomerUpdateToJSON(value['customerUpdate']),
        'invoice_history': PortalInvoiceListToJSON(value['invoiceHistory']),
        'payment_method_update': PortalPaymentMethodUpdateToJSON(value['paymentMethodUpdate']),
        'subscription_cancel': PortalSubscriptionCancelToJSON(value['subscriptionCancel']),
        'subscription_update': PortalSubscriptionUpdateToJSON(value['subscriptionUpdate']),
    };
}

