// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/TaxProductResourceTaxCode.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface TaxProductResourceTaxCode
 */
export interface TaxProductResourceTaxCode {
    /**
     * N/A
     * @type {string}
     * @memberof TaxProductResourceTaxCode
     */
    id: string;
    /**
     * N/A
     * @type {string}
     * @memberof TaxProductResourceTaxCode
     */
    name: string;
    /**
     * N/A
     * @type {TaxProductResourceTaxCodeObjectEnum}
     * @memberof TaxProductResourceTaxCode
     */
    object: TaxProductResourceTaxCodeObjectEnum;
}


/**
 * @export
 */
export const TaxProductResourceTaxCodeObjectEnum = {
    TaxCode: 'tax_code'
} as const;
export type TaxProductResourceTaxCodeObjectEnum = typeof TaxProductResourceTaxCodeObjectEnum[keyof typeof TaxProductResourceTaxCodeObjectEnum];


/**
 * Check if a given object implements the TaxProductResourceTaxCode interface.
 */
export function instanceOfTaxProductResourceTaxCode(value: object): value is TaxProductResourceTaxCode {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    return true;
}

export function TaxProductResourceTaxCodeFromJSON(json: any): TaxProductResourceTaxCode {
    return TaxProductResourceTaxCodeFromJSONTyped(json, false);
}

export function TaxProductResourceTaxCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxProductResourceTaxCode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'object': json['object'],
    };
}

export function TaxProductResourceTaxCodeToJSON(json: any): TaxProductResourceTaxCode {
    return TaxProductResourceTaxCodeToJSONTyped(json, false);
}

export function TaxProductResourceTaxCodeToJSONTyped(value?: TaxProductResourceTaxCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'object': value['object'],
    };
}

