// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerTaxRateDetails } from './V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerTaxRateDetails';
import {
    V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerTaxRateDetailsFromJSON,
    V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerTaxRateDetailsFromJSONTyped,
    V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerTaxRateDetailsToJSON,
    V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerTaxRateDetailsToJSONTyped,
} from './V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerTaxRateDetails';
import type { V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerJurisdiction } from './V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerJurisdiction';
import {
    V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerJurisdictionFromJSON,
    V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerJurisdictionFromJSONTyped,
    V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerJurisdictionToJSON,
    V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerJurisdictionToJSONTyped,
} from './V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerJurisdiction';

/**
 * 
 * @export
 * @interface V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner
 */
export interface V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner {
    /**
     * 
     * @type {number}
     * @memberof V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner
     */
    amount?: number;
    /**
     * 
     * @type {V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerJurisdiction}
     * @memberof V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner
     */
    jurisdiction?: V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerJurisdiction;
    /**
     * 
     * @type {string}
     * @memberof V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner
     */
    sourcing?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner
     */
    taxabilityReason?: string;
    /**
     * 
     * @type {number}
     * @memberof V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner
     */
    taxableAmount?: number;
    /**
     * 
     * @type {V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerTaxRateDetails}
     * @memberof V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner
     */
    taxRateDetails?: V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerTaxRateDetails;
}

/**
 * Check if a given object implements the V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner interface.
 */
export function instanceOfV1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner(value: object): value is V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner {
    return true;
}

export function V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerFromJSON(json: any): V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner {
    return V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerFromJSONTyped(json, false);
}

export function V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'jurisdiction': json['jurisdiction'] == null ? undefined : V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerJurisdictionFromJSON(json['jurisdiction']),
        'sourcing': json['sourcing'] == null ? undefined : json['sourcing'],
        'taxabilityReason': json['taxability_reason'] == null ? undefined : json['taxability_reason'],
        'taxableAmount': json['taxable_amount'] == null ? undefined : json['taxable_amount'],
        'taxRateDetails': json['tax_rate_details'] == null ? undefined : V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerTaxRateDetailsFromJSON(json['tax_rate_details']),
    };
}

export function V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerToJSON(json: any): V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner {
    return V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerToJSONTyped(json, false);
}

export function V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerToJSONTyped(value?: V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'jurisdiction': V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerJurisdictionToJSON(value['jurisdiction']),
        'sourcing': value['sourcing'],
        'taxability_reason': value['taxabilityReason'],
        'taxable_amount': value['taxableAmount'],
        'tax_rate_details': V1TaxCalculationsPost200ResponseLineItemsDataInnerTaxBreakdownInnerTaxRateDetailsToJSON(value['taxRateDetails']),
    };
}

