// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount
 */
export interface V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount {
    /**
     * 
     * @type {string}
     * @memberof V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount
     */
    network?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount
     */
    accountHolderType?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount
     */
    accountType?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount
     */
    bankName?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount
     */
    fingerprint?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount
     */
    last4?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount
     */
    mandate?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount
     */
    routingNumber?: string;
}

/**
 * Check if a given object implements the V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount interface.
 */
export function instanceOfV1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount(value: object): value is V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount {
    return true;
}

export function V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccountFromJSON(json: any): V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount {
    return V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccountFromJSONTyped(json, false);
}

export function V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'network': json['network'] == null ? undefined : json['network'],
        'accountHolderType': json['account_holder_type'] == null ? undefined : json['account_holder_type'],
        'accountType': json['account_type'] == null ? undefined : json['account_type'],
        'bankName': json['bank_name'] == null ? undefined : json['bank_name'],
        'fingerprint': json['fingerprint'] == null ? undefined : json['fingerprint'],
        'last4': json['last4'] == null ? undefined : json['last4'],
        'mandate': json['mandate'] == null ? undefined : json['mandate'],
        'routingNumber': json['routing_number'] == null ? undefined : json['routing_number'],
    };
}

export function V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccountToJSON(json: any): V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount {
    return V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccountToJSONTyped(json, false);
}

export function V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccountToJSONTyped(value?: V1TestHelpersTreasuryOutboundPaymentsIdPost200ResponseDestinationPaymentMethodDetailsUsBankAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': value['network'],
        'account_holder_type': value['accountHolderType'],
        'account_type': value['accountType'],
        'bank_name': value['bankName'],
        'fingerprint': value['fingerprint'],
        'last4': value['last4'],
        'mandate': value['mandate'],
        'routing_number': value['routingNumber'],
    };
}

