// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/AccountBrandingSettings1.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface AccountBrandingSettings1
 */
export interface AccountBrandingSettings1 {
    /**
     * 
     * @type {string}
     * @memberof AccountBrandingSettings1
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountBrandingSettings1
     */
    logo?: string;
    /**
     * N/A
     * @type {string}
     * @memberof AccountBrandingSettings1
     */
    primaryColor?: string;
    /**
     * N/A
     * @type {string}
     * @memberof AccountBrandingSettings1
     */
    secondaryColor?: string;
}

/**
 * Check if a given object implements the AccountBrandingSettings1 interface.
 */
export function instanceOfAccountBrandingSettings1(value: object): value is AccountBrandingSettings1 {
    return true;
}

export function AccountBrandingSettings1FromJSON(json: any): AccountBrandingSettings1 {
    return AccountBrandingSettings1FromJSONTyped(json, false);
}

export function AccountBrandingSettings1FromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountBrandingSettings1 {
    if (json == null) {
        return json;
    }
    return {
        
        'icon': json['icon'] == null ? undefined : json['icon'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'primaryColor': json['primary_color'] == null ? undefined : json['primary_color'],
        'secondaryColor': json['secondary_color'] == null ? undefined : json['secondary_color'],
    };
}

export function AccountBrandingSettings1ToJSON(json: any): AccountBrandingSettings1 {
    return AccountBrandingSettings1ToJSONTyped(json, false);
}

export function AccountBrandingSettings1ToJSONTyped(value?: AccountBrandingSettings1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icon': value['icon'],
        'logo': value['logo'],
        'primary_color': value['primaryColor'],
        'secondary_color': value['secondaryColor'],
    };
}

