// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/ApiConnectionsGet200ResponseInner.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiConnectionsGet200ResponseInner
 */
export interface ApiConnectionsGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ApiConnectionsGet200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConnectionsGet200ResponseInner
     */
    object: string;
    /**
     * N/A
     * @type {boolean}
     * @memberof ApiConnectionsGet200ResponseInner
     */
    liveMode: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ApiConnectionsGet200ResponseInner
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiConnectionsGet200ResponseInner
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiConnectionsGet200ResponseInner
     */
    discardedAt: Date;
    /**
     * N/A
     * @type {string}
     * @memberof ApiConnectionsGet200ResponseInner
     */
    vendorId: string;
    /**
     * N/A
     * @type {string}
     * @memberof ApiConnectionsGet200ResponseInner
     */
    vendorCustomerId: string;
    /**
     * N/A
     * @type {string}
     * @memberof ApiConnectionsGet200ResponseInner
     */
    vendorName: string;
}

/**
 * Check if a given object implements the ApiConnectionsGet200ResponseInner interface.
 */
export function instanceOfApiConnectionsGet200ResponseInner(value: object): value is ApiConnectionsGet200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('liveMode' in value) || value['liveMode'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('discardedAt' in value) || value['discardedAt'] === undefined) return false;
    if (!('vendorId' in value) || value['vendorId'] === undefined) return false;
    if (!('vendorCustomerId' in value) || value['vendorCustomerId'] === undefined) return false;
    if (!('vendorName' in value) || value['vendorName'] === undefined) return false;
    return true;
}

export function ApiConnectionsGet200ResponseInnerFromJSON(json: any): ApiConnectionsGet200ResponseInner {
    return ApiConnectionsGet200ResponseInnerFromJSONTyped(json, false);
}

export function ApiConnectionsGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiConnectionsGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'liveMode': json['live_mode'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'discardedAt': (new Date(json['discarded_at'])),
        'vendorId': json['vendor_id'],
        'vendorCustomerId': json['vendor_customer_id'],
        'vendorName': json['vendor_name'],
    };
}

export function ApiConnectionsGet200ResponseInnerToJSON(json: any): ApiConnectionsGet200ResponseInner {
    return ApiConnectionsGet200ResponseInnerToJSONTyped(json, false);
}

export function ApiConnectionsGet200ResponseInnerToJSONTyped(value?: ApiConnectionsGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'live_mode': value['liveMode'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'discarded_at': value['discardedAt'].toISOString(),
        'vendor_id': value['vendorId'],
        'vendor_customer_id': value['vendorCustomerId'],
        'vendor_name': value['vendorName'],
    };
}

