// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/ApiPaymentReferencesGet200ResponseInner.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiPaymentReferencesGet200ResponseInner
 */
export interface ApiPaymentReferencesGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ApiPaymentReferencesGet200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPaymentReferencesGet200ResponseInner
     */
    object: string;
    /**
     * N/A
     * @type {boolean}
     * @memberof ApiPaymentReferencesGet200ResponseInner
     */
    liveMode: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ApiPaymentReferencesGet200ResponseInner
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiPaymentReferencesGet200ResponseInner
     */
    updatedAt: Date;
    /**
     * N/A
     * @type {string}
     * @memberof ApiPaymentReferencesGet200ResponseInner
     */
    referenceableId: string;
    /**
     * N/A
     * @type {ApiPaymentReferencesGet200ResponseInnerReferenceableTypeEnum}
     * @memberof ApiPaymentReferencesGet200ResponseInner
     */
    referenceableType: ApiPaymentReferencesGet200ResponseInnerReferenceableTypeEnum;
    /**
     * N/A
     * @type {string}
     * @memberof ApiPaymentReferencesGet200ResponseInner
     */
    referenceNumber: string;
    /**
     * N/A
     * @type {ApiPaymentReferencesGet200ResponseInnerReferenceNumberTypeEnum}
     * @memberof ApiPaymentReferencesGet200ResponseInner
     */
    referenceNumberType: ApiPaymentReferencesGet200ResponseInnerReferenceNumberTypeEnum;
}


/**
 * @export
 */
export const ApiPaymentReferencesGet200ResponseInnerReferenceableTypeEnum = {
    PaymentOrder: 'payment_order',
    Reversal: 'reversal',
    Return: 'return'
} as const;
export type ApiPaymentReferencesGet200ResponseInnerReferenceableTypeEnum = typeof ApiPaymentReferencesGet200ResponseInnerReferenceableTypeEnum[keyof typeof ApiPaymentReferencesGet200ResponseInnerReferenceableTypeEnum];

/**
 * @export
 */
export const ApiPaymentReferencesGet200ResponseInnerReferenceNumberTypeEnum = {
    AchOriginalTraceNumber: 'ach_original_trace_number',
    AchTraceNumber: 'ach_trace_number',
    BankprovPaymentActivityDate: 'bankprov_payment_activity_date',
    BankprovPaymentId: 'bankprov_payment_id',
    BnkDevPrenotificationId: 'bnk_dev_prenotification_id',
    BnkDevTransferId: 'bnk_dev_transfer_id',
    BofaEndToEndId: 'bofa_end_to_end_id',
    BofaTransactionId: 'bofa_transaction_id',
    CheckNumber: 'check_number',
    ColumnFxQuoteId: 'column_fx_quote_id',
    ColumnReversalPairTransferId: 'column_reversal_pair_transfer_id',
    ColumnTransferId: 'column_transfer_id',
    CrossRiverPaymentId: 'cross_river_payment_id',
    CrossRiverTransactionId: 'cross_river_transaction_id',
    CurrencycloudConversionId: 'currencycloud_conversion_id',
    CurrencycloudPaymentId: 'currencycloud_payment_id',
    DcBankTransactionId: 'dc_bank_transaction_id',
    DwollaTransactionId: 'dwolla_transaction_id',
    EftTraceNumber: 'eft_trace_number',
    EvolveTransactionId: 'evolve_transaction_id',
    FedwireImad: 'fedwire_imad',
    FedwireOmad: 'fedwire_omad',
    FirstRepublicInternalId: 'first_republic_internal_id',
    GoldmanSachsCollectionRequestId: 'goldman_sachs_collection_request_id',
    GoldmanSachsEndToEndId: 'goldman_sachs_end_to_end_id',
    GoldmanSachsPaymentRequestId: 'goldman_sachs_payment_request_id',
    GoldmanSachsRequestId: 'goldman_sachs_request_id',
    GoldmanSachsUniquePaymentId: 'goldman_sachs_unique_payment_id',
    InteracMessageId: 'interac_message_id',
    JpmcCcn: 'jpmc_ccn',
    JpmcCustomerReferenceId: 'jpmc_customer_reference_id',
    JpmcEndToEndId: 'jpmc_end_to_end_id',
    JpmcFirmRootId: 'jpmc_firm_root_id',
    JpmcP3Id: 'jpmc_p3_id',
    JpmcPaymentBatchId: 'jpmc_payment_batch_id',
    JpmcPaymentInformationId: 'jpmc_payment_information_id',
    JpmcPaymentReturnedDatetime: 'jpmc_payment_returned_datetime',
    LobCheckId: 'lob_check_id',
    Other: 'other',
    PartialSwiftMir: 'partial_swift_mir',
    PncClearingReference: 'pnc_clearing_reference',
    PncInstructionId: 'pnc_instruction_id',
    PncMultipaymentId: 'pnc_multipayment_id',
    PncPaymentTraceId: 'pnc_payment_trace_id',
    RspecVendorPaymentId: 'rspec_vendor_payment_id',
    RtpInstructionId: 'rtp_instruction_id',
    SignetApiReferenceId: 'signet_api_reference_id',
    SignetConfirmationId: 'signet_confirmation_id',
    SignetRequestId: 'signet_request_id',
    SilvergatePaymentId: 'silvergate_payment_id',
    SwiftMir: 'swift_mir',
    SwiftUetr: 'swift_uetr',
    UsbankPaymentId: 'usbank_payment_id',
    WellsFargoPaymentId: 'wells_fargo_payment_id',
    WellsFargoTraceNumber: 'wells_fargo_trace_number'
} as const;
export type ApiPaymentReferencesGet200ResponseInnerReferenceNumberTypeEnum = typeof ApiPaymentReferencesGet200ResponseInnerReferenceNumberTypeEnum[keyof typeof ApiPaymentReferencesGet200ResponseInnerReferenceNumberTypeEnum];


/**
 * Check if a given object implements the ApiPaymentReferencesGet200ResponseInner interface.
 */
export function instanceOfApiPaymentReferencesGet200ResponseInner(value: object): value is ApiPaymentReferencesGet200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('liveMode' in value) || value['liveMode'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('referenceableId' in value) || value['referenceableId'] === undefined) return false;
    if (!('referenceableType' in value) || value['referenceableType'] === undefined) return false;
    if (!('referenceNumber' in value) || value['referenceNumber'] === undefined) return false;
    if (!('referenceNumberType' in value) || value['referenceNumberType'] === undefined) return false;
    return true;
}

export function ApiPaymentReferencesGet200ResponseInnerFromJSON(json: any): ApiPaymentReferencesGet200ResponseInner {
    return ApiPaymentReferencesGet200ResponseInnerFromJSONTyped(json, false);
}

export function ApiPaymentReferencesGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPaymentReferencesGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'liveMode': json['live_mode'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'referenceableId': json['referenceable_id'],
        'referenceableType': json['referenceable_type'],
        'referenceNumber': json['reference_number'],
        'referenceNumberType': json['reference_number_type'],
    };
}

export function ApiPaymentReferencesGet200ResponseInnerToJSON(json: any): ApiPaymentReferencesGet200ResponseInner {
    return ApiPaymentReferencesGet200ResponseInnerToJSONTyped(json, false);
}

export function ApiPaymentReferencesGet200ResponseInnerToJSONTyped(value?: ApiPaymentReferencesGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'live_mode': value['liveMode'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'referenceable_id': value['referenceableId'],
        'referenceable_type': value['referenceableType'],
        'reference_number': value['referenceNumber'],
        'reference_number_type': value['referenceNumberType'],
    };
}

