// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/ApiVirtualAccountsIdPatchRequest.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiVirtualAccountsIdPatchRequest
 */
export interface ApiVirtualAccountsIdPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiVirtualAccountsIdPatchRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVirtualAccountsIdPatchRequest
     */
    counterpartyId?: string;
    /**
     * 
     * @type {object}
     * @memberof ApiVirtualAccountsIdPatchRequest
     */
    metadata?: object;
}

/**
 * Check if a given object implements the ApiVirtualAccountsIdPatchRequest interface.
 */
export function instanceOfApiVirtualAccountsIdPatchRequest(value: object): value is ApiVirtualAccountsIdPatchRequest {
    return true;
}

export function ApiVirtualAccountsIdPatchRequestFromJSON(json: any): ApiVirtualAccountsIdPatchRequest {
    return ApiVirtualAccountsIdPatchRequestFromJSONTyped(json, false);
}

export function ApiVirtualAccountsIdPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVirtualAccountsIdPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'counterpartyId': json['counterparty_id'] == null ? undefined : json['counterparty_id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ApiVirtualAccountsIdPatchRequestToJSON(json: any): ApiVirtualAccountsIdPatchRequest {
    return ApiVirtualAccountsIdPatchRequestToJSONTyped(json, false);
}

export function ApiVirtualAccountsIdPatchRequestToJSONTyped(value?: ApiVirtualAccountsIdPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'counterparty_id': value['counterpartyId'],
        'metadata': value['metadata'],
    };
}

