// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/BalanceDetailUngated.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BalanceAmount } from './BalanceAmount';
import {
    BalanceAmountFromJSON,
    BalanceAmountFromJSONTyped,
    BalanceAmountToJSON,
    BalanceAmountToJSONTyped,
} from './BalanceAmount';

/**
 * N/A
 * @export
 * @interface BalanceDetailUngated
 */
export interface BalanceDetailUngated {
    /**
     * N/A
     * @type {Array<BalanceAmount>}
     * @memberof BalanceDetailUngated
     */
    available: Array<BalanceAmount>;
    /**
     * N/A
     * @type {Array<BalanceAmount>}
     * @memberof BalanceDetailUngated
     */
    pending: Array<BalanceAmount>;
}

/**
 * Check if a given object implements the BalanceDetailUngated interface.
 */
export function instanceOfBalanceDetailUngated(value: object): value is BalanceDetailUngated {
    if (!('available' in value) || value['available'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    return true;
}

export function BalanceDetailUngatedFromJSON(json: any): BalanceDetailUngated {
    return BalanceDetailUngatedFromJSONTyped(json, false);
}

export function BalanceDetailUngatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceDetailUngated {
    if (json == null) {
        return json;
    }
    return {
        
        'available': ((json['available'] as Array<any>).map(BalanceAmountFromJSON)),
        'pending': ((json['pending'] as Array<any>).map(BalanceAmountFromJSON)),
    };
}

export function BalanceDetailUngatedToJSON(json: any): BalanceDetailUngated {
    return BalanceDetailUngatedToJSONTyped(json, false);
}

export function BalanceDetailUngatedToJSONTyped(value?: BalanceDetailUngated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available': ((value['available'] as Array<any>).map(BalanceAmountToJSON)),
        'pending': ((value['pending'] as Array<any>).map(BalanceAmountToJSON)),
    };
}

