// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/ChargeList.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface ChargeList
 */
export interface ChargeList {
    /**
     * 
     * @type {Array<any>}
     * @memberof ChargeList
     */
    data: Array<any>;
    /**
     * N/A
     * @type {boolean}
     * @memberof ChargeList
     */
    hasMore: boolean;
    /**
     * N/A
     * @type {ChargeListObjectEnum}
     * @memberof ChargeList
     */
    object: ChargeListObjectEnum;
    /**
     * N/A
     * @type {string}
     * @memberof ChargeList
     */
    url: string;
}


/**
 * @export
 */
export const ChargeListObjectEnum = {
    List: 'list'
} as const;
export type ChargeListObjectEnum = typeof ChargeListObjectEnum[keyof typeof ChargeListObjectEnum];


/**
 * Check if a given object implements the ChargeList interface.
 */
export function instanceOfChargeList(value: object): value is ChargeList {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ChargeListFromJSON(json: any): ChargeList {
    return ChargeListFromJSONTyped(json, false);
}

export function ChargeListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChargeList {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'hasMore': json['has_more'],
        'object': json['object'],
        'url': json['url'],
    };
}

export function ChargeListToJSON(json: any): ChargeList {
    return ChargeListToJSONTyped(json, false);
}

export function ChargeListToJSONTyped(value?: ChargeList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'has_more': value['hasMore'],
        'object': value['object'],
        'url': value['url'],
    };
}

