// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/ConnectEmbeddedPayoutsFeatures.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface ConnectEmbeddedPayoutsFeatures
 */
export interface ConnectEmbeddedPayoutsFeatures {
    /**
     * N/A
     * @type {boolean}
     * @memberof ConnectEmbeddedPayoutsFeatures
     */
    disableStripeUserAuthentication: boolean;
    /**
     * N/A
     * @type {boolean}
     * @memberof ConnectEmbeddedPayoutsFeatures
     */
    editPayoutSchedule: boolean;
    /**
     * N/A
     * @type {boolean}
     * @memberof ConnectEmbeddedPayoutsFeatures
     */
    externalAccountCollection: boolean;
    /**
     * N/A
     * @type {boolean}
     * @memberof ConnectEmbeddedPayoutsFeatures
     */
    instantPayouts: boolean;
    /**
     * N/A
     * @type {boolean}
     * @memberof ConnectEmbeddedPayoutsFeatures
     */
    standardPayouts: boolean;
}

/**
 * Check if a given object implements the ConnectEmbeddedPayoutsFeatures interface.
 */
export function instanceOfConnectEmbeddedPayoutsFeatures(value: object): value is ConnectEmbeddedPayoutsFeatures {
    if (!('disableStripeUserAuthentication' in value) || value['disableStripeUserAuthentication'] === undefined) return false;
    if (!('editPayoutSchedule' in value) || value['editPayoutSchedule'] === undefined) return false;
    if (!('externalAccountCollection' in value) || value['externalAccountCollection'] === undefined) return false;
    if (!('instantPayouts' in value) || value['instantPayouts'] === undefined) return false;
    if (!('standardPayouts' in value) || value['standardPayouts'] === undefined) return false;
    return true;
}

export function ConnectEmbeddedPayoutsFeaturesFromJSON(json: any): ConnectEmbeddedPayoutsFeatures {
    return ConnectEmbeddedPayoutsFeaturesFromJSONTyped(json, false);
}

export function ConnectEmbeddedPayoutsFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectEmbeddedPayoutsFeatures {
    if (json == null) {
        return json;
    }
    return {
        
        'disableStripeUserAuthentication': json['disable_stripe_user_authentication'],
        'editPayoutSchedule': json['edit_payout_schedule'],
        'externalAccountCollection': json['external_account_collection'],
        'instantPayouts': json['instant_payouts'],
        'standardPayouts': json['standard_payouts'],
    };
}

export function ConnectEmbeddedPayoutsFeaturesToJSON(json: any): ConnectEmbeddedPayoutsFeatures {
    return ConnectEmbeddedPayoutsFeaturesToJSONTyped(json, false);
}

export function ConnectEmbeddedPayoutsFeaturesToJSONTyped(value?: ConnectEmbeddedPayoutsFeatures | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disable_stripe_user_authentication': value['disableStripeUserAuthentication'],
        'edit_payout_schedule': value['editPayoutSchedule'],
        'external_account_collection': value['externalAccountCollection'],
        'instant_payouts': value['instantPayouts'],
        'standard_payouts': value['standardPayouts'],
    };
}

