// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeSourcesInner } from './CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeSourcesInner';
import {
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeSourcesInnerFromJSON,
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeSourcesInnerFromJSONTyped,
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeSourcesInnerToJSON,
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeSourcesInnerToJSONTyped,
} from './CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeSourcesInner';
import type { CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeAccountsInner } from './CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeAccountsInner';
import {
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeAccountsInnerFromJSON,
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeAccountsInnerFromJSONTyped,
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeAccountsInnerToJSON,
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeAccountsInnerToJSONTyped,
} from './CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeAccountsInner';

/**
 * 
 * @export
 * @interface CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner
 */
export interface CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner {
    /**
     * 
     * @type {Array<CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeAccountsInner>}
     * @memberof CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner
     */
    bankIncomeAccounts?: Array<CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeAccountsInner>;
    /**
     * 
     * @type {Array<CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeSourcesInner>}
     * @memberof CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner
     */
    bankIncomeSources?: Array<CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeSourcesInner>;
    /**
     * 
     * @type {string}
     * @memberof CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner
     */
    insitutionName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner
     */
    institutionId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner
     */
    itemId?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner
     */
    lastUpdatedTime?: Date;
}

/**
 * Check if a given object implements the CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner interface.
 */
export function instanceOfCreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner(value: object): value is CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner {
    return true;
}

export function CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerFromJSON(json: any): CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner {
    return CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerFromJSONTyped(json, false);
}

export function CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'bankIncomeAccounts': json['bank_income_accounts'] == null ? undefined : ((json['bank_income_accounts'] as Array<any>).map(CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeAccountsInnerFromJSON)),
        'bankIncomeSources': json['bank_income_sources'] == null ? undefined : ((json['bank_income_sources'] as Array<any>).map(CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeSourcesInnerFromJSON)),
        'insitutionName': json['insitution_name'] == null ? undefined : json['insitution_name'],
        'institutionId': json['institution_id'] == null ? undefined : json['institution_id'],
        'itemId': json['item_id'] == null ? undefined : json['item_id'],
        'lastUpdatedTime': json['last_updated_time'] == null ? undefined : (new Date(json['last_updated_time'])),
    };
}

export function CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerToJSON(json: any): CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner {
    return CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerToJSONTyped(json, false);
}

export function CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerToJSONTyped(value?: CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bank_income_accounts': value['bankIncomeAccounts'] == null ? undefined : ((value['bankIncomeAccounts'] as Array<any>).map(CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeAccountsInnerToJSON)),
        'bank_income_sources': value['bankIncomeSources'] == null ? undefined : ((value['bankIncomeSources'] as Array<any>).map(CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerBankIncomeSourcesInnerToJSON)),
        'insitution_name': value['insitutionName'],
        'institution_id': value['institutionId'],
        'item_id': value['itemId'],
        'last_updated_time': value['lastUpdatedTime'] == null ? value['lastUpdatedTime'] : value['lastUpdatedTime'].toISOString(),
    };
}

