// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/IdentityDocumentsUploadsGetPost200ResponseAccountsInner.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdentityDocumentsUploadsGetPost200ResponseAccountsInnerBalances } from './IdentityDocumentsUploadsGetPost200ResponseAccountsInnerBalances';
import {
    IdentityDocumentsUploadsGetPost200ResponseAccountsInnerBalancesFromJSON,
    IdentityDocumentsUploadsGetPost200ResponseAccountsInnerBalancesFromJSONTyped,
    IdentityDocumentsUploadsGetPost200ResponseAccountsInnerBalancesToJSON,
    IdentityDocumentsUploadsGetPost200ResponseAccountsInnerBalancesToJSONTyped,
} from './IdentityDocumentsUploadsGetPost200ResponseAccountsInnerBalances';
import type { IdentityDocumentsUploadsGetPost200ResponseAccountsInnerOwnersInner } from './IdentityDocumentsUploadsGetPost200ResponseAccountsInnerOwnersInner';
import {
    IdentityDocumentsUploadsGetPost200ResponseAccountsInnerOwnersInnerFromJSON,
    IdentityDocumentsUploadsGetPost200ResponseAccountsInnerOwnersInnerFromJSONTyped,
    IdentityDocumentsUploadsGetPost200ResponseAccountsInnerOwnersInnerToJSON,
    IdentityDocumentsUploadsGetPost200ResponseAccountsInnerOwnersInnerToJSONTyped,
} from './IdentityDocumentsUploadsGetPost200ResponseAccountsInnerOwnersInner';
import type { IdentityDocumentsUploadsGetPost200ResponseAccountsInnerDocumentsInner } from './IdentityDocumentsUploadsGetPost200ResponseAccountsInnerDocumentsInner';
import {
    IdentityDocumentsUploadsGetPost200ResponseAccountsInnerDocumentsInnerFromJSON,
    IdentityDocumentsUploadsGetPost200ResponseAccountsInnerDocumentsInnerFromJSONTyped,
    IdentityDocumentsUploadsGetPost200ResponseAccountsInnerDocumentsInnerToJSON,
    IdentityDocumentsUploadsGetPost200ResponseAccountsInnerDocumentsInnerToJSONTyped,
} from './IdentityDocumentsUploadsGetPost200ResponseAccountsInnerDocumentsInner';

/**
 * 
 * @export
 * @interface IdentityDocumentsUploadsGetPost200ResponseAccountsInner
 */
export interface IdentityDocumentsUploadsGetPost200ResponseAccountsInner {
    /**
     * 
     * @type {string}
     * @memberof IdentityDocumentsUploadsGetPost200ResponseAccountsInner
     */
    accountId?: string;
    /**
     * 
     * @type {IdentityDocumentsUploadsGetPost200ResponseAccountsInnerBalances}
     * @memberof IdentityDocumentsUploadsGetPost200ResponseAccountsInner
     */
    balances?: IdentityDocumentsUploadsGetPost200ResponseAccountsInnerBalances;
    /**
     * 
     * @type {Array<IdentityDocumentsUploadsGetPost200ResponseAccountsInnerDocumentsInner>}
     * @memberof IdentityDocumentsUploadsGetPost200ResponseAccountsInner
     */
    documents?: Array<IdentityDocumentsUploadsGetPost200ResponseAccountsInnerDocumentsInner>;
    /**
     * 
     * @type {string}
     * @memberof IdentityDocumentsUploadsGetPost200ResponseAccountsInner
     */
    mask?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityDocumentsUploadsGetPost200ResponseAccountsInner
     */
    name?: string;
    /**
     * 
     * @type {Array<IdentityDocumentsUploadsGetPost200ResponseAccountsInnerOwnersInner>}
     * @memberof IdentityDocumentsUploadsGetPost200ResponseAccountsInner
     */
    owners?: Array<IdentityDocumentsUploadsGetPost200ResponseAccountsInnerOwnersInner>;
    /**
     * 
     * @type {string}
     * @memberof IdentityDocumentsUploadsGetPost200ResponseAccountsInner
     */
    subtype?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityDocumentsUploadsGetPost200ResponseAccountsInner
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityDocumentsUploadsGetPost200ResponseAccountsInner
     */
    verificationStatus?: string;
}

/**
 * Check if a given object implements the IdentityDocumentsUploadsGetPost200ResponseAccountsInner interface.
 */
export function instanceOfIdentityDocumentsUploadsGetPost200ResponseAccountsInner(value: object): value is IdentityDocumentsUploadsGetPost200ResponseAccountsInner {
    return true;
}

export function IdentityDocumentsUploadsGetPost200ResponseAccountsInnerFromJSON(json: any): IdentityDocumentsUploadsGetPost200ResponseAccountsInner {
    return IdentityDocumentsUploadsGetPost200ResponseAccountsInnerFromJSONTyped(json, false);
}

export function IdentityDocumentsUploadsGetPost200ResponseAccountsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityDocumentsUploadsGetPost200ResponseAccountsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'balances': json['balances'] == null ? undefined : IdentityDocumentsUploadsGetPost200ResponseAccountsInnerBalancesFromJSON(json['balances']),
        'documents': json['documents'] == null ? undefined : ((json['documents'] as Array<any>).map(IdentityDocumentsUploadsGetPost200ResponseAccountsInnerDocumentsInnerFromJSON)),
        'mask': json['mask'] == null ? undefined : json['mask'],
        'name': json['name'] == null ? undefined : json['name'],
        'owners': json['owners'] == null ? undefined : ((json['owners'] as Array<any>).map(IdentityDocumentsUploadsGetPost200ResponseAccountsInnerOwnersInnerFromJSON)),
        'subtype': json['subtype'] == null ? undefined : json['subtype'],
        'type': json['type'] == null ? undefined : json['type'],
        'verificationStatus': json['verification_status'] == null ? undefined : json['verification_status'],
    };
}

export function IdentityDocumentsUploadsGetPost200ResponseAccountsInnerToJSON(json: any): IdentityDocumentsUploadsGetPost200ResponseAccountsInner {
    return IdentityDocumentsUploadsGetPost200ResponseAccountsInnerToJSONTyped(json, false);
}

export function IdentityDocumentsUploadsGetPost200ResponseAccountsInnerToJSONTyped(value?: IdentityDocumentsUploadsGetPost200ResponseAccountsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'balances': IdentityDocumentsUploadsGetPost200ResponseAccountsInnerBalancesToJSON(value['balances']),
        'documents': value['documents'] == null ? undefined : ((value['documents'] as Array<any>).map(IdentityDocumentsUploadsGetPost200ResponseAccountsInnerDocumentsInnerToJSON)),
        'mask': value['mask'],
        'name': value['name'],
        'owners': value['owners'] == null ? undefined : ((value['owners'] as Array<any>).map(IdentityDocumentsUploadsGetPost200ResponseAccountsInnerOwnersInnerToJSON)),
        'subtype': value['subtype'],
        'type': value['type'],
        'verification_status': value['verificationStatus'],
    };
}

