// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/IssuingAuthorizationThreeDSecure.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface IssuingAuthorizationThreeDSecure
 */
export interface IssuingAuthorizationThreeDSecure {
    /**
     * N/A
     * @type {IssuingAuthorizationThreeDSecureResultEnum}
     * @memberof IssuingAuthorizationThreeDSecure
     */
    result: IssuingAuthorizationThreeDSecureResultEnum;
}


/**
 * @export
 */
export const IssuingAuthorizationThreeDSecureResultEnum = {
    AttemptAcknowledged: 'attempt_acknowledged',
    Authenticated: 'authenticated',
    Failed: 'failed',
    Required: 'required'
} as const;
export type IssuingAuthorizationThreeDSecureResultEnum = typeof IssuingAuthorizationThreeDSecureResultEnum[keyof typeof IssuingAuthorizationThreeDSecureResultEnum];


/**
 * Check if a given object implements the IssuingAuthorizationThreeDSecure interface.
 */
export function instanceOfIssuingAuthorizationThreeDSecure(value: object): value is IssuingAuthorizationThreeDSecure {
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function IssuingAuthorizationThreeDSecureFromJSON(json: any): IssuingAuthorizationThreeDSecure {
    return IssuingAuthorizationThreeDSecureFromJSONTyped(json, false);
}

export function IssuingAuthorizationThreeDSecureFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuingAuthorizationThreeDSecure {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'],
    };
}

export function IssuingAuthorizationThreeDSecureToJSON(json: any): IssuingAuthorizationThreeDSecure {
    return IssuingAuthorizationThreeDSecureToJSONTyped(json, false);
}

export function IssuingAuthorizationThreeDSecureToJSONTyped(value?: IssuingAuthorizationThreeDSecure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
    };
}

