// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/IssuingTransactionAmountDetails.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface IssuingTransactionAmountDetails
 */
export interface IssuingTransactionAmountDetails {
    /**
     * N/A
     * @type {number}
     * @memberof IssuingTransactionAmountDetails
     */
    atmFee?: number;
    /**
     * N/A
     * @type {number}
     * @memberof IssuingTransactionAmountDetails
     */
    cashbackAmount?: number;
}

/**
 * Check if a given object implements the IssuingTransactionAmountDetails interface.
 */
export function instanceOfIssuingTransactionAmountDetails(value: object): value is IssuingTransactionAmountDetails {
    return true;
}

export function IssuingTransactionAmountDetailsFromJSON(json: any): IssuingTransactionAmountDetails {
    return IssuingTransactionAmountDetailsFromJSONTyped(json, false);
}

export function IssuingTransactionAmountDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuingTransactionAmountDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'atmFee': json['atm_fee'] == null ? undefined : json['atm_fee'],
        'cashbackAmount': json['cashback_amount'] == null ? undefined : json['cashback_amount'],
    };
}

export function IssuingTransactionAmountDetailsToJSON(json: any): IssuingTransactionAmountDetails {
    return IssuingTransactionAmountDetailsToJSONTyped(json, false);
}

export function IssuingTransactionAmountDetailsToJSONTyped(value?: IssuingTransactionAmountDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'atm_fee': value['atmFee'],
        'cashback_amount': value['cashbackAmount'],
    };
}

