// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/LegalEntityCompanyVerificationDocumentBack.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileResourceFileLinkList } from './FileResourceFileLinkList';
import {
    FileResourceFileLinkListFromJSON,
    FileResourceFileLinkListFromJSONTyped,
    FileResourceFileLinkListToJSON,
    FileResourceFileLinkListToJSONTyped,
} from './FileResourceFileLinkList';
import type { ModelFile } from './ModelFile';
import {
    ModelFileFromJSON,
    ModelFileFromJSONTyped,
    ModelFileToJSON,
    ModelFileToJSONTyped,
} from './ModelFile';

/**
 * N/A
 * @export
 * @interface LegalEntityCompanyVerificationDocumentBack
 */
export interface LegalEntityCompanyVerificationDocumentBack {
    /**
     * N/A
     * @type {number}
     * @memberof LegalEntityCompanyVerificationDocumentBack
     */
    created: number;
    /**
     * N/A
     * @type {number}
     * @memberof LegalEntityCompanyVerificationDocumentBack
     */
    expiresAt?: number;
    /**
     * N/A
     * @type {string}
     * @memberof LegalEntityCompanyVerificationDocumentBack
     */
    filename?: string;
    /**
     * N/A
     * @type {string}
     * @memberof LegalEntityCompanyVerificationDocumentBack
     */
    id: string;
    /**
     * 
     * @type {FileResourceFileLinkList}
     * @memberof LegalEntityCompanyVerificationDocumentBack
     */
    links?: FileResourceFileLinkList;
    /**
     * N/A
     * @type {LegalEntityCompanyVerificationDocumentBackObjectEnum}
     * @memberof LegalEntityCompanyVerificationDocumentBack
     */
    object: LegalEntityCompanyVerificationDocumentBackObjectEnum;
    /**
     * N/A
     * @type {LegalEntityCompanyVerificationDocumentBackPurposeEnum}
     * @memberof LegalEntityCompanyVerificationDocumentBack
     */
    purpose: LegalEntityCompanyVerificationDocumentBackPurposeEnum;
    /**
     * N/A
     * @type {number}
     * @memberof LegalEntityCompanyVerificationDocumentBack
     */
    size: number;
    /**
     * N/A
     * @type {string}
     * @memberof LegalEntityCompanyVerificationDocumentBack
     */
    title?: string;
    /**
     * N/A
     * @type {string}
     * @memberof LegalEntityCompanyVerificationDocumentBack
     */
    type?: string;
    /**
     * N/A
     * @type {string}
     * @memberof LegalEntityCompanyVerificationDocumentBack
     */
    url?: string;
}


/**
 * @export
 */
export const LegalEntityCompanyVerificationDocumentBackObjectEnum = {
    File: 'file'
} as const;
export type LegalEntityCompanyVerificationDocumentBackObjectEnum = typeof LegalEntityCompanyVerificationDocumentBackObjectEnum[keyof typeof LegalEntityCompanyVerificationDocumentBackObjectEnum];

/**
 * @export
 */
export const LegalEntityCompanyVerificationDocumentBackPurposeEnum = {
    AccountRequirement: 'account_requirement',
    AdditionalVerification: 'additional_verification',
    BusinessIcon: 'business_icon',
    BusinessLogo: 'business_logo',
    CustomerSignature: 'customer_signature',
    DisputeEvidence: 'dispute_evidence',
    DocumentProviderIdentityDocument: 'document_provider_identity_document',
    FinanceReportRun: 'finance_report_run',
    FinancialAccountStatement: 'financial_account_statement',
    IdentityDocument: 'identity_document',
    IdentityDocumentDownloadable: 'identity_document_downloadable',
    IssuingRegulatoryReporting: 'issuing_regulatory_reporting',
    PciDocument: 'pci_document',
    PlatformTermsOfService: 'platform_terms_of_service',
    Selfie: 'selfie',
    SigmaScheduledQuery: 'sigma_scheduled_query',
    TaxDocumentUserUpload: 'tax_document_user_upload',
    TerminalAndroidApk: 'terminal_android_apk',
    TerminalReaderSplashscreen: 'terminal_reader_splashscreen'
} as const;
export type LegalEntityCompanyVerificationDocumentBackPurposeEnum = typeof LegalEntityCompanyVerificationDocumentBackPurposeEnum[keyof typeof LegalEntityCompanyVerificationDocumentBackPurposeEnum];


/**
 * Check if a given object implements the LegalEntityCompanyVerificationDocumentBack interface.
 */
export function instanceOfLegalEntityCompanyVerificationDocumentBack(value: object): value is LegalEntityCompanyVerificationDocumentBack {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('purpose' in value) || value['purpose'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function LegalEntityCompanyVerificationDocumentBackFromJSON(json: any): LegalEntityCompanyVerificationDocumentBack {
    return LegalEntityCompanyVerificationDocumentBackFromJSONTyped(json, false);
}

export function LegalEntityCompanyVerificationDocumentBackFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalEntityCompanyVerificationDocumentBack {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'id': json['id'],
        'links': json['links'] == null ? undefined : FileResourceFileLinkListFromJSON(json['links']),
        'object': json['object'],
        'purpose': json['purpose'],
        'size': json['size'],
        'title': json['title'] == null ? undefined : json['title'],
        'type': json['type'] == null ? undefined : json['type'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function LegalEntityCompanyVerificationDocumentBackToJSON(json: any): LegalEntityCompanyVerificationDocumentBack {
    return LegalEntityCompanyVerificationDocumentBackToJSONTyped(json, false);
}

export function LegalEntityCompanyVerificationDocumentBackToJSONTyped(value?: LegalEntityCompanyVerificationDocumentBack | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'expires_at': value['expiresAt'],
        'filename': value['filename'],
        'id': value['id'],
        'links': FileResourceFileLinkListToJSON(value['links']),
        'object': value['object'],
        'purpose': value['purpose'],
        'size': value['size'],
        'title': value['title'],
        'type': value['type'],
        'url': value['url'],
    };
}

