// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet-1.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet
 */
export interface PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet {
    /**
     * N/A
     * @type {PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletTypeEnum}
     * @memberof PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet
     */
    type: PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletTypeEnum;
}


/**
 * @export
 */
export const PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletTypeEnum = {
    ApplePay: 'apple_pay',
    GooglePay: 'google_pay',
    SamsungPay: 'samsung_pay',
    Unknown: 'unknown'
} as const;
export type PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletTypeEnum = typeof PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletTypeEnum[keyof typeof PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletTypeEnum];


/**
 * Check if a given object implements the PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet interface.
 */
export function instanceOfPaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet(value: object): value is PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletFromJSON(json: any): PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet {
    return PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletFromJSONTyped(json, false);
}

export function PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletToJSON(json: any): PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet {
    return PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletToJSONTyped(json, false);
}

export function PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletToJSONTyped(value?: PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

