// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/ProcessorIdentityMatchPost200Response.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcessorIdentityMatchPost200ResponseAccount } from './ProcessorIdentityMatchPost200ResponseAccount';
import {
    ProcessorIdentityMatchPost200ResponseAccountFromJSON,
    ProcessorIdentityMatchPost200ResponseAccountFromJSONTyped,
    ProcessorIdentityMatchPost200ResponseAccountToJSON,
    ProcessorIdentityMatchPost200ResponseAccountToJSONTyped,
} from './ProcessorIdentityMatchPost200ResponseAccount';

/**
 * 
 * @export
 * @interface ProcessorIdentityMatchPost200Response
 */
export interface ProcessorIdentityMatchPost200Response {
    /**
     * 
     * @type {ProcessorIdentityMatchPost200ResponseAccount}
     * @memberof ProcessorIdentityMatchPost200Response
     */
    account?: ProcessorIdentityMatchPost200ResponseAccount;
    /**
     * 
     * @type {string}
     * @memberof ProcessorIdentityMatchPost200Response
     */
    requestId?: string;
}

/**
 * Check if a given object implements the ProcessorIdentityMatchPost200Response interface.
 */
export function instanceOfProcessorIdentityMatchPost200Response(value: object): value is ProcessorIdentityMatchPost200Response {
    return true;
}

export function ProcessorIdentityMatchPost200ResponseFromJSON(json: any): ProcessorIdentityMatchPost200Response {
    return ProcessorIdentityMatchPost200ResponseFromJSONTyped(json, false);
}

export function ProcessorIdentityMatchPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessorIdentityMatchPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : ProcessorIdentityMatchPost200ResponseAccountFromJSON(json['account']),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function ProcessorIdentityMatchPost200ResponseToJSON(json: any): ProcessorIdentityMatchPost200Response {
    return ProcessorIdentityMatchPost200ResponseToJSONTyped(json, false);
}

export function ProcessorIdentityMatchPost200ResponseToJSONTyped(value?: ProcessorIdentityMatchPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': ProcessorIdentityMatchPost200ResponseAccountToJSON(value['account']),
        'request_id': value['requestId'],
    };
}

