// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/ProcessorSignalReturnReportPostRequest.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessorSignalReturnReportPostRequest
 */
export interface ProcessorSignalReturnReportPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ProcessorSignalReturnReportPostRequest
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessorSignalReturnReportPostRequest
     */
    secret?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessorSignalReturnReportPostRequest
     */
    processorToken?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessorSignalReturnReportPostRequest
     */
    clientTransactionId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessorSignalReturnReportPostRequest
     */
    returnCode?: string;
}

/**
 * Check if a given object implements the ProcessorSignalReturnReportPostRequest interface.
 */
export function instanceOfProcessorSignalReturnReportPostRequest(value: object): value is ProcessorSignalReturnReportPostRequest {
    return true;
}

export function ProcessorSignalReturnReportPostRequestFromJSON(json: any): ProcessorSignalReturnReportPostRequest {
    return ProcessorSignalReturnReportPostRequestFromJSONTyped(json, false);
}

export function ProcessorSignalReturnReportPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessorSignalReturnReportPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'processorToken': json['processor_token'] == null ? undefined : json['processor_token'],
        'clientTransactionId': json['client_transaction_id'] == null ? undefined : json['client_transaction_id'],
        'returnCode': json['return_code'] == null ? undefined : json['return_code'],
    };
}

export function ProcessorSignalReturnReportPostRequestToJSON(json: any): ProcessorSignalReturnReportPostRequest {
    return ProcessorSignalReturnReportPostRequestToJSONTyped(json, false);
}

export function ProcessorSignalReturnReportPostRequestToJSONTyped(value?: ProcessorSignalReturnReportPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'secret': value['secret'],
        'processor_token': value['processorToken'],
        'client_transaction_id': value['clientTransactionId'],
        'return_code': value['returnCode'],
    };
}

