// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/SetupAttemptPaymentMethodDetailsCardPresent.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentMethodDetailsCardPresentOffline } from './PaymentMethodDetailsCardPresentOffline';
import {
    PaymentMethodDetailsCardPresentOfflineFromJSON,
    PaymentMethodDetailsCardPresentOfflineFromJSONTyped,
    PaymentMethodDetailsCardPresentOfflineToJSON,
    PaymentMethodDetailsCardPresentOfflineToJSONTyped,
} from './PaymentMethodDetailsCardPresentOffline';

/**
 * N/A
 * @export
 * @interface SetupAttemptPaymentMethodDetailsCardPresent
 */
export interface SetupAttemptPaymentMethodDetailsCardPresent {
    /**
     * 
     * @type {string}
     * @memberof SetupAttemptPaymentMethodDetailsCardPresent
     */
    generatedCard?: string | null;
    /**
     * 
     * @type {PaymentMethodDetailsCardPresentOffline}
     * @memberof SetupAttemptPaymentMethodDetailsCardPresent
     */
    offline?: PaymentMethodDetailsCardPresentOffline;
}

/**
 * Check if a given object implements the SetupAttemptPaymentMethodDetailsCardPresent interface.
 */
export function instanceOfSetupAttemptPaymentMethodDetailsCardPresent(value: object): value is SetupAttemptPaymentMethodDetailsCardPresent {
    return true;
}

export function SetupAttemptPaymentMethodDetailsCardPresentFromJSON(json: any): SetupAttemptPaymentMethodDetailsCardPresent {
    return SetupAttemptPaymentMethodDetailsCardPresentFromJSONTyped(json, false);
}

export function SetupAttemptPaymentMethodDetailsCardPresentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupAttemptPaymentMethodDetailsCardPresent {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedCard': json['generated_card'] == null ? undefined : json['generated_card'],
        'offline': json['offline'] == null ? undefined : PaymentMethodDetailsCardPresentOfflineFromJSON(json['offline']),
    };
}

export function SetupAttemptPaymentMethodDetailsCardPresentToJSON(json: any): SetupAttemptPaymentMethodDetailsCardPresent {
    return SetupAttemptPaymentMethodDetailsCardPresentToJSONTyped(json, false);
}

export function SetupAttemptPaymentMethodDetailsCardPresentToJSONTyped(value?: SetupAttemptPaymentMethodDetailsCardPresent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generated_card': value['generatedCard'],
        'offline': PaymentMethodDetailsCardPresentOfflineToJSON(value['offline']),
    };
}

