// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/SourceBancontact.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SourceBancontact
 */
export interface SourceBancontact {
    /**
     * 
     * @type {string}
     * @memberof SourceBancontact
     */
    bankCode?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceBancontact
     */
    bankName?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceBancontact
     */
    bic?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceBancontact
     */
    ibanLast4?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceBancontact
     */
    preferredLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceBancontact
     */
    statementDescriptor?: string;
}

/**
 * Check if a given object implements the SourceBancontact interface.
 */
export function instanceOfSourceBancontact(value: object): value is SourceBancontact {
    return true;
}

export function SourceBancontactFromJSON(json: any): SourceBancontact {
    return SourceBancontactFromJSONTyped(json, false);
}

export function SourceBancontactFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceBancontact {
    if (json == null) {
        return json;
    }
    return {
        
        'bankCode': json['bank_code'] == null ? undefined : json['bank_code'],
        'bankName': json['bank_name'] == null ? undefined : json['bank_name'],
        'bic': json['bic'] == null ? undefined : json['bic'],
        'ibanLast4': json['iban_last4'] == null ? undefined : json['iban_last4'],
        'preferredLanguage': json['preferred_language'] == null ? undefined : json['preferred_language'],
        'statementDescriptor': json['statement_descriptor'] == null ? undefined : json['statement_descriptor'],
    };
}

export function SourceBancontactToJSON(json: any): SourceBancontact {
    return SourceBancontactToJSONTyped(json, false);
}

export function SourceBancontactToJSONTyped(value?: SourceBancontact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bank_code': value['bankCode'],
        'bank_name': value['bankName'],
        'bic': value['bic'],
        'iban_last4': value['ibanLast4'],
        'preferred_language': value['preferredLanguage'],
        'statement_descriptor': value['statementDescriptor'],
    };
}

