// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/SubscriptionBillingThresholds.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface SubscriptionBillingThresholds
 */
export interface SubscriptionBillingThresholds {
    /**
     * N/A
     * @type {number}
     * @memberof SubscriptionBillingThresholds
     */
    amountGte?: number;
    /**
     * N/A
     * @type {boolean}
     * @memberof SubscriptionBillingThresholds
     */
    resetBillingCycleAnchor?: boolean;
}

/**
 * Check if a given object implements the SubscriptionBillingThresholds interface.
 */
export function instanceOfSubscriptionBillingThresholds(value: object): value is SubscriptionBillingThresholds {
    return true;
}

export function SubscriptionBillingThresholdsFromJSON(json: any): SubscriptionBillingThresholds {
    return SubscriptionBillingThresholdsFromJSONTyped(json, false);
}

export function SubscriptionBillingThresholdsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionBillingThresholds {
    if (json == null) {
        return json;
    }
    return {
        
        'amountGte': json['amount_gte'] == null ? undefined : json['amount_gte'],
        'resetBillingCycleAnchor': json['reset_billing_cycle_anchor'] == null ? undefined : json['reset_billing_cycle_anchor'],
    };
}

export function SubscriptionBillingThresholdsToJSON(json: any): SubscriptionBillingThresholds {
    return SubscriptionBillingThresholdsToJSONTyped(json, false);
}

export function SubscriptionBillingThresholdsToJSONTyped(value?: SubscriptionBillingThresholds | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_gte': value['amountGte'],
        'reset_billing_cycle_anchor': value['resetBillingCycleAnchor'],
    };
}

