// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/SubscriptionScheduleCurrentPhase.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface SubscriptionScheduleCurrentPhase
 */
export interface SubscriptionScheduleCurrentPhase {
    /**
     * N/A
     * @type {number}
     * @memberof SubscriptionScheduleCurrentPhase
     */
    endDate: number;
    /**
     * N/A
     * @type {number}
     * @memberof SubscriptionScheduleCurrentPhase
     */
    startDate: number;
}

/**
 * Check if a given object implements the SubscriptionScheduleCurrentPhase interface.
 */
export function instanceOfSubscriptionScheduleCurrentPhase(value: object): value is SubscriptionScheduleCurrentPhase {
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    return true;
}

export function SubscriptionScheduleCurrentPhaseFromJSON(json: any): SubscriptionScheduleCurrentPhase {
    return SubscriptionScheduleCurrentPhaseFromJSONTyped(json, false);
}

export function SubscriptionScheduleCurrentPhaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionScheduleCurrentPhase {
    if (json == null) {
        return json;
    }
    return {
        
        'endDate': json['end_date'],
        'startDate': json['start_date'],
    };
}

export function SubscriptionScheduleCurrentPhaseToJSON(json: any): SubscriptionScheduleCurrentPhase {
    return SubscriptionScheduleCurrentPhaseToJSONTyped(json, false);
}

export function SubscriptionScheduleCurrentPhaseToJSONTyped(value?: SubscriptionScheduleCurrentPhase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end_date': value['endDate'],
        'start_date': value['startDate'],
    };
}

