// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/ThresholdsResourceAlert.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ThresholdsResourceUsageThresholdConfig } from './ThresholdsResourceUsageThresholdConfig';
import {
    ThresholdsResourceUsageThresholdConfigFromJSON,
    ThresholdsResourceUsageThresholdConfigFromJSONTyped,
    ThresholdsResourceUsageThresholdConfigToJSON,
    ThresholdsResourceUsageThresholdConfigToJSONTyped,
} from './ThresholdsResourceUsageThresholdConfig';

/**
 * N/A
 * @export
 * @interface ThresholdsResourceAlert
 */
export interface ThresholdsResourceAlert {
    /**
     * N/A
     * @type {ThresholdsResourceAlertAlertTypeEnum}
     * @memberof ThresholdsResourceAlert
     */
    alertType: ThresholdsResourceAlertAlertTypeEnum;
    /**
     * N/A
     * @type {string}
     * @memberof ThresholdsResourceAlert
     */
    id: string;
    /**
     * N/A
     * @type {boolean}
     * @memberof ThresholdsResourceAlert
     */
    livemode: boolean;
    /**
     * N/A
     * @type {ThresholdsResourceAlertObjectEnum}
     * @memberof ThresholdsResourceAlert
     */
    object: ThresholdsResourceAlertObjectEnum;
    /**
     * N/A
     * @type {ThresholdsResourceAlertStatusEnum}
     * @memberof ThresholdsResourceAlert
     */
    status?: ThresholdsResourceAlertStatusEnum;
    /**
     * N/A
     * @type {string}
     * @memberof ThresholdsResourceAlert
     */
    title: string;
    /**
     * 
     * @type {ThresholdsResourceUsageThresholdConfig}
     * @memberof ThresholdsResourceAlert
     */
    usageThreshold?: ThresholdsResourceUsageThresholdConfig;
}


/**
 * @export
 */
export const ThresholdsResourceAlertAlertTypeEnum = {
    UsageThreshold: 'usage_threshold'
} as const;
export type ThresholdsResourceAlertAlertTypeEnum = typeof ThresholdsResourceAlertAlertTypeEnum[keyof typeof ThresholdsResourceAlertAlertTypeEnum];

/**
 * @export
 */
export const ThresholdsResourceAlertObjectEnum = {
    BillingAlert: 'billing.alert'
} as const;
export type ThresholdsResourceAlertObjectEnum = typeof ThresholdsResourceAlertObjectEnum[keyof typeof ThresholdsResourceAlertObjectEnum];

/**
 * @export
 */
export const ThresholdsResourceAlertStatusEnum = {
    Active: 'active',
    Archived: 'archived',
    Inactive: 'inactive'
} as const;
export type ThresholdsResourceAlertStatusEnum = typeof ThresholdsResourceAlertStatusEnum[keyof typeof ThresholdsResourceAlertStatusEnum];


/**
 * Check if a given object implements the ThresholdsResourceAlert interface.
 */
export function instanceOfThresholdsResourceAlert(value: object): value is ThresholdsResourceAlert {
    if (!('alertType' in value) || value['alertType'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('livemode' in value) || value['livemode'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ThresholdsResourceAlertFromJSON(json: any): ThresholdsResourceAlert {
    return ThresholdsResourceAlertFromJSONTyped(json, false);
}

export function ThresholdsResourceAlertFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThresholdsResourceAlert {
    if (json == null) {
        return json;
    }
    return {
        
        'alertType': json['alert_type'],
        'id': json['id'],
        'livemode': json['livemode'],
        'object': json['object'],
        'status': json['status'] == null ? undefined : json['status'],
        'title': json['title'],
        'usageThreshold': json['usage_threshold'] == null ? undefined : ThresholdsResourceUsageThresholdConfigFromJSON(json['usage_threshold']),
    };
}

export function ThresholdsResourceAlertToJSON(json: any): ThresholdsResourceAlert {
    return ThresholdsResourceAlertToJSONTyped(json, false);
}

export function ThresholdsResourceAlertToJSONTyped(value?: ThresholdsResourceAlert | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alert_type': value['alertType'],
        'id': value['id'],
        'livemode': value['livemode'],
        'object': value['object'],
        'status': value['status'],
        'title': value['title'],
        'usage_threshold': ThresholdsResourceUsageThresholdConfigToJSON(value['usageThreshold']),
    };
}

