// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/TransactionsRecurringGet200Response.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionsRecurringGet200ResponseDataInner } from './TransactionsRecurringGet200ResponseDataInner';
import {
    TransactionsRecurringGet200ResponseDataInnerFromJSON,
    TransactionsRecurringGet200ResponseDataInnerFromJSONTyped,
    TransactionsRecurringGet200ResponseDataInnerToJSON,
    TransactionsRecurringGet200ResponseDataInnerToJSONTyped,
} from './TransactionsRecurringGet200ResponseDataInner';

/**
 * 
 * @export
 * @interface TransactionsRecurringGet200Response
 */
export interface TransactionsRecurringGet200Response {
    /**
     * 
     * @type {number}
     * @memberof TransactionsRecurringGet200Response
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionsRecurringGet200Response
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionsRecurringGet200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionsRecurringGet200Response
     */
    nextOffset?: number;
    /**
     * 
     * @type {Array<TransactionsRecurringGet200ResponseDataInner>}
     * @memberof TransactionsRecurringGet200Response
     */
    data: Array<TransactionsRecurringGet200ResponseDataInner>;
}

/**
 * Check if a given object implements the TransactionsRecurringGet200Response interface.
 */
export function instanceOfTransactionsRecurringGet200Response(value: object): value is TransactionsRecurringGet200Response {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TransactionsRecurringGet200ResponseFromJSON(json: any): TransactionsRecurringGet200Response {
    return TransactionsRecurringGet200ResponseFromJSONTyped(json, false);
}

export function TransactionsRecurringGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsRecurringGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'],
        'nextOffset': json['nextOffset'] == null ? undefined : json['nextOffset'],
        'data': ((json['data'] as Array<any>).map(TransactionsRecurringGet200ResponseDataInnerFromJSON)),
    };
}

export function TransactionsRecurringGet200ResponseToJSON(json: any): TransactionsRecurringGet200Response {
    return TransactionsRecurringGet200ResponseToJSONTyped(json, false);
}

export function TransactionsRecurringGet200ResponseToJSONTyped(value?: TransactionsRecurringGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
        'nextOffset': value['nextOffset'],
        'data': ((value['data'] as Array<any>).map(TransactionsRecurringGet200ResponseDataInnerToJSON)),
    };
}

