// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehavior.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehavior
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehavior {
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehavior
     */
    missingPaymentMethod?: string;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehavior interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehavior(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehavior {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehaviorFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehavior {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehaviorFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehaviorFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehavior {
    if (json == null) {
        return json;
    }
    return {
        
        'missingPaymentMethod': json['missing_payment_method'] == null ? undefined : json['missing_payment_method'],
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehaviorToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehavior {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehaviorToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehaviorToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerTrialSettingsEndBehavior | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'missing_payment_method': value['missingPaymentMethod'],
    };
}

