// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitGeneratedFrom } from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitGeneratedFrom';
import {
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitGeneratedFromFromJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitGeneratedFromFromJSONTyped,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitGeneratedFromToJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitGeneratedFromToJSONTyped,
} from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitGeneratedFrom';

/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit {
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit
     */
    bankCode?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit
     */
    branchCode?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit
     */
    fingerprint?: string;
    /**
     * 
     * @type {V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitGeneratedFrom}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit
     */
    generatedFrom?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitGeneratedFrom;
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit
     */
    last4?: string;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit {
    if (json == null) {
        return json;
    }
    return {
        
        'bankCode': json['bank_code'] == null ? undefined : json['bank_code'],
        'branchCode': json['branch_code'] == null ? undefined : json['branch_code'],
        'country': json['country'] == null ? undefined : json['country'],
        'fingerprint': json['fingerprint'] == null ? undefined : json['fingerprint'],
        'generatedFrom': json['generated_from'] == null ? undefined : V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitGeneratedFromFromJSON(json['generated_from']),
        'last4': json['last4'] == null ? undefined : json['last4'],
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bank_code': value['bankCode'],
        'branch_code': value['branchCode'],
        'country': value['country'],
        'fingerprint': value['fingerprint'],
        'generated_from': V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewSepaDebitGeneratedFromToJSON(value['generatedFrom']),
        'last4': value['last4'],
    };
}

