// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1IdentityVerificationReportsGet200ResponseDataInnerDocument.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDob } from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDob';
import {
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDobFromJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDobFromJSONTyped,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDobToJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDobToJSONTyped,
} from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDob';
import type { V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddress } from './V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddress';
import {
    V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressFromJSON,
    V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressFromJSONTyped,
    V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressToJSON,
    V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressToJSONTyped,
} from './V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddress';
import type { V1IdentityVerificationReportsGet200ResponseDataInnerDocumentError } from './V1IdentityVerificationReportsGet200ResponseDataInnerDocumentError';
import {
    V1IdentityVerificationReportsGet200ResponseDataInnerDocumentErrorFromJSON,
    V1IdentityVerificationReportsGet200ResponseDataInnerDocumentErrorFromJSONTyped,
    V1IdentityVerificationReportsGet200ResponseDataInnerDocumentErrorToJSON,
    V1IdentityVerificationReportsGet200ResponseDataInnerDocumentErrorToJSONTyped,
} from './V1IdentityVerificationReportsGet200ResponseDataInnerDocumentError';

/**
 * 
 * @export
 * @interface V1IdentityVerificationReportsGet200ResponseDataInnerDocument
 */
export interface V1IdentityVerificationReportsGet200ResponseDataInnerDocument {
    /**
     * 
     * @type {string}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    status?: string;
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddress}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    address?: V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddress;
    /**
     * 
     * @type {V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDob}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    dob?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDob;
    /**
     * 
     * @type {V1IdentityVerificationReportsGet200ResponseDataInnerDocumentError}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    error?: V1IdentityVerificationReportsGet200ResponseDataInnerDocumentError;
    /**
     * 
     * @type {V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDob}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    expirationDate?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDob;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    files?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    firstName?: string;
    /**
     * 
     * @type {V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDob}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    issuedDate?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDob;
    /**
     * 
     * @type {string}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    issuingCountry?: string;
    /**
     * 
     * @type {string}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    number?: string;
    /**
     * 
     * @type {string}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    sex?: string;
    /**
     * 
     * @type {string}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    unparsedPlaceOfBirth?: string;
    /**
     * 
     * @type {string}
     * @memberof V1IdentityVerificationReportsGet200ResponseDataInnerDocument
     */
    unparsedSex?: string;
}

/**
 * Check if a given object implements the V1IdentityVerificationReportsGet200ResponseDataInnerDocument interface.
 */
export function instanceOfV1IdentityVerificationReportsGet200ResponseDataInnerDocument(value: object): value is V1IdentityVerificationReportsGet200ResponseDataInnerDocument {
    return true;
}

export function V1IdentityVerificationReportsGet200ResponseDataInnerDocumentFromJSON(json: any): V1IdentityVerificationReportsGet200ResponseDataInnerDocument {
    return V1IdentityVerificationReportsGet200ResponseDataInnerDocumentFromJSONTyped(json, false);
}

export function V1IdentityVerificationReportsGet200ResponseDataInnerDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1IdentityVerificationReportsGet200ResponseDataInnerDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'address': json['address'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressFromJSON(json['address']),
        'dob': json['dob'] == null ? undefined : V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDobFromJSON(json['dob']),
        'error': json['error'] == null ? undefined : V1IdentityVerificationReportsGet200ResponseDataInnerDocumentErrorFromJSON(json['error']),
        'expirationDate': json['expiration_date'] == null ? undefined : V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDobFromJSON(json['expiration_date']),
        'files': json['files'] == null ? undefined : json['files'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'issuedDate': json['issued_date'] == null ? undefined : V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDobFromJSON(json['issued_date']),
        'issuingCountry': json['issuing_country'] == null ? undefined : json['issuing_country'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'number': json['number'] == null ? undefined : json['number'],
        'sex': json['sex'] == null ? undefined : json['sex'],
        'type': json['type'] == null ? undefined : json['type'],
        'unparsedPlaceOfBirth': json['unparsed_place_of_birth'] == null ? undefined : json['unparsed_place_of_birth'],
        'unparsedSex': json['unparsed_sex'] == null ? undefined : json['unparsed_sex'],
    };
}

export function V1IdentityVerificationReportsGet200ResponseDataInnerDocumentToJSON(json: any): V1IdentityVerificationReportsGet200ResponseDataInnerDocument {
    return V1IdentityVerificationReportsGet200ResponseDataInnerDocumentToJSONTyped(json, false);
}

export function V1IdentityVerificationReportsGet200ResponseDataInnerDocumentToJSONTyped(value?: V1IdentityVerificationReportsGet200ResponseDataInnerDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'address': V1CheckoutSessionsGet200ResponseDataInnerCollectedInformationShippingDetailsAddressToJSON(value['address']),
        'dob': V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDobToJSON(value['dob']),
        'error': V1IdentityVerificationReportsGet200ResponseDataInnerDocumentErrorToJSON(value['error']),
        'expiration_date': V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDobToJSON(value['expirationDate']),
        'files': value['files'],
        'first_name': value['firstName'],
        'issued_date': V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewKlarnaDobToJSON(value['issuedDate']),
        'issuing_country': value['issuingCountry'],
        'last_name': value['lastName'],
        'number': value['number'],
        'sex': value['sex'],
        'type': value['type'],
        'unparsed_place_of_birth': value['unparsedPlaceOfBirth'],
        'unparsed_sex': value['unparsedSex'],
    };
}

