// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1IssuingPhysicalBundlesGet200ResponseDataInner.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1IssuingPhysicalBundlesGet200ResponseDataInnerFeatures } from './V1IssuingPhysicalBundlesGet200ResponseDataInnerFeatures';
import {
    V1IssuingPhysicalBundlesGet200ResponseDataInnerFeaturesFromJSON,
    V1IssuingPhysicalBundlesGet200ResponseDataInnerFeaturesFromJSONTyped,
    V1IssuingPhysicalBundlesGet200ResponseDataInnerFeaturesToJSON,
    V1IssuingPhysicalBundlesGet200ResponseDataInnerFeaturesToJSONTyped,
} from './V1IssuingPhysicalBundlesGet200ResponseDataInnerFeatures';

/**
 * 
 * @export
 * @interface V1IssuingPhysicalBundlesGet200ResponseDataInner
 */
export interface V1IssuingPhysicalBundlesGet200ResponseDataInner {
    /**
     * 
     * @type {V1IssuingPhysicalBundlesGet200ResponseDataInnerFeatures}
     * @memberof V1IssuingPhysicalBundlesGet200ResponseDataInner
     */
    features?: V1IssuingPhysicalBundlesGet200ResponseDataInnerFeatures;
    /**
     * 
     * @type {string}
     * @memberof V1IssuingPhysicalBundlesGet200ResponseDataInner
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1IssuingPhysicalBundlesGet200ResponseDataInner
     */
    livemode?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1IssuingPhysicalBundlesGet200ResponseDataInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1IssuingPhysicalBundlesGet200ResponseDataInner
     */
    object?: string;
    /**
     * 
     * @type {string}
     * @memberof V1IssuingPhysicalBundlesGet200ResponseDataInner
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof V1IssuingPhysicalBundlesGet200ResponseDataInner
     */
    type?: string;
}

/**
 * Check if a given object implements the V1IssuingPhysicalBundlesGet200ResponseDataInner interface.
 */
export function instanceOfV1IssuingPhysicalBundlesGet200ResponseDataInner(value: object): value is V1IssuingPhysicalBundlesGet200ResponseDataInner {
    return true;
}

export function V1IssuingPhysicalBundlesGet200ResponseDataInnerFromJSON(json: any): V1IssuingPhysicalBundlesGet200ResponseDataInner {
    return V1IssuingPhysicalBundlesGet200ResponseDataInnerFromJSONTyped(json, false);
}

export function V1IssuingPhysicalBundlesGet200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1IssuingPhysicalBundlesGet200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'features': json['features'] == null ? undefined : V1IssuingPhysicalBundlesGet200ResponseDataInnerFeaturesFromJSON(json['features']),
        'id': json['id'] == null ? undefined : json['id'],
        'livemode': json['livemode'] == null ? undefined : json['livemode'],
        'name': json['name'] == null ? undefined : json['name'],
        'object': json['object'] == null ? undefined : json['object'],
        'status': json['status'] == null ? undefined : json['status'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function V1IssuingPhysicalBundlesGet200ResponseDataInnerToJSON(json: any): V1IssuingPhysicalBundlesGet200ResponseDataInner {
    return V1IssuingPhysicalBundlesGet200ResponseDataInnerToJSONTyped(json, false);
}

export function V1IssuingPhysicalBundlesGet200ResponseDataInnerToJSONTyped(value?: V1IssuingPhysicalBundlesGet200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'features': V1IssuingPhysicalBundlesGet200ResponseDataInnerFeaturesToJSON(value['features']),
        'id': value['id'],
        'livemode': value['livemode'],
        'name': value['name'],
        'object': value['object'],
        'status': value['status'],
        'type': value['type'],
    };
}

