// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTax.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTax
 */
export interface V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTax {
    /**
     * 
     * @type {number}
     * @memberof V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTax
     */
    totalTaxAmount?: number;
}

/**
 * Check if a given object implements the V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTax interface.
 */
export function instanceOfV1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTax(value: object): value is V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTax {
    return true;
}

export function V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTaxFromJSON(json: any): V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTax {
    return V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTaxFromJSONTyped(json, false);
}

export function V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTaxFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTax {
    if (json == null) {
        return json;
    }
    return {
        
        'totalTaxAmount': json['total_tax_amount'] == null ? undefined : json['total_tax_amount'],
    };
}

export function V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTaxToJSON(json: any): V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTax {
    return V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTaxToJSONTyped(json, false);
}

export function V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTaxToJSONTyped(value?: V1PaymentIntentsIntentAmountDetailsLineItemsGet200ResponseDataInnerTax | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_tax_amount': value['totalTaxAmount'],
    };
}

