// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAe.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeStandard } from './V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeStandard';
import {
    V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeStandardFromJSON,
    V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeStandardFromJSONTyped,
    V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeStandardToJSON,
    V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeStandardToJSONTyped,
} from './V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeStandard';

/**
 * 
 * @export
 * @interface V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAe
 */
export interface V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAe {
    /**
     * 
     * @type {string}
     * @memberof V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAe
     */
    type?: string;
    /**
     * 
     * @type {V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeStandard}
     * @memberof V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAe
     */
    standard?: V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeStandard;
}

/**
 * Check if a given object implements the V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAe interface.
 */
export function instanceOfV1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAe(value: object): value is V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAe {
    return true;
}

export function V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeFromJSON(json: any): V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAe {
    return V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeFromJSONTyped(json, false);
}

export function V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAe {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'standard': json['standard'] == null ? undefined : V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeStandardFromJSON(json['standard']),
    };
}

export function V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeToJSON(json: any): V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAe {
    return V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeToJSONTyped(json, false);
}

export function V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeToJSONTyped(value?: V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAe | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'standard': V1TaxRegistrationsGet200ResponseDataInnerCountryOptionsAeStandardToJSON(value['standard']),
    };
}

