// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails } from './V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails';
import {
    V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetailsFromJSON,
    V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetailsFromJSONTyped,
    V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetailsToJSON,
    V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetailsToJSONTyped,
} from './V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails';

/**
 * 
 * @export
 * @interface V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows
 */
export interface V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows {
    /**
     * 
     * @type {string}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows
     */
    creditReversal?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows
     */
    issuingAuthorization?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows
     */
    issuingTransaction?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows
     */
    sourceFlow?: string;
    /**
     * 
     * @type {V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows
     */
    sourceFlowDetails?: V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails;
    /**
     * 
     * @type {string}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows
     */
    sourceFlowType?: string;
}

/**
 * Check if a given object implements the V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows interface.
 */
export function instanceOfV1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows(value: object): value is V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows {
    return true;
}

export function V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsFromJSON(json: any): V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows {
    return V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsFromJSONTyped(json, false);
}

export function V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows {
    if (json == null) {
        return json;
    }
    return {
        
        'creditReversal': json['credit_reversal'] == null ? undefined : json['credit_reversal'],
        'issuingAuthorization': json['issuing_authorization'] == null ? undefined : json['issuing_authorization'],
        'issuingTransaction': json['issuing_transaction'] == null ? undefined : json['issuing_transaction'],
        'sourceFlow': json['source_flow'] == null ? undefined : json['source_flow'],
        'sourceFlowDetails': json['source_flow_details'] == null ? undefined : V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetailsFromJSON(json['source_flow_details']),
        'sourceFlowType': json['source_flow_type'] == null ? undefined : json['source_flow_type'],
    };
}

export function V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsToJSON(json: any): V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows {
    return V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsToJSONTyped(json, false);
}

export function V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsToJSONTyped(value?: V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlows | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credit_reversal': value['creditReversal'],
        'issuing_authorization': value['issuingAuthorization'],
        'issuing_transaction': value['issuingTransaction'],
        'source_flow': value['sourceFlow'],
        'source_flow_details': V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetailsToJSON(value['sourceFlowDetails']),
        'source_flow_type': value['sourceFlowType'],
    };
}

