// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1TreasuryTransactionsIdGet200ResponseFlowDetails.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1TestHelpersTreasuryReceivedDebitsPost200Response } from './V1TestHelpersTreasuryReceivedDebitsPost200Response';
import {
    V1TestHelpersTreasuryReceivedDebitsPost200ResponseFromJSON,
    V1TestHelpersTreasuryReceivedDebitsPost200ResponseFromJSONTyped,
    V1TestHelpersTreasuryReceivedDebitsPost200ResponseToJSON,
    V1TestHelpersTreasuryReceivedDebitsPost200ResponseToJSONTyped,
} from './V1TestHelpersTreasuryReceivedDebitsPost200Response';
import type { V1ChargesChargeGet200Response } from './V1ChargesChargeGet200Response';
import {
    V1ChargesChargeGet200ResponseFromJSON,
    V1ChargesChargeGet200ResponseFromJSONTyped,
    V1ChargesChargeGet200ResponseToJSON,
    V1ChargesChargeGet200ResponseToJSONTyped,
} from './V1ChargesChargeGet200Response';
import type { V1TreasuryTransactionsIdGet200ResponseFlowDetailsIssuingAuthorization } from './V1TreasuryTransactionsIdGet200ResponseFlowDetailsIssuingAuthorization';
import {
    V1TreasuryTransactionsIdGet200ResponseFlowDetailsIssuingAuthorizationFromJSON,
    V1TreasuryTransactionsIdGet200ResponseFlowDetailsIssuingAuthorizationFromJSONTyped,
    V1TreasuryTransactionsIdGet200ResponseFlowDetailsIssuingAuthorizationToJSON,
    V1TreasuryTransactionsIdGet200ResponseFlowDetailsIssuingAuthorizationToJSONTyped,
} from './V1TreasuryTransactionsIdGet200ResponseFlowDetailsIssuingAuthorization';
import type { V1TreasuryCreditReversalsPost200Response } from './V1TreasuryCreditReversalsPost200Response';
import {
    V1TreasuryCreditReversalsPost200ResponseFromJSON,
    V1TreasuryCreditReversalsPost200ResponseFromJSONTyped,
    V1TreasuryCreditReversalsPost200ResponseToJSON,
    V1TreasuryCreditReversalsPost200ResponseToJSONTyped,
} from './V1TreasuryCreditReversalsPost200Response';
import type { V1TreasuryOutboundTransfersPost200Response } from './V1TreasuryOutboundTransfersPost200Response';
import {
    V1TreasuryOutboundTransfersPost200ResponseFromJSON,
    V1TreasuryOutboundTransfersPost200ResponseFromJSONTyped,
    V1TreasuryOutboundTransfersPost200ResponseToJSON,
    V1TreasuryOutboundTransfersPost200ResponseToJSONTyped,
} from './V1TreasuryOutboundTransfersPost200Response';
import type { V1TreasuryTransactionsIdGet200ResponseFlowDetailsReceivedCredit } from './V1TreasuryTransactionsIdGet200ResponseFlowDetailsReceivedCredit';
import {
    V1TreasuryTransactionsIdGet200ResponseFlowDetailsReceivedCreditFromJSON,
    V1TreasuryTransactionsIdGet200ResponseFlowDetailsReceivedCreditFromJSONTyped,
    V1TreasuryTransactionsIdGet200ResponseFlowDetailsReceivedCreditToJSON,
    V1TreasuryTransactionsIdGet200ResponseFlowDetailsReceivedCreditToJSONTyped,
} from './V1TreasuryTransactionsIdGet200ResponseFlowDetailsReceivedCredit';
import type { V1TreasuryTransactionsIdGet200ResponseFlowDetailsDebitReversal } from './V1TreasuryTransactionsIdGet200ResponseFlowDetailsDebitReversal';
import {
    V1TreasuryTransactionsIdGet200ResponseFlowDetailsDebitReversalFromJSON,
    V1TreasuryTransactionsIdGet200ResponseFlowDetailsDebitReversalFromJSONTyped,
    V1TreasuryTransactionsIdGet200ResponseFlowDetailsDebitReversalToJSON,
    V1TreasuryTransactionsIdGet200ResponseFlowDetailsDebitReversalToJSONTyped,
} from './V1TreasuryTransactionsIdGet200ResponseFlowDetailsDebitReversal';
import type { V1TreasuryOutboundPaymentsPost200Response } from './V1TreasuryOutboundPaymentsPost200Response';
import {
    V1TreasuryOutboundPaymentsPost200ResponseFromJSON,
    V1TreasuryOutboundPaymentsPost200ResponseFromJSONTyped,
    V1TreasuryOutboundPaymentsPost200ResponseToJSON,
    V1TreasuryOutboundPaymentsPost200ResponseToJSONTyped,
} from './V1TreasuryOutboundPaymentsPost200Response';

/**
 * 
 * @export
 * @interface V1TreasuryTransactionsIdGet200ResponseFlowDetails
 */
export interface V1TreasuryTransactionsIdGet200ResponseFlowDetails {
    /**
     * 
     * @type {string}
     * @memberof V1TreasuryTransactionsIdGet200ResponseFlowDetails
     */
    type?: string;
    /**
     * 
     * @type {V1TreasuryCreditReversalsPost200Response}
     * @memberof V1TreasuryTransactionsIdGet200ResponseFlowDetails
     */
    creditReversal?: V1TreasuryCreditReversalsPost200Response;
    /**
     * 
     * @type {V1TreasuryTransactionsIdGet200ResponseFlowDetailsDebitReversal}
     * @memberof V1TreasuryTransactionsIdGet200ResponseFlowDetails
     */
    debitReversal?: V1TreasuryTransactionsIdGet200ResponseFlowDetailsDebitReversal;
    /**
     * 
     * @type {V1ChargesChargeGet200Response}
     * @memberof V1TreasuryTransactionsIdGet200ResponseFlowDetails
     */
    inboundTransfer?: V1ChargesChargeGet200Response;
    /**
     * 
     * @type {V1TreasuryTransactionsIdGet200ResponseFlowDetailsIssuingAuthorization}
     * @memberof V1TreasuryTransactionsIdGet200ResponseFlowDetails
     */
    issuingAuthorization?: V1TreasuryTransactionsIdGet200ResponseFlowDetailsIssuingAuthorization;
    /**
     * 
     * @type {V1TreasuryOutboundPaymentsPost200Response}
     * @memberof V1TreasuryTransactionsIdGet200ResponseFlowDetails
     */
    outboundPayment?: V1TreasuryOutboundPaymentsPost200Response;
    /**
     * 
     * @type {V1TreasuryOutboundTransfersPost200Response}
     * @memberof V1TreasuryTransactionsIdGet200ResponseFlowDetails
     */
    outboundTransfer?: V1TreasuryOutboundTransfersPost200Response;
    /**
     * 
     * @type {V1TreasuryTransactionsIdGet200ResponseFlowDetailsReceivedCredit}
     * @memberof V1TreasuryTransactionsIdGet200ResponseFlowDetails
     */
    receivedCredit?: V1TreasuryTransactionsIdGet200ResponseFlowDetailsReceivedCredit;
    /**
     * 
     * @type {V1TestHelpersTreasuryReceivedDebitsPost200Response}
     * @memberof V1TreasuryTransactionsIdGet200ResponseFlowDetails
     */
    receivedDebit?: V1TestHelpersTreasuryReceivedDebitsPost200Response;
}

/**
 * Check if a given object implements the V1TreasuryTransactionsIdGet200ResponseFlowDetails interface.
 */
export function instanceOfV1TreasuryTransactionsIdGet200ResponseFlowDetails(value: object): value is V1TreasuryTransactionsIdGet200ResponseFlowDetails {
    return true;
}

export function V1TreasuryTransactionsIdGet200ResponseFlowDetailsFromJSON(json: any): V1TreasuryTransactionsIdGet200ResponseFlowDetails {
    return V1TreasuryTransactionsIdGet200ResponseFlowDetailsFromJSONTyped(json, false);
}

export function V1TreasuryTransactionsIdGet200ResponseFlowDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TreasuryTransactionsIdGet200ResponseFlowDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'creditReversal': json['credit_reversal'] == null ? undefined : V1TreasuryCreditReversalsPost200ResponseFromJSON(json['credit_reversal']),
        'debitReversal': json['debit_reversal'] == null ? undefined : V1TreasuryTransactionsIdGet200ResponseFlowDetailsDebitReversalFromJSON(json['debit_reversal']),
        'inboundTransfer': json['inbound_transfer'] == null ? undefined : V1ChargesChargeGet200ResponseFromJSON(json['inbound_transfer']),
        'issuingAuthorization': json['issuing_authorization'] == null ? undefined : V1TreasuryTransactionsIdGet200ResponseFlowDetailsIssuingAuthorizationFromJSON(json['issuing_authorization']),
        'outboundPayment': json['outbound_payment'] == null ? undefined : V1TreasuryOutboundPaymentsPost200ResponseFromJSON(json['outbound_payment']),
        'outboundTransfer': json['outbound_transfer'] == null ? undefined : V1TreasuryOutboundTransfersPost200ResponseFromJSON(json['outbound_transfer']),
        'receivedCredit': json['received_credit'] == null ? undefined : V1TreasuryTransactionsIdGet200ResponseFlowDetailsReceivedCreditFromJSON(json['received_credit']),
        'receivedDebit': json['received_debit'] == null ? undefined : V1TestHelpersTreasuryReceivedDebitsPost200ResponseFromJSON(json['received_debit']),
    };
}

export function V1TreasuryTransactionsIdGet200ResponseFlowDetailsToJSON(json: any): V1TreasuryTransactionsIdGet200ResponseFlowDetails {
    return V1TreasuryTransactionsIdGet200ResponseFlowDetailsToJSONTyped(json, false);
}

export function V1TreasuryTransactionsIdGet200ResponseFlowDetailsToJSONTyped(value?: V1TreasuryTransactionsIdGet200ResponseFlowDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'credit_reversal': V1TreasuryCreditReversalsPost200ResponseToJSON(value['creditReversal']),
        'debit_reversal': V1TreasuryTransactionsIdGet200ResponseFlowDetailsDebitReversalToJSON(value['debitReversal']),
        'inbound_transfer': V1ChargesChargeGet200ResponseToJSON(value['inboundTransfer']),
        'issuing_authorization': V1TreasuryTransactionsIdGet200ResponseFlowDetailsIssuingAuthorizationToJSON(value['issuingAuthorization']),
        'outbound_payment': V1TreasuryOutboundPaymentsPost200ResponseToJSON(value['outboundPayment']),
        'outbound_transfer': V1TreasuryOutboundTransfersPost200ResponseToJSON(value['outboundTransfer']),
        'received_credit': V1TreasuryTransactionsIdGet200ResponseFlowDetailsReceivedCreditToJSON(value['receivedCredit']),
        'received_debit': V1TestHelpersTreasuryReceivedDebitsPost200ResponseToJSON(value['receivedDebit']),
    };
}

