// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/WatchlistScreeningEntityProgramListPostDefaultResponse.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WatchlistScreeningIndividualProgramListPostDefaultResponseIndividualWatchlistProgramsInner } from './WatchlistScreeningIndividualProgramListPostDefaultResponseIndividualWatchlistProgramsInner';
import {
    WatchlistScreeningIndividualProgramListPostDefaultResponseIndividualWatchlistProgramsInnerFromJSON,
    WatchlistScreeningIndividualProgramListPostDefaultResponseIndividualWatchlistProgramsInnerFromJSONTyped,
    WatchlistScreeningIndividualProgramListPostDefaultResponseIndividualWatchlistProgramsInnerToJSON,
    WatchlistScreeningIndividualProgramListPostDefaultResponseIndividualWatchlistProgramsInnerToJSONTyped,
} from './WatchlistScreeningIndividualProgramListPostDefaultResponseIndividualWatchlistProgramsInner';

/**
 * 
 * @export
 * @interface WatchlistScreeningEntityProgramListPostDefaultResponse
 */
export interface WatchlistScreeningEntityProgramListPostDefaultResponse {
    /**
     * 
     * @type {Array<WatchlistScreeningIndividualProgramListPostDefaultResponseIndividualWatchlistProgramsInner>}
     * @memberof WatchlistScreeningEntityProgramListPostDefaultResponse
     */
    entityWatchlistPrograms?: Array<WatchlistScreeningIndividualProgramListPostDefaultResponseIndividualWatchlistProgramsInner>;
    /**
     * 
     * @type {string}
     * @memberof WatchlistScreeningEntityProgramListPostDefaultResponse
     */
    requestId?: string;
}

/**
 * Check if a given object implements the WatchlistScreeningEntityProgramListPostDefaultResponse interface.
 */
export function instanceOfWatchlistScreeningEntityProgramListPostDefaultResponse(value: object): value is WatchlistScreeningEntityProgramListPostDefaultResponse {
    return true;
}

export function WatchlistScreeningEntityProgramListPostDefaultResponseFromJSON(json: any): WatchlistScreeningEntityProgramListPostDefaultResponse {
    return WatchlistScreeningEntityProgramListPostDefaultResponseFromJSONTyped(json, false);
}

export function WatchlistScreeningEntityProgramListPostDefaultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchlistScreeningEntityProgramListPostDefaultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entityWatchlistPrograms': json['entity_watchlist_programs'] == null ? undefined : ((json['entity_watchlist_programs'] as Array<any>).map(WatchlistScreeningIndividualProgramListPostDefaultResponseIndividualWatchlistProgramsInnerFromJSON)),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function WatchlistScreeningEntityProgramListPostDefaultResponseToJSON(json: any): WatchlistScreeningEntityProgramListPostDefaultResponse {
    return WatchlistScreeningEntityProgramListPostDefaultResponseToJSONTyped(json, false);
}

export function WatchlistScreeningEntityProgramListPostDefaultResponseToJSONTyped(value?: WatchlistScreeningEntityProgramListPostDefaultResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity_watchlist_programs': value['entityWatchlistPrograms'] == null ? undefined : ((value['entityWatchlistPrograms'] as Array<any>).map(WatchlistScreeningIndividualProgramListPostDefaultResponseIndividualWatchlistProgramsInnerToJSON)),
        'request_id': value['requestId'],
    };
}

