// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
 */
export interface AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner {
    /**
     * N/A
     * @type {string}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    productName: string;
    /**
     * N/A
     * @type {AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInnerBalanceTypeEnum}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    balanceType: AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInnerBalanceTypeEnum;
    /**
     * N/A
     * @type {string}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    displayAccountNumber: string;
    /**
     * N/A
     * @type {string}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    accountDescription?: string;
    /**
     * N/A
     * @type {string}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    accountNickname?: string;
    /**
     * N/A
     * @type {string}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    accountId: string;
    /**
     * N/A
     * @type {string}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    currencyCode: string;
    /**
     * N/A
     * @type {number}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    currentBalanceAmount?: number;
    /**
     * N/A
     * @type {number}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    creditAvailableAmount?: number;
    /**
     * N/A
     * @type {number}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    paymentDueAmount?: number;
    /**
     * N/A
     * @type {Date}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    paymentDueDate?: Date;
    /**
     * N/A
     * @type {boolean}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    autoPayFlag?: boolean;
    /**
     * N/A
     * @type {number}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    lastPaymentAmount?: number;
    /**
     * N/A
     * @type {Date}
     * @memberof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner
     */
    lastPaymentDate?: Date;
}


/**
 * @export
 */
export const AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInnerBalanceTypeEnum = {
    Asset: 'ASSET',
    Liability: 'LIABILITY'
} as const;
export type AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInnerBalanceTypeEnum = typeof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInnerBalanceTypeEnum[keyof typeof AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInnerBalanceTypeEnum];


/**
 * Check if a given object implements the AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner interface.
 */
export function instanceOfAccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner(value: object): value is AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner {
    if (!('productName' in value) || value['productName'] === undefined) return false;
    if (!('balanceType' in value) || value['balanceType'] === undefined) return false;
    if (!('displayAccountNumber' in value) || value['displayAccountNumber'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('currencyCode' in value) || value['currencyCode'] === undefined) return false;
    return true;
}

export function AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInnerFromJSON(json: any): AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner {
    return AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInnerFromJSONTyped(json, false);
}

export function AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'productName': json['productName'],
        'balanceType': json['balanceType'],
        'displayAccountNumber': json['displayAccountNumber'],
        'accountDescription': json['accountDescription'] == null ? undefined : json['accountDescription'],
        'accountNickname': json['accountNickname'] == null ? undefined : json['accountNickname'],
        'accountId': json['accountId'],
        'currencyCode': json['currencyCode'],
        'currentBalanceAmount': json['currentBalanceAmount'] == null ? undefined : json['currentBalanceAmount'],
        'creditAvailableAmount': json['creditAvailableAmount'] == null ? undefined : json['creditAvailableAmount'],
        'paymentDueAmount': json['paymentDueAmount'] == null ? undefined : json['paymentDueAmount'],
        'paymentDueDate': json['paymentDueDate'] == null ? undefined : (new Date(json['paymentDueDate'])),
        'autoPayFlag': json['autoPayFlag'] == null ? undefined : json['autoPayFlag'],
        'lastPaymentAmount': json['lastPaymentAmount'] == null ? undefined : json['lastPaymentAmount'],
        'lastPaymentDate': json['lastPaymentDate'] == null ? undefined : (new Date(json['lastPaymentDate'])),
    };
}

export function AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInnerToJSON(json: any): AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner {
    return AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInnerToJSONTyped(json, false);
}

export function AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInnerToJSONTyped(value?: AccountsDetailsGet200ResponseAccountGroupDetailsInnerLoanAccountsDetailsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productName': value['productName'],
        'balanceType': value['balanceType'],
        'displayAccountNumber': value['displayAccountNumber'],
        'accountDescription': value['accountDescription'],
        'accountNickname': value['accountNickname'],
        'accountId': value['accountId'],
        'currencyCode': value['currencyCode'],
        'currentBalanceAmount': value['currentBalanceAmount'],
        'creditAvailableAmount': value['creditAvailableAmount'],
        'paymentDueAmount': value['paymentDueAmount'],
        'paymentDueDate': value['paymentDueDate'] == null ? value['paymentDueDate'] : value['paymentDueDate'].toISOString().substring(0,10),
        'autoPayFlag': value['autoPayFlag'],
        'lastPaymentAmount': value['lastPaymentAmount'],
        'lastPaymentDate': value['lastPaymentDate'] == null ? value['lastPaymentDate'] : value['lastPaymentDate'].toISOString().substring(0,10),
    };
}

