// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/AccountCapability.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountCapabilityRequirements } from './AccountCapabilityRequirements';
import {
    AccountCapabilityRequirementsFromJSON,
    AccountCapabilityRequirementsFromJSONTyped,
    AccountCapabilityRequirementsToJSON,
    AccountCapabilityRequirementsToJSONTyped,
} from './AccountCapabilityRequirements';
import type { AccountCapabilityFutureRequirements } from './AccountCapabilityFutureRequirements';
import {
    AccountCapabilityFutureRequirementsFromJSON,
    AccountCapabilityFutureRequirementsFromJSONTyped,
    AccountCapabilityFutureRequirementsToJSON,
    AccountCapabilityFutureRequirementsToJSONTyped,
} from './AccountCapabilityFutureRequirements';
import type { AccountCapabilityAccount } from './AccountCapabilityAccount';
import {
    AccountCapabilityAccountFromJSON,
    AccountCapabilityAccountFromJSONTyped,
    AccountCapabilityAccountToJSON,
    AccountCapabilityAccountToJSONTyped,
} from './AccountCapabilityAccount';

/**
 * N/A
 * @export
 * @interface AccountCapability
 */
export interface AccountCapability {
    /**
     * 
     * @type {AccountCapabilityAccount}
     * @memberof AccountCapability
     */
    account: AccountCapabilityAccount;
    /**
     * 
     * @type {AccountCapabilityFutureRequirements}
     * @memberof AccountCapability
     */
    futureRequirements?: AccountCapabilityFutureRequirements;
    /**
     * N/A
     * @type {string}
     * @memberof AccountCapability
     */
    id: string;
    /**
     * N/A
     * @type {AccountCapabilityObjectEnum}
     * @memberof AccountCapability
     */
    object: AccountCapabilityObjectEnum;
    /**
     * N/A
     * @type {boolean}
     * @memberof AccountCapability
     */
    requested: boolean;
    /**
     * N/A
     * @type {number}
     * @memberof AccountCapability
     */
    requestedAt?: number;
    /**
     * 
     * @type {AccountCapabilityRequirements}
     * @memberof AccountCapability
     */
    requirements?: AccountCapabilityRequirements;
    /**
     * N/A
     * @type {AccountCapabilityStatusEnum}
     * @memberof AccountCapability
     */
    status: AccountCapabilityStatusEnum;
}


/**
 * @export
 */
export const AccountCapabilityObjectEnum = {
    Capability: 'capability'
} as const;
export type AccountCapabilityObjectEnum = typeof AccountCapabilityObjectEnum[keyof typeof AccountCapabilityObjectEnum];

/**
 * @export
 */
export const AccountCapabilityStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Pending: 'pending',
    Unrequested: 'unrequested'
} as const;
export type AccountCapabilityStatusEnum = typeof AccountCapabilityStatusEnum[keyof typeof AccountCapabilityStatusEnum];


/**
 * Check if a given object implements the AccountCapability interface.
 */
export function instanceOfAccountCapability(value: object): value is AccountCapability {
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('requested' in value) || value['requested'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AccountCapabilityFromJSON(json: any): AccountCapability {
    return AccountCapabilityFromJSONTyped(json, false);
}

export function AccountCapabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCapability {
    if (json == null) {
        return json;
    }
    return {
        
        'account': AccountCapabilityAccountFromJSON(json['account']),
        'futureRequirements': json['future_requirements'] == null ? undefined : AccountCapabilityFutureRequirementsFromJSON(json['future_requirements']),
        'id': json['id'],
        'object': json['object'],
        'requested': json['requested'],
        'requestedAt': json['requested_at'] == null ? undefined : json['requested_at'],
        'requirements': json['requirements'] == null ? undefined : AccountCapabilityRequirementsFromJSON(json['requirements']),
        'status': json['status'],
    };
}

export function AccountCapabilityToJSON(json: any): AccountCapability {
    return AccountCapabilityToJSONTyped(json, false);
}

export function AccountCapabilityToJSONTyped(value?: AccountCapability | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': AccountCapabilityAccountToJSON(value['account']),
        'future_requirements': AccountCapabilityFutureRequirementsToJSON(value['futureRequirements']),
        'id': value['id'],
        'object': value['object'],
        'requested': value['requested'],
        'requested_at': value['requestedAt'],
        'requirements': AccountCapabilityRequirementsToJSON(value['requirements']),
        'status': value['status'],
    };
}

