// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiCounterpartiesGet200ResponseInnerAccountsInnerRoutingDetailsInner } from './ApiCounterpartiesGet200ResponseInnerAccountsInnerRoutingDetailsInner';
import {
    ApiCounterpartiesGet200ResponseInnerAccountsInnerRoutingDetailsInnerFromJSON,
    ApiCounterpartiesGet200ResponseInnerAccountsInnerRoutingDetailsInnerFromJSONTyped,
    ApiCounterpartiesGet200ResponseInnerAccountsInnerRoutingDetailsInnerToJSON,
    ApiCounterpartiesGet200ResponseInnerAccountsInnerRoutingDetailsInnerToJSONTyped,
} from './ApiCounterpartiesGet200ResponseInnerAccountsInnerRoutingDetailsInner';
import type { ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInner } from './ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInner';
import {
    ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInnerFromJSON,
    ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInnerFromJSONTyped,
    ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInnerToJSON,
    ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInnerToJSONTyped,
} from './ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInner';

/**
 * 
 * @export
 * @interface ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
 */
export interface ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount {
    /**
     * 
     * @type {string}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    object: string;
    /**
     * N/A
     * @type {boolean}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    liveMode: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    discardedAt: Date;
    /**
     * N/A
     * @type {string}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    name: string;
    /**
     * N/A
     * @type {string}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    counterpartyId: string;
    /**
     * N/A
     * @type {string}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    internalAccountId: string;
    /**
     * N/A
     * @type {Array<ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInner>}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    accountDetails: Array<ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInner>;
    /**
     * N/A
     * @type {Array<ApiCounterpartiesGet200ResponseInnerAccountsInnerRoutingDetailsInner>}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    routingDetails: Array<ApiCounterpartiesGet200ResponseInnerAccountsInnerRoutingDetailsInner>;
    /**
     * N/A
     * @type {string}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    debitLedgerAccountId: string;
    /**
     * N/A
     * @type {string}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    creditLedgerAccountId: string;
    /**
     * N/A
     * @type {object}
     * @memberof ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount
     */
    metadata: object;
}

/**
 * Check if a given object implements the ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount interface.
 */
export function instanceOfApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount(value: object): value is ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('liveMode' in value) || value['liveMode'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('discardedAt' in value) || value['discardedAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('counterpartyId' in value) || value['counterpartyId'] === undefined) return false;
    if (!('internalAccountId' in value) || value['internalAccountId'] === undefined) return false;
    if (!('accountDetails' in value) || value['accountDetails'] === undefined) return false;
    if (!('routingDetails' in value) || value['routingDetails'] === undefined) return false;
    if (!('debitLedgerAccountId' in value) || value['debitLedgerAccountId'] === undefined) return false;
    if (!('creditLedgerAccountId' in value) || value['creditLedgerAccountId'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccountFromJSON(json: any): ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount {
    return ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccountFromJSONTyped(json, false);
}

export function ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'liveMode': json['live_mode'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'discardedAt': (new Date(json['discarded_at'])),
        'name': json['name'],
        'counterpartyId': json['counterparty_id'],
        'internalAccountId': json['internal_account_id'],
        'accountDetails': ((json['account_details'] as Array<any>).map(ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInnerFromJSON)),
        'routingDetails': ((json['routing_details'] as Array<any>).map(ApiCounterpartiesGet200ResponseInnerAccountsInnerRoutingDetailsInnerFromJSON)),
        'debitLedgerAccountId': json['debit_ledger_account_id'],
        'creditLedgerAccountId': json['credit_ledger_account_id'],
        'metadata': json['metadata'],
    };
}

export function ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccountToJSON(json: any): ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount {
    return ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccountToJSONTyped(json, false);
}

export function ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccountToJSONTyped(value?: ApiIncomingPaymentDetailsGet200ResponseInnerVirtualAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'live_mode': value['liveMode'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'discarded_at': value['discardedAt'].toISOString(),
        'name': value['name'],
        'counterparty_id': value['counterpartyId'],
        'internal_account_id': value['internalAccountId'],
        'account_details': ((value['accountDetails'] as Array<any>).map(ApiAccountsTypeAccountIdAccountDetailsGet200ResponseInnerToJSON)),
        'routing_details': ((value['routingDetails'] as Array<any>).map(ApiCounterpartiesGet200ResponseInnerAccountsInnerRoutingDetailsInnerToJSON)),
        'debit_ledger_account_id': value['debitLedgerAccountId'],
        'credit_ledger_account_id': value['creditLedgerAccountId'],
        'metadata': value['metadata'],
    };
}

