// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/ApiLedgerAccountPayoutsGet200ResponseInner.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiLedgerAccountPayoutsGet200ResponseInner
 */
export interface ApiLedgerAccountPayoutsGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    object: string;
    /**
     * N/A
     * @type {boolean}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    liveMode: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    updatedAt: Date;
    /**
     * N/A
     * @type {string}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    ledgerId: string;
    /**
     * N/A
     * @type {ApiLedgerAccountPayoutsGet200ResponseInnerStatusEnum}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    status: ApiLedgerAccountPayoutsGet200ResponseInnerStatusEnum;
    /**
     * N/A
     * @type {string}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    payoutLedgerAccountId: string;
    /**
     * N/A
     * @type {string}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    fundingLedgerAccountId: string;
    /**
     * N/A
     * @type {string}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    effectiveAtUpperBound: string;
    /**
     * N/A
     * @type {string}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    ledgerTransactionId: string;
    /**
     * N/A
     * @type {number}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    amount: number;
    /**
     * N/A
     * @type {string}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    currency: string;
    /**
     * N/A
     * @type {number}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    currencyExponent: number;
    /**
     * N/A
     * @type {object}
     * @memberof ApiLedgerAccountPayoutsGet200ResponseInner
     */
    metadata: object;
}


/**
 * @export
 */
export const ApiLedgerAccountPayoutsGet200ResponseInnerStatusEnum = {
    Archived: 'archived',
    Archiving: 'archiving',
    Pending: 'pending',
    Posted: 'posted',
    Processing: 'processing'
} as const;
export type ApiLedgerAccountPayoutsGet200ResponseInnerStatusEnum = typeof ApiLedgerAccountPayoutsGet200ResponseInnerStatusEnum[keyof typeof ApiLedgerAccountPayoutsGet200ResponseInnerStatusEnum];


/**
 * Check if a given object implements the ApiLedgerAccountPayoutsGet200ResponseInner interface.
 */
export function instanceOfApiLedgerAccountPayoutsGet200ResponseInner(value: object): value is ApiLedgerAccountPayoutsGet200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('liveMode' in value) || value['liveMode'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('ledgerId' in value) || value['ledgerId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('payoutLedgerAccountId' in value) || value['payoutLedgerAccountId'] === undefined) return false;
    if (!('fundingLedgerAccountId' in value) || value['fundingLedgerAccountId'] === undefined) return false;
    if (!('effectiveAtUpperBound' in value) || value['effectiveAtUpperBound'] === undefined) return false;
    if (!('ledgerTransactionId' in value) || value['ledgerTransactionId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('currencyExponent' in value) || value['currencyExponent'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function ApiLedgerAccountPayoutsGet200ResponseInnerFromJSON(json: any): ApiLedgerAccountPayoutsGet200ResponseInner {
    return ApiLedgerAccountPayoutsGet200ResponseInnerFromJSONTyped(json, false);
}

export function ApiLedgerAccountPayoutsGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLedgerAccountPayoutsGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'liveMode': json['live_mode'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'ledgerId': json['ledger_id'],
        'status': json['status'],
        'payoutLedgerAccountId': json['payout_ledger_account_id'],
        'fundingLedgerAccountId': json['funding_ledger_account_id'],
        'effectiveAtUpperBound': json['effective_at_upper_bound'],
        'ledgerTransactionId': json['ledger_transaction_id'],
        'amount': json['amount'],
        'currency': json['currency'],
        'currencyExponent': json['currency_exponent'],
        'metadata': json['metadata'],
    };
}

export function ApiLedgerAccountPayoutsGet200ResponseInnerToJSON(json: any): ApiLedgerAccountPayoutsGet200ResponseInner {
    return ApiLedgerAccountPayoutsGet200ResponseInnerToJSONTyped(json, false);
}

export function ApiLedgerAccountPayoutsGet200ResponseInnerToJSONTyped(value?: ApiLedgerAccountPayoutsGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'live_mode': value['liveMode'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'ledger_id': value['ledgerId'],
        'status': value['status'],
        'payout_ledger_account_id': value['payoutLedgerAccountId'],
        'funding_ledger_account_id': value['fundingLedgerAccountId'],
        'effective_at_upper_bound': value['effectiveAtUpperBound'],
        'ledger_transaction_id': value['ledgerTransactionId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'currency_exponent': value['currencyExponent'],
        'metadata': value['metadata'],
    };
}

