// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/ApiLedgerAccountBalanceMonitorsPostRequest.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiLedgerAccountBalanceMonitorsGet200ResponseInnerAlertCondition } from './ApiLedgerAccountBalanceMonitorsGet200ResponseInnerAlertCondition';
import {
    ApiLedgerAccountBalanceMonitorsGet200ResponseInnerAlertConditionFromJSON,
    ApiLedgerAccountBalanceMonitorsGet200ResponseInnerAlertConditionFromJSONTyped,
    ApiLedgerAccountBalanceMonitorsGet200ResponseInnerAlertConditionToJSON,
    ApiLedgerAccountBalanceMonitorsGet200ResponseInnerAlertConditionToJSONTyped,
} from './ApiLedgerAccountBalanceMonitorsGet200ResponseInnerAlertCondition';

/**
 * 
 * @export
 * @interface ApiLedgerAccountBalanceMonitorsPostRequest
 */
export interface ApiLedgerAccountBalanceMonitorsPostRequest {
    /**
     * N/A
     * @type {string}
     * @memberof ApiLedgerAccountBalanceMonitorsPostRequest
     */
    ledgerAccountId: string;
    /**
     * 
     * @type {ApiLedgerAccountBalanceMonitorsGet200ResponseInnerAlertCondition}
     * @memberof ApiLedgerAccountBalanceMonitorsPostRequest
     */
    alertCondition: ApiLedgerAccountBalanceMonitorsGet200ResponseInnerAlertCondition;
    /**
     * N/A
     * @type {object}
     * @memberof ApiLedgerAccountBalanceMonitorsPostRequest
     */
    metadata?: object;
}

/**
 * Check if a given object implements the ApiLedgerAccountBalanceMonitorsPostRequest interface.
 */
export function instanceOfApiLedgerAccountBalanceMonitorsPostRequest(value: object): value is ApiLedgerAccountBalanceMonitorsPostRequest {
    if (!('ledgerAccountId' in value) || value['ledgerAccountId'] === undefined) return false;
    if (!('alertCondition' in value) || value['alertCondition'] === undefined) return false;
    return true;
}

export function ApiLedgerAccountBalanceMonitorsPostRequestFromJSON(json: any): ApiLedgerAccountBalanceMonitorsPostRequest {
    return ApiLedgerAccountBalanceMonitorsPostRequestFromJSONTyped(json, false);
}

export function ApiLedgerAccountBalanceMonitorsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLedgerAccountBalanceMonitorsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ledgerAccountId': json['ledger_account_id'],
        'alertCondition': ApiLedgerAccountBalanceMonitorsGet200ResponseInnerAlertConditionFromJSON(json['alert_condition']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ApiLedgerAccountBalanceMonitorsPostRequestToJSON(json: any): ApiLedgerAccountBalanceMonitorsPostRequest {
    return ApiLedgerAccountBalanceMonitorsPostRequestToJSONTyped(json, false);
}

export function ApiLedgerAccountBalanceMonitorsPostRequestToJSONTyped(value?: ApiLedgerAccountBalanceMonitorsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ledger_account_id': value['ledgerAccountId'],
        'alert_condition': ApiLedgerAccountBalanceMonitorsGet200ResponseInnerAlertConditionToJSON(value['alertCondition']),
        'metadata': value['metadata'],
    };
}

