// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/ApiLedgerTransactionsIdReversalPost201Response.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiLedgerEntriesGet200ResponseInner } from './ApiLedgerEntriesGet200ResponseInner';
import {
    ApiLedgerEntriesGet200ResponseInnerFromJSON,
    ApiLedgerEntriesGet200ResponseInnerFromJSONTyped,
    ApiLedgerEntriesGet200ResponseInnerToJSON,
    ApiLedgerEntriesGet200ResponseInnerToJSONTyped,
} from './ApiLedgerEntriesGet200ResponseInner';

/**
 * 
 * @export
 * @interface ApiLedgerTransactionsIdReversalPost201Response
 */
export interface ApiLedgerTransactionsIdReversalPost201Response {
    /**
     * 
     * @type {string}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    object: string;
    /**
     * N/A
     * @type {boolean}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    liveMode: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    updatedAt: Date;
    /**
     * N/A
     * @type {ApiLedgerTransactionsIdReversalPost201ResponseStatusEnum}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    status: ApiLedgerTransactionsIdReversalPost201ResponseStatusEnum;
    /**
     * N/A
     * @type {object}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    metadata: object;
    /**
     * N/A
     * @type {Date}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    effectiveAt: Date;
    /**
     * N/A
     * @type {Date}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    effectiveDate: Date;
    /**
     * N/A
     * @type {Array<ApiLedgerEntriesGet200ResponseInner>}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    ledgerEntries: Array<ApiLedgerEntriesGet200ResponseInner>;
    /**
     * N/A
     * @type {string}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    postedAt: string;
    /**
     * N/A
     * @type {string}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    ledgerId: string;
    /**
     * N/A
     * @type {ApiLedgerTransactionsIdReversalPost201ResponseLedgerableTypeEnum}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    ledgerableType: ApiLedgerTransactionsIdReversalPost201ResponseLedgerableTypeEnum;
    /**
     * N/A
     * @type {string}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    ledgerableId: string;
    /**
     * N/A
     * @type {string}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    externalId: string;
    /**
     * N/A
     * @type {string}
     * @memberof ApiLedgerTransactionsIdReversalPost201Response
     */
    reversesLedgerTransactionId: string;
}


/**
 * @export
 */
export const ApiLedgerTransactionsIdReversalPost201ResponseStatusEnum = {
    Archived: 'archived',
    Pending: 'pending',
    Posted: 'posted'
} as const;
export type ApiLedgerTransactionsIdReversalPost201ResponseStatusEnum = typeof ApiLedgerTransactionsIdReversalPost201ResponseStatusEnum[keyof typeof ApiLedgerTransactionsIdReversalPost201ResponseStatusEnum];

/**
 * @export
 */
export const ApiLedgerTransactionsIdReversalPost201ResponseLedgerableTypeEnum = {
    Counterparty: 'counterparty',
    ExpectedPayment: 'expected_payment',
    IncomingPaymentDetail: 'incoming_payment_detail',
    InternalAccount: 'internal_account',
    LineItem: 'line_item',
    PaperItem: 'paper_item',
    PaymentOrder: 'payment_order',
    PaymentOrderAttempt: 'payment_order_attempt',
    Return: 'return',
    Reversal: 'reversal'
} as const;
export type ApiLedgerTransactionsIdReversalPost201ResponseLedgerableTypeEnum = typeof ApiLedgerTransactionsIdReversalPost201ResponseLedgerableTypeEnum[keyof typeof ApiLedgerTransactionsIdReversalPost201ResponseLedgerableTypeEnum];


/**
 * Check if a given object implements the ApiLedgerTransactionsIdReversalPost201Response interface.
 */
export function instanceOfApiLedgerTransactionsIdReversalPost201Response(value: object): value is ApiLedgerTransactionsIdReversalPost201Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('liveMode' in value) || value['liveMode'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('effectiveAt' in value) || value['effectiveAt'] === undefined) return false;
    if (!('effectiveDate' in value) || value['effectiveDate'] === undefined) return false;
    if (!('ledgerEntries' in value) || value['ledgerEntries'] === undefined) return false;
    if (!('postedAt' in value) || value['postedAt'] === undefined) return false;
    if (!('ledgerId' in value) || value['ledgerId'] === undefined) return false;
    if (!('ledgerableType' in value) || value['ledgerableType'] === undefined) return false;
    if (!('ledgerableId' in value) || value['ledgerableId'] === undefined) return false;
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('reversesLedgerTransactionId' in value) || value['reversesLedgerTransactionId'] === undefined) return false;
    return true;
}

export function ApiLedgerTransactionsIdReversalPost201ResponseFromJSON(json: any): ApiLedgerTransactionsIdReversalPost201Response {
    return ApiLedgerTransactionsIdReversalPost201ResponseFromJSONTyped(json, false);
}

export function ApiLedgerTransactionsIdReversalPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLedgerTransactionsIdReversalPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'liveMode': json['live_mode'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'status': json['status'],
        'metadata': json['metadata'],
        'effectiveAt': (new Date(json['effective_at'])),
        'effectiveDate': (new Date(json['effective_date'])),
        'ledgerEntries': ((json['ledger_entries'] as Array<any>).map(ApiLedgerEntriesGet200ResponseInnerFromJSON)),
        'postedAt': json['posted_at'],
        'ledgerId': json['ledger_id'],
        'ledgerableType': json['ledgerable_type'],
        'ledgerableId': json['ledgerable_id'],
        'externalId': json['external_id'],
        'reversesLedgerTransactionId': json['reverses_ledger_transaction_id'],
    };
}

export function ApiLedgerTransactionsIdReversalPost201ResponseToJSON(json: any): ApiLedgerTransactionsIdReversalPost201Response {
    return ApiLedgerTransactionsIdReversalPost201ResponseToJSONTyped(json, false);
}

export function ApiLedgerTransactionsIdReversalPost201ResponseToJSONTyped(value?: ApiLedgerTransactionsIdReversalPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'live_mode': value['liveMode'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'status': value['status'],
        'metadata': value['metadata'],
        'effective_at': value['effectiveAt'].toISOString().substring(0,10),
        'effective_date': value['effectiveDate'].toISOString().substring(0,10),
        'ledger_entries': ((value['ledgerEntries'] as Array<any>).map(ApiLedgerEntriesGet200ResponseInnerToJSON)),
        'posted_at': value['postedAt'],
        'ledger_id': value['ledgerId'],
        'ledgerable_type': value['ledgerableType'],
        'ledgerable_id': value['ledgerableId'],
        'external_id': value['externalId'],
        'reverses_ledger_transaction_id': value['reversesLedgerTransactionId'],
    };
}

