// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/BalanceAmountBySourceType.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface BalanceAmountBySourceType
 */
export interface BalanceAmountBySourceType {
    /**
     * N/A
     * @type {number}
     * @memberof BalanceAmountBySourceType
     */
    bankAccount?: number;
    /**
     * N/A
     * @type {number}
     * @memberof BalanceAmountBySourceType
     */
    card?: number;
    /**
     * N/A
     * @type {number}
     * @memberof BalanceAmountBySourceType
     */
    fpx?: number;
}

/**
 * Check if a given object implements the BalanceAmountBySourceType interface.
 */
export function instanceOfBalanceAmountBySourceType(value: object): value is BalanceAmountBySourceType {
    return true;
}

export function BalanceAmountBySourceTypeFromJSON(json: any): BalanceAmountBySourceType {
    return BalanceAmountBySourceTypeFromJSONTyped(json, false);
}

export function BalanceAmountBySourceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceAmountBySourceType {
    if (json == null) {
        return json;
    }
    return {
        
        'bankAccount': json['bank_account'] == null ? undefined : json['bank_account'],
        'card': json['card'] == null ? undefined : json['card'],
        'fpx': json['fpx'] == null ? undefined : json['fpx'],
    };
}

export function BalanceAmountBySourceTypeToJSON(json: any): BalanceAmountBySourceType {
    return BalanceAmountBySourceTypeToJSONTyped(json, false);
}

export function BalanceAmountBySourceTypeToJSONTyped(value?: BalanceAmountBySourceType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bank_account': value['bankAccount'],
        'card': value['card'],
        'fpx': value['fpx'],
    };
}

