// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/BalanceSettingsResourcePayments.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BalanceSettingsResourcePayouts } from './BalanceSettingsResourcePayouts';
import {
    BalanceSettingsResourcePayoutsFromJSON,
    BalanceSettingsResourcePayoutsFromJSONTyped,
    BalanceSettingsResourcePayoutsToJSON,
    BalanceSettingsResourcePayoutsToJSONTyped,
} from './BalanceSettingsResourcePayouts';
import type { BalanceSettingsResourceSettlementTiming } from './BalanceSettingsResourceSettlementTiming';
import {
    BalanceSettingsResourceSettlementTimingFromJSON,
    BalanceSettingsResourceSettlementTimingFromJSONTyped,
    BalanceSettingsResourceSettlementTimingToJSON,
    BalanceSettingsResourceSettlementTimingToJSONTyped,
} from './BalanceSettingsResourceSettlementTiming';

/**
 * N/A
 * @export
 * @interface BalanceSettingsResourcePayments
 */
export interface BalanceSettingsResourcePayments {
    /**
     * N/A
     * @type {boolean}
     * @memberof BalanceSettingsResourcePayments
     */
    debitNegativeBalances?: boolean;
    /**
     * 
     * @type {BalanceSettingsResourcePayouts}
     * @memberof BalanceSettingsResourcePayments
     */
    payouts?: BalanceSettingsResourcePayouts;
    /**
     * 
     * @type {BalanceSettingsResourceSettlementTiming}
     * @memberof BalanceSettingsResourcePayments
     */
    settlementTiming: BalanceSettingsResourceSettlementTiming;
}

/**
 * Check if a given object implements the BalanceSettingsResourcePayments interface.
 */
export function instanceOfBalanceSettingsResourcePayments(value: object): value is BalanceSettingsResourcePayments {
    if (!('settlementTiming' in value) || value['settlementTiming'] === undefined) return false;
    return true;
}

export function BalanceSettingsResourcePaymentsFromJSON(json: any): BalanceSettingsResourcePayments {
    return BalanceSettingsResourcePaymentsFromJSONTyped(json, false);
}

export function BalanceSettingsResourcePaymentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceSettingsResourcePayments {
    if (json == null) {
        return json;
    }
    return {
        
        'debitNegativeBalances': json['debit_negative_balances'] == null ? undefined : json['debit_negative_balances'],
        'payouts': json['payouts'] == null ? undefined : BalanceSettingsResourcePayoutsFromJSON(json['payouts']),
        'settlementTiming': BalanceSettingsResourceSettlementTimingFromJSON(json['settlement_timing']),
    };
}

export function BalanceSettingsResourcePaymentsToJSON(json: any): BalanceSettingsResourcePayments {
    return BalanceSettingsResourcePaymentsToJSONTyped(json, false);
}

export function BalanceSettingsResourcePaymentsToJSONTyped(value?: BalanceSettingsResourcePayments | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'debit_negative_balances': value['debitNegativeBalances'],
        'payouts': BalanceSettingsResourcePayoutsToJSON(value['payouts']),
        'settlement_timing': BalanceSettingsResourceSettlementTimingToJSON(value['settlementTiming']),
    };
}

