// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/BillingCreditGrantsResourceMonetaryAmount.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface BillingCreditGrantsResourceMonetaryAmount
 */
export interface BillingCreditGrantsResourceMonetaryAmount {
    /**
     * N/A
     * @type {string}
     * @memberof BillingCreditGrantsResourceMonetaryAmount
     */
    currency: string;
    /**
     * N/A
     * @type {number}
     * @memberof BillingCreditGrantsResourceMonetaryAmount
     */
    value: number;
}

/**
 * Check if a given object implements the BillingCreditGrantsResourceMonetaryAmount interface.
 */
export function instanceOfBillingCreditGrantsResourceMonetaryAmount(value: object): value is BillingCreditGrantsResourceMonetaryAmount {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function BillingCreditGrantsResourceMonetaryAmountFromJSON(json: any): BillingCreditGrantsResourceMonetaryAmount {
    return BillingCreditGrantsResourceMonetaryAmountFromJSONTyped(json, false);
}

export function BillingCreditGrantsResourceMonetaryAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingCreditGrantsResourceMonetaryAmount {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'value': json['value'],
    };
}

export function BillingCreditGrantsResourceMonetaryAmountToJSON(json: any): BillingCreditGrantsResourceMonetaryAmount {
    return BillingCreditGrantsResourceMonetaryAmountToJSONTyped(json, false);
}

export function BillingCreditGrantsResourceMonetaryAmountToJSONTyped(value?: BillingCreditGrantsResourceMonetaryAmount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'value': value['value'],
    };
}

