// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/ConnectEmbeddedDisputesListFeatures.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface ConnectEmbeddedDisputesListFeatures
 */
export interface ConnectEmbeddedDisputesListFeatures {
    /**
     * N/A
     * @type {boolean}
     * @memberof ConnectEmbeddedDisputesListFeatures
     */
    capturePayments: boolean;
    /**
     * N/A
     * @type {boolean}
     * @memberof ConnectEmbeddedDisputesListFeatures
     */
    destinationOnBehalfOfChargeManagement: boolean;
    /**
     * N/A
     * @type {boolean}
     * @memberof ConnectEmbeddedDisputesListFeatures
     */
    disputeManagement: boolean;
    /**
     * N/A
     * @type {boolean}
     * @memberof ConnectEmbeddedDisputesListFeatures
     */
    refundManagement: boolean;
}

/**
 * Check if a given object implements the ConnectEmbeddedDisputesListFeatures interface.
 */
export function instanceOfConnectEmbeddedDisputesListFeatures(value: object): value is ConnectEmbeddedDisputesListFeatures {
    if (!('capturePayments' in value) || value['capturePayments'] === undefined) return false;
    if (!('destinationOnBehalfOfChargeManagement' in value) || value['destinationOnBehalfOfChargeManagement'] === undefined) return false;
    if (!('disputeManagement' in value) || value['disputeManagement'] === undefined) return false;
    if (!('refundManagement' in value) || value['refundManagement'] === undefined) return false;
    return true;
}

export function ConnectEmbeddedDisputesListFeaturesFromJSON(json: any): ConnectEmbeddedDisputesListFeatures {
    return ConnectEmbeddedDisputesListFeaturesFromJSONTyped(json, false);
}

export function ConnectEmbeddedDisputesListFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectEmbeddedDisputesListFeatures {
    if (json == null) {
        return json;
    }
    return {
        
        'capturePayments': json['capture_payments'],
        'destinationOnBehalfOfChargeManagement': json['destination_on_behalf_of_charge_management'],
        'disputeManagement': json['dispute_management'],
        'refundManagement': json['refund_management'],
    };
}

export function ConnectEmbeddedDisputesListFeaturesToJSON(json: any): ConnectEmbeddedDisputesListFeatures {
    return ConnectEmbeddedDisputesListFeaturesToJSONTyped(json, false);
}

export function ConnectEmbeddedDisputesListFeaturesToJSONTyped(value?: ConnectEmbeddedDisputesListFeatures | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capture_payments': value['capturePayments'],
        'destination_on_behalf_of_charge_management': value['destinationOnBehalfOfChargeManagement'],
        'dispute_management': value['disputeManagement'],
        'refund_management': value['refundManagement'],
    };
}

