// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/CreditBankIncomeGetPostDefaultResponseBankIncomeInner.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditBankIncomeGetPostDefaultResponseBankIncomeInnerBankIncomeSummary } from './CreditBankIncomeGetPostDefaultResponseBankIncomeInnerBankIncomeSummary';
import {
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerBankIncomeSummaryFromJSON,
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerBankIncomeSummaryFromJSONTyped,
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerBankIncomeSummaryToJSON,
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerBankIncomeSummaryToJSONTyped,
} from './CreditBankIncomeGetPostDefaultResponseBankIncomeInnerBankIncomeSummary';
import type { CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner } from './CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner';
import {
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerFromJSON,
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerFromJSONTyped,
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerToJSON,
    CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerToJSONTyped,
} from './CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner';

/**
 * 
 * @export
 * @interface CreditBankIncomeGetPostDefaultResponseBankIncomeInner
 */
export interface CreditBankIncomeGetPostDefaultResponseBankIncomeInner {
    /**
     * 
     * @type {string}
     * @memberof CreditBankIncomeGetPostDefaultResponseBankIncomeInner
     */
    bankIncomeId?: string;
    /**
     * 
     * @type {CreditBankIncomeGetPostDefaultResponseBankIncomeInnerBankIncomeSummary}
     * @memberof CreditBankIncomeGetPostDefaultResponseBankIncomeInner
     */
    bankIncomeSummary?: CreditBankIncomeGetPostDefaultResponseBankIncomeInnerBankIncomeSummary;
    /**
     * 
     * @type {number}
     * @memberof CreditBankIncomeGetPostDefaultResponseBankIncomeInner
     */
    daysRequested?: number;
    /**
     * 
     * @type {Date}
     * @memberof CreditBankIncomeGetPostDefaultResponseBankIncomeInner
     */
    generatedTime?: Date;
    /**
     * 
     * @type {Array<CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner>}
     * @memberof CreditBankIncomeGetPostDefaultResponseBankIncomeInner
     */
    items?: Array<CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInner>;
}

/**
 * Check if a given object implements the CreditBankIncomeGetPostDefaultResponseBankIncomeInner interface.
 */
export function instanceOfCreditBankIncomeGetPostDefaultResponseBankIncomeInner(value: object): value is CreditBankIncomeGetPostDefaultResponseBankIncomeInner {
    return true;
}

export function CreditBankIncomeGetPostDefaultResponseBankIncomeInnerFromJSON(json: any): CreditBankIncomeGetPostDefaultResponseBankIncomeInner {
    return CreditBankIncomeGetPostDefaultResponseBankIncomeInnerFromJSONTyped(json, false);
}

export function CreditBankIncomeGetPostDefaultResponseBankIncomeInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditBankIncomeGetPostDefaultResponseBankIncomeInner {
    if (json == null) {
        return json;
    }
    return {
        
        'bankIncomeId': json['bank_income_id'] == null ? undefined : json['bank_income_id'],
        'bankIncomeSummary': json['bank_income_summary'] == null ? undefined : CreditBankIncomeGetPostDefaultResponseBankIncomeInnerBankIncomeSummaryFromJSON(json['bank_income_summary']),
        'daysRequested': json['days_requested'] == null ? undefined : json['days_requested'],
        'generatedTime': json['generated_time'] == null ? undefined : (new Date(json['generated_time'])),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerFromJSON)),
    };
}

export function CreditBankIncomeGetPostDefaultResponseBankIncomeInnerToJSON(json: any): CreditBankIncomeGetPostDefaultResponseBankIncomeInner {
    return CreditBankIncomeGetPostDefaultResponseBankIncomeInnerToJSONTyped(json, false);
}

export function CreditBankIncomeGetPostDefaultResponseBankIncomeInnerToJSONTyped(value?: CreditBankIncomeGetPostDefaultResponseBankIncomeInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bank_income_id': value['bankIncomeId'],
        'bank_income_summary': CreditBankIncomeGetPostDefaultResponseBankIncomeInnerBankIncomeSummaryToJSON(value['bankIncomeSummary']),
        'days_requested': value['daysRequested'],
        'generated_time': value['generatedTime'] == null ? value['generatedTime'] : value['generatedTime'].toISOString(),
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CreditBankIncomeGetPostDefaultResponseBankIncomeInnerItemsInnerToJSON)),
    };
}

