// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft
 */
export interface CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft {
    /**
     * 
     * @type {string}
     * @memberof CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft
     */
    balanceTransaction: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft
     */
    linkedTransaction: string | null;
}

/**
 * Check if a given object implements the CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft interface.
 */
export function instanceOfCustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft(value: object): value is CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft {
    if (!('balanceTransaction' in value) || value['balanceTransaction'] === undefined) return false;
    if (!('linkedTransaction' in value) || value['linkedTransaction'] === undefined) return false;
    return true;
}

export function CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftFromJSON(json: any): CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft {
    return CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftFromJSONTyped(json, false);
}

export function CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft {
    if (json == null) {
        return json;
    }
    return {
        
        'balanceTransaction': json['balance_transaction'],
        'linkedTransaction': json['linked_transaction'],
    };
}

export function CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftToJSON(json: any): CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft {
    return CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftToJSONTyped(json, false);
}

export function CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftToJSONTyped(value?: CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'balance_transaction': value['balanceTransaction'],
        'linked_transaction': value['linkedTransaction'],
    };
}

