// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/CustomerCashBalanceTransaction.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction } from './CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction';
import {
    CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionFromJSON,
    CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionFromJSONTyped,
    CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionToJSON,
    CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionToJSONTyped,
} from './CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction';
import type { CustomerCashBalanceTransactionCustomer } from './CustomerCashBalanceTransactionCustomer';
import {
    CustomerCashBalanceTransactionCustomerFromJSON,
    CustomerCashBalanceTransactionCustomerFromJSONTyped,
    CustomerCashBalanceTransactionCustomerToJSON,
    CustomerCashBalanceTransactionCustomerToJSONTyped,
} from './CustomerCashBalanceTransactionCustomer';
import type { CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft } from './CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft';
import {
    CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftFromJSON,
    CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftFromJSONTyped,
    CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftToJSON,
    CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftToJSONTyped,
} from './CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft';
import type { CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction } from './CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction';
import {
    CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionFromJSON,
    CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionFromJSONTyped,
    CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionToJSON,
    CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionToJSONTyped,
} from './CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction';
import type { CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction } from './CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction';
import {
    CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionFromJSON,
    CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionFromJSONTyped,
    CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionToJSON,
    CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionToJSONTyped,
} from './CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction';
import type { CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance } from './CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance';
import {
    CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceFromJSON,
    CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceFromJSONTyped,
    CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceToJSON,
    CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceToJSONTyped,
} from './CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance';
import type { CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction } from './CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction';
import {
    CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionFromJSON,
    CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionFromJSONTyped,
    CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionToJSON,
    CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionToJSONTyped,
} from './CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction';

/**
 * N/A
 * @export
 * @interface CustomerCashBalanceTransaction
 */
export interface CustomerCashBalanceTransaction {
    /**
     * 
     * @type {CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft}
     * @memberof CustomerCashBalanceTransaction
     */
    adjustedForOverdraft?: CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft;
    /**
     * 
     * @type {CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction}
     * @memberof CustomerCashBalanceTransaction
     */
    appliedToPayment?: CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction;
    /**
     * N/A
     * @type {number}
     * @memberof CustomerCashBalanceTransaction
     */
    created: number;
    /**
     * N/A
     * @type {string}
     * @memberof CustomerCashBalanceTransaction
     */
    currency: string;
    /**
     * 
     * @type {CustomerCashBalanceTransactionCustomer}
     * @memberof CustomerCashBalanceTransaction
     */
    customer: CustomerCashBalanceTransactionCustomer;
    /**
     * N/A
     * @type {string}
     * @memberof CustomerCashBalanceTransaction
     */
    customerAccount?: string;
    /**
     * N/A
     * @type {number}
     * @memberof CustomerCashBalanceTransaction
     */
    endingBalance: number;
    /**
     * 
     * @type {CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction}
     * @memberof CustomerCashBalanceTransaction
     */
    funded?: CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction;
    /**
     * N/A
     * @type {string}
     * @memberof CustomerCashBalanceTransaction
     */
    id: string;
    /**
     * N/A
     * @type {boolean}
     * @memberof CustomerCashBalanceTransaction
     */
    livemode: boolean;
    /**
     * N/A
     * @type {number}
     * @memberof CustomerCashBalanceTransaction
     */
    netAmount: number;
    /**
     * N/A
     * @type {CustomerCashBalanceTransactionObjectEnum}
     * @memberof CustomerCashBalanceTransaction
     */
    object: CustomerCashBalanceTransactionObjectEnum;
    /**
     * 
     * @type {CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction}
     * @memberof CustomerCashBalanceTransaction
     */
    refundedFromPayment?: CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction;
    /**
     * 
     * @type {CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance}
     * @memberof CustomerCashBalanceTransaction
     */
    transferredToBalance?: CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance;
    /**
     * N/A
     * @type {CustomerCashBalanceTransactionTypeEnum}
     * @memberof CustomerCashBalanceTransaction
     */
    type: CustomerCashBalanceTransactionTypeEnum;
    /**
     * 
     * @type {CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction}
     * @memberof CustomerCashBalanceTransaction
     */
    unappliedFromPayment?: CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction;
}


/**
 * @export
 */
export const CustomerCashBalanceTransactionObjectEnum = {
    CustomerCashBalanceTransaction: 'customer_cash_balance_transaction'
} as const;
export type CustomerCashBalanceTransactionObjectEnum = typeof CustomerCashBalanceTransactionObjectEnum[keyof typeof CustomerCashBalanceTransactionObjectEnum];

/**
 * @export
 */
export const CustomerCashBalanceTransactionTypeEnum = {
    AdjustedForOverdraft: 'adjusted_for_overdraft',
    AppliedToPayment: 'applied_to_payment',
    Funded: 'funded',
    FundingReversed: 'funding_reversed',
    RefundedFromPayment: 'refunded_from_payment',
    ReturnCanceled: 'return_canceled',
    ReturnInitiated: 'return_initiated',
    TransferredToBalance: 'transferred_to_balance',
    UnappliedFromPayment: 'unapplied_from_payment'
} as const;
export type CustomerCashBalanceTransactionTypeEnum = typeof CustomerCashBalanceTransactionTypeEnum[keyof typeof CustomerCashBalanceTransactionTypeEnum];


/**
 * Check if a given object implements the CustomerCashBalanceTransaction interface.
 */
export function instanceOfCustomerCashBalanceTransaction(value: object): value is CustomerCashBalanceTransaction {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('customer' in value) || value['customer'] === undefined) return false;
    if (!('endingBalance' in value) || value['endingBalance'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('livemode' in value) || value['livemode'] === undefined) return false;
    if (!('netAmount' in value) || value['netAmount'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CustomerCashBalanceTransactionFromJSON(json: any): CustomerCashBalanceTransaction {
    return CustomerCashBalanceTransactionFromJSONTyped(json, false);
}

export function CustomerCashBalanceTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerCashBalanceTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'adjustedForOverdraft': json['adjusted_for_overdraft'] == null ? undefined : CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftFromJSON(json['adjusted_for_overdraft']),
        'appliedToPayment': json['applied_to_payment'] == null ? undefined : CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionFromJSON(json['applied_to_payment']),
        'created': json['created'],
        'currency': json['currency'],
        'customer': CustomerCashBalanceTransactionCustomerFromJSON(json['customer']),
        'customerAccount': json['customer_account'] == null ? undefined : json['customer_account'],
        'endingBalance': json['ending_balance'],
        'funded': json['funded'] == null ? undefined : CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionFromJSON(json['funded']),
        'id': json['id'],
        'livemode': json['livemode'],
        'netAmount': json['net_amount'],
        'object': json['object'],
        'refundedFromPayment': json['refunded_from_payment'] == null ? undefined : CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionFromJSON(json['refunded_from_payment']),
        'transferredToBalance': json['transferred_to_balance'] == null ? undefined : CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceFromJSON(json['transferred_to_balance']),
        'type': json['type'],
        'unappliedFromPayment': json['unapplied_from_payment'] == null ? undefined : CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionFromJSON(json['unapplied_from_payment']),
    };
}

export function CustomerCashBalanceTransactionToJSON(json: any): CustomerCashBalanceTransaction {
    return CustomerCashBalanceTransactionToJSONTyped(json, false);
}

export function CustomerCashBalanceTransactionToJSONTyped(value?: CustomerCashBalanceTransaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adjusted_for_overdraft': CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftToJSON(value['adjustedForOverdraft']),
        'applied_to_payment': CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionToJSON(value['appliedToPayment']),
        'created': value['created'],
        'currency': value['currency'],
        'customer': CustomerCashBalanceTransactionCustomerToJSON(value['customer']),
        'customer_account': value['customerAccount'],
        'ending_balance': value['endingBalance'],
        'funded': CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionToJSON(value['funded']),
        'id': value['id'],
        'livemode': value['livemode'],
        'net_amount': value['netAmount'],
        'object': value['object'],
        'refunded_from_payment': CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionToJSON(value['refundedFromPayment']),
        'transferred_to_balance': CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceToJSON(value['transferredToBalance']),
        'type': value['type'],
        'unapplied_from_payment': CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionToJSON(value['unappliedFromPayment']),
    };
}

