// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/DisputeEnhancedEvidenceVisaCompellingEvidence3.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DisputeVisaCompellingEvidence3PriorUndisputedTransaction } from './DisputeVisaCompellingEvidence3PriorUndisputedTransaction';
import {
    DisputeVisaCompellingEvidence3PriorUndisputedTransactionFromJSON,
    DisputeVisaCompellingEvidence3PriorUndisputedTransactionFromJSONTyped,
    DisputeVisaCompellingEvidence3PriorUndisputedTransactionToJSON,
    DisputeVisaCompellingEvidence3PriorUndisputedTransactionToJSONTyped,
} from './DisputeVisaCompellingEvidence3PriorUndisputedTransaction';
import type { DisputeVisaCompellingEvidence3DisputedTransaction } from './DisputeVisaCompellingEvidence3DisputedTransaction';
import {
    DisputeVisaCompellingEvidence3DisputedTransactionFromJSON,
    DisputeVisaCompellingEvidence3DisputedTransactionFromJSONTyped,
    DisputeVisaCompellingEvidence3DisputedTransactionToJSON,
    DisputeVisaCompellingEvidence3DisputedTransactionToJSONTyped,
} from './DisputeVisaCompellingEvidence3DisputedTransaction';

/**
 * N/A
 * @export
 * @interface DisputeEnhancedEvidenceVisaCompellingEvidence3
 */
export interface DisputeEnhancedEvidenceVisaCompellingEvidence3 {
    /**
     * 
     * @type {DisputeVisaCompellingEvidence3DisputedTransaction}
     * @memberof DisputeEnhancedEvidenceVisaCompellingEvidence3
     */
    disputedTransaction?: DisputeVisaCompellingEvidence3DisputedTransaction;
    /**
     * N/A
     * @type {Array<DisputeVisaCompellingEvidence3PriorUndisputedTransaction>}
     * @memberof DisputeEnhancedEvidenceVisaCompellingEvidence3
     */
    priorUndisputedTransactions: Array<DisputeVisaCompellingEvidence3PriorUndisputedTransaction>;
}

/**
 * Check if a given object implements the DisputeEnhancedEvidenceVisaCompellingEvidence3 interface.
 */
export function instanceOfDisputeEnhancedEvidenceVisaCompellingEvidence3(value: object): value is DisputeEnhancedEvidenceVisaCompellingEvidence3 {
    if (!('priorUndisputedTransactions' in value) || value['priorUndisputedTransactions'] === undefined) return false;
    return true;
}

export function DisputeEnhancedEvidenceVisaCompellingEvidence3FromJSON(json: any): DisputeEnhancedEvidenceVisaCompellingEvidence3 {
    return DisputeEnhancedEvidenceVisaCompellingEvidence3FromJSONTyped(json, false);
}

export function DisputeEnhancedEvidenceVisaCompellingEvidence3FromJSONTyped(json: any, ignoreDiscriminator: boolean): DisputeEnhancedEvidenceVisaCompellingEvidence3 {
    if (json == null) {
        return json;
    }
    return {
        
        'disputedTransaction': json['disputed_transaction'] == null ? undefined : DisputeVisaCompellingEvidence3DisputedTransactionFromJSON(json['disputed_transaction']),
        'priorUndisputedTransactions': ((json['prior_undisputed_transactions'] as Array<any>).map(DisputeVisaCompellingEvidence3PriorUndisputedTransactionFromJSON)),
    };
}

export function DisputeEnhancedEvidenceVisaCompellingEvidence3ToJSON(json: any): DisputeEnhancedEvidenceVisaCompellingEvidence3 {
    return DisputeEnhancedEvidenceVisaCompellingEvidence3ToJSONTyped(json, false);
}

export function DisputeEnhancedEvidenceVisaCompellingEvidence3ToJSONTyped(value?: DisputeEnhancedEvidenceVisaCompellingEvidence3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disputed_transaction': DisputeVisaCompellingEvidence3DisputedTransactionToJSON(value['disputedTransaction']),
        'prior_undisputed_transactions': ((value['priorUndisputedTransactions'] as Array<any>).map(DisputeVisaCompellingEvidence3PriorUndisputedTransactionToJSON)),
    };
}

