// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/InvoiceMandateOptionsCard.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface InvoiceMandateOptionsCard
 */
export interface InvoiceMandateOptionsCard {
    /**
     * N/A
     * @type {number}
     * @memberof InvoiceMandateOptionsCard
     */
    amount?: number;
    /**
     * N/A
     * @type {InvoiceMandateOptionsCardAmountTypeEnum}
     * @memberof InvoiceMandateOptionsCard
     */
    amountType?: InvoiceMandateOptionsCardAmountTypeEnum;
}


/**
 * @export
 */
export const InvoiceMandateOptionsCardAmountTypeEnum = {
    Fixed: 'fixed',
    Maximum: 'maximum'
} as const;
export type InvoiceMandateOptionsCardAmountTypeEnum = typeof InvoiceMandateOptionsCardAmountTypeEnum[keyof typeof InvoiceMandateOptionsCardAmountTypeEnum];


/**
 * Check if a given object implements the InvoiceMandateOptionsCard interface.
 */
export function instanceOfInvoiceMandateOptionsCard(value: object): value is InvoiceMandateOptionsCard {
    return true;
}

export function InvoiceMandateOptionsCardFromJSON(json: any): InvoiceMandateOptionsCard {
    return InvoiceMandateOptionsCardFromJSONTyped(json, false);
}

export function InvoiceMandateOptionsCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceMandateOptionsCard {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'amountType': json['amount_type'] == null ? undefined : json['amount_type'],
    };
}

export function InvoiceMandateOptionsCardToJSON(json: any): InvoiceMandateOptionsCard {
    return InvoiceMandateOptionsCardToJSONTyped(json, false);
}

export function InvoiceMandateOptionsCardToJSONTyped(value?: InvoiceMandateOptionsCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'amount_type': value['amountType'],
    };
}



================================================================================
// APPENDED FROM REPO: diplomat-bit/aibankingmtls | ORIGINAL PATH: diplomat-bit-aibankingmtls-6a06a68/models/InvoiceMandateOptionsCard-1.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface InvoiceMandateOptionsCard
 */
export interface InvoiceMandateOptionsCard {
    /**
     * N/A
     * @type {number}
     * @memberof InvoiceMandateOptionsCard
     */
    amount?: number;
    /**
     * N/A
     * @type {InvoiceMandateOptionsCardAmountTypeEnum}
     * @memberof InvoiceMandateOptionsCard
     */
    amountType?: InvoiceMandateOptionsCardAmountTypeEnum;
}


/**
 * @export
 */
export const InvoiceMandateOptionsCardAmountTypeEnum = {
    Fixed: 'fixed',
    Maximum: 'maximum'
} as const;
export type InvoiceMandateOptionsCardAmountTypeEnum = typeof InvoiceMandateOptionsCardAmountTypeEnum[keyof typeof InvoiceMandateOptionsCardAmountTypeEnum];


/**
 * Check if a given object implements the InvoiceMandateOptionsCard interface.
 */
export function instanceOfInvoiceMandateOptionsCard(value: object): value is InvoiceMandateOptionsCard {
    return true;
}

export function InvoiceMandateOptionsCardFromJSON(json: any): InvoiceMandateOptionsCard {
    return InvoiceMandateOptionsCardFromJSONTyped(json, false);
}

export function InvoiceMandateOptionsCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceMandateOptionsCard {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'amountType': json['amount_type'] == null ? undefined : json['amount_type'],
    };
}

export function InvoiceMandateOptionsCardToJSON(json: any): InvoiceMandateOptionsCard {
    return InvoiceMandateOptionsCardToJSONTyped(json, false);
}

export function InvoiceMandateOptionsCardToJSONTyped(value?: InvoiceMandateOptionsCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'amount_type': value['amountType'],
    };
}

