// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentFlowsSetupIntentSetupAttemptApplication } from './PaymentFlowsSetupIntentSetupAttemptApplication';
import {
    PaymentFlowsSetupIntentSetupAttemptApplicationFromJSON,
    PaymentFlowsSetupIntentSetupAttemptApplicationFromJSONTyped,
    PaymentFlowsSetupIntentSetupAttemptApplicationToJSON,
    PaymentFlowsSetupIntentSetupAttemptApplicationToJSONTyped,
} from './PaymentFlowsSetupIntentSetupAttemptApplication';
import type { PaymentIntent } from './PaymentIntent';
import {
    PaymentIntentFromJSON,
    PaymentIntentFromJSONTyped,
    PaymentIntentToJSON,
    PaymentIntentToJSONTyped,
} from './PaymentIntent';
import type { Shipping } from './Shipping';
import {
    ShippingFromJSON,
    ShippingFromJSONTyped,
    ShippingToJSON,
    ShippingToJSONTyped,
} from './Shipping';
import type { CardCustomer } from './CardCustomer';
import {
    CardCustomerFromJSON,
    CardCustomerFromJSONTyped,
    CardCustomerToJSON,
    CardCustomerToJSONTyped,
} from './CardCustomer';

/**
 * N/A
 * @export
 * @interface InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
 */
export interface InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent {
    /**
     * N/A
     * @type {number}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    amount?: number;
    /**
     * N/A
     * @type {number}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    amountCapturable?: number;
    /**
     * 
     * @type {}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    amountDetails?:  | null;
    /**
     * N/A
     * @type {number}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    amountReceived?: number;
    /**
     * 
     * @type {PaymentFlowsSetupIntentSetupAttemptApplication}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    application?: PaymentFlowsSetupIntentSetupAttemptApplication;
    /**
     * N/A
     * @type {number}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    applicationFeeAmount?: number;
    /**
     * N/A
     * @type {}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    automaticPaymentMethods?:  | null;
    /**
     * N/A
     * @type {number}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    canceledAt?: number;
    /**
     * N/A
     * @type {InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentCancellationReasonEnum}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    cancellationReason?: InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentCancellationReasonEnum;
    /**
     * N/A
     * @type {InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentCaptureMethodEnum}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    captureMethod?: InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentCaptureMethodEnum;
    /**
     * N/A
     * @type {string}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    clientSecret?: string;
    /**
     * N/A
     * @type {InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentConfirmationMethodEnum}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    confirmationMethod?: InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentConfirmationMethodEnum;
    /**
     * N/A
     * @type {number}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    created: number;
    /**
     * N/A
     * @type {string}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    currency?: string;
    /**
     * 
     * @type {CardCustomer}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    customer?: CardCustomer | null;
    /**
     * N/A
     * @type {string}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    customerAccount?: string;
    /**
     * N/A
     * @type {Array<string>}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    excludedPaymentMethodTypes?: Array<string>;
    /**
     * N/A
     * @type {object}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    hooks?: object;
    /**
     * N/A
     * @type {string}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    id: string;
    /**
     * N/A
     * @type {}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    lastPaymentError?:  | null;
    /**
     * 
     * @type {string}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    latestCharge?: string | null;
    /**
     * N/A
     * @type {boolean}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    livemode: boolean;
    /**
     * N/A
     * @type {object}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    metadata?: object;
    /**
     * N/A
     * @type {}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    nextAction?:  | null;
    /**
     * N/A
     * @type {InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentObjectEnum}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    object: InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentObjectEnum;
    /**
     * 
     * @type {string}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    onBehalfOf?: string | null;
    /**
     * N/A
     * @type {object}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    paymentDetails?: object;
    /**
     * 
     * @type {string}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    paymentMethod?: string | null;
    /**
     * N/A
     * @type {}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    paymentMethodConfigurationDetails?:  | null;
    /**
     * N/A
     * @type {}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    paymentMethodOptions?:  | null;
    /**
     * N/A
     * @type {Array<string>}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    paymentMethodTypes?: Array<string>;
    /**
     * N/A
     * @type {object}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    presentmentDetails?: object;
    /**
     * N/A
     * @type {}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    processing?:  | null;
    /**
     * N/A
     * @type {string}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    receiptEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    review?: string | null;
    /**
     * N/A
     * @type {InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentSetupFutureUsageEnum}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    setupFutureUsage?: InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentSetupFutureUsageEnum;
    /**
     * 
     * @type {Shipping}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    shipping?: Shipping;
    /**
     * N/A
     * @type {string}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    statementDescriptor?: string;
    /**
     * N/A
     * @type {string}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    statementDescriptorSuffix?: string;
    /**
     * N/A
     * @type {InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentStatusEnum}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    status: InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentStatusEnum;
    /**
     * N/A
     * @type {}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    transferData?:  | null;
    /**
     * N/A
     * @type {string}
     * @memberof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent
     */
    transferGroup?: string;
}


/**
 * @export
 */
export const InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentCancellationReasonEnum = {
    Abandoned: 'abandoned',
    Automatic: 'automatic',
    Duplicate: 'duplicate',
    Expired: 'expired',
    FailedInvoice: 'failed_invoice',
    Fraudulent: 'fraudulent',
    RequestedByCustomer: 'requested_by_customer',
    VoidInvoice: 'void_invoice'
} as const;
export type InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentCancellationReasonEnum = typeof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentCancellationReasonEnum[keyof typeof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentCancellationReasonEnum];

/**
 * @export
 */
export const InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentCaptureMethodEnum = {
    Automatic: 'automatic',
    AutomaticAsync: 'automatic_async',
    Manual: 'manual'
} as const;
export type InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentCaptureMethodEnum = typeof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentCaptureMethodEnum[keyof typeof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentCaptureMethodEnum];

/**
 * @export
 */
export const InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentConfirmationMethodEnum = {
    Automatic: 'automatic',
    Manual: 'manual'
} as const;
export type InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentConfirmationMethodEnum = typeof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentConfirmationMethodEnum[keyof typeof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentConfirmationMethodEnum];

/**
 * @export
 */
export const InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentObjectEnum = {
    PaymentIntent: 'payment_intent'
} as const;
export type InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentObjectEnum = typeof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentObjectEnum[keyof typeof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentObjectEnum];

/**
 * @export
 */
export const InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentSetupFutureUsageEnum = {
    OffSession: 'off_session',
    OnSession: 'on_session'
} as const;
export type InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentSetupFutureUsageEnum = typeof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentSetupFutureUsageEnum[keyof typeof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentSetupFutureUsageEnum];

/**
 * @export
 */
export const InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentStatusEnum = {
    Canceled: 'canceled',
    Processing: 'processing',
    RequiresAction: 'requires_action',
    RequiresCapture: 'requires_capture',
    RequiresConfirmation: 'requires_confirmation',
    RequiresPaymentMethod: 'requires_payment_method',
    Succeeded: 'succeeded'
} as const;
export type InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentStatusEnum = typeof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentStatusEnum[keyof typeof InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentStatusEnum];


/**
 * Check if a given object implements the InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent interface.
 */
export function instanceOfInvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent(value: object): value is InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('livemode' in value) || value['livemode'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentFromJSON(json: any): InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent {
    return InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentFromJSONTyped(json, false);
}

export function InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'amountCapturable': json['amount_capturable'] == null ? undefined : json['amount_capturable'],
        'amountDetails': json['amount_details'] == null ? undefined : FromJSON(json['amount_details']),
        'amountReceived': json['amount_received'] == null ? undefined : json['amount_received'],
        'application': json['application'] == null ? undefined : PaymentFlowsSetupIntentSetupAttemptApplicationFromJSON(json['application']),
        'applicationFeeAmount': json['application_fee_amount'] == null ? undefined : json['application_fee_amount'],
        'automaticPaymentMethods': json['automatic_payment_methods'] == null ? undefined : FromJSON(json['automatic_payment_methods']),
        'canceledAt': json['canceled_at'] == null ? undefined : json['canceled_at'],
        'cancellationReason': json['cancellation_reason'] == null ? undefined : json['cancellation_reason'],
        'captureMethod': json['capture_method'] == null ? undefined : json['capture_method'],
        'clientSecret': json['client_secret'] == null ? undefined : json['client_secret'],
        'confirmationMethod': json['confirmation_method'] == null ? undefined : json['confirmation_method'],
        'created': json['created'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'customer': json['customer'] == null ? undefined : CardCustomerFromJSON(json['customer']),
        'customerAccount': json['customer_account'] == null ? undefined : json['customer_account'],
        'excludedPaymentMethodTypes': json['excluded_payment_method_types'] == null ? undefined : json['excluded_payment_method_types'],
        'hooks': json['hooks'] == null ? undefined : json['hooks'],
        'id': json['id'],
        'lastPaymentError': json['last_payment_error'] == null ? undefined : FromJSON(json['last_payment_error']),
        'latestCharge': json['latest_charge'] == null ? undefined : json['latest_charge'],
        'livemode': json['livemode'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'nextAction': json['next_action'] == null ? undefined : FromJSON(json['next_action']),
        'object': json['object'],
        'onBehalfOf': json['on_behalf_of'] == null ? undefined : json['on_behalf_of'],
        'paymentDetails': json['payment_details'] == null ? undefined : json['payment_details'],
        'paymentMethod': json['payment_method'] == null ? undefined : json['payment_method'],
        'paymentMethodConfigurationDetails': json['payment_method_configuration_details'] == null ? undefined : FromJSON(json['payment_method_configuration_details']),
        'paymentMethodOptions': json['payment_method_options'] == null ? undefined : FromJSON(json['payment_method_options']),
        'paymentMethodTypes': json['payment_method_types'] == null ? undefined : json['payment_method_types'],
        'presentmentDetails': json['presentment_details'] == null ? undefined : json['presentment_details'],
        'processing': json['processing'] == null ? undefined : FromJSON(json['processing']),
        'receiptEmail': json['receipt_email'] == null ? undefined : json['receipt_email'],
        'review': json['review'] == null ? undefined : json['review'],
        'setupFutureUsage': json['setup_future_usage'] == null ? undefined : json['setup_future_usage'],
        'shipping': json['shipping'] == null ? undefined : ShippingFromJSON(json['shipping']),
        'statementDescriptor': json['statement_descriptor'] == null ? undefined : json['statement_descriptor'],
        'statementDescriptorSuffix': json['statement_descriptor_suffix'] == null ? undefined : json['statement_descriptor_suffix'],
        'status': json['status'],
        'transferData': json['transfer_data'] == null ? undefined : FromJSON(json['transfer_data']),
        'transferGroup': json['transfer_group'] == null ? undefined : json['transfer_group'],
    };
}

export function InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentToJSON(json: any): InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent {
    return InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentToJSONTyped(json, false);
}

export function InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntentToJSONTyped(value?: InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'amount_capturable': value['amountCapturable'],
        'amount_details': ToJSON(value['amountDetails']),
        'amount_received': value['amountReceived'],
        'application': PaymentFlowsSetupIntentSetupAttemptApplicationToJSON(value['application']),
        'application_fee_amount': value['applicationFeeAmount'],
        'automatic_payment_methods': ToJSON(value['automaticPaymentMethods']),
        'canceled_at': value['canceledAt'],
        'cancellation_reason': value['cancellationReason'],
        'capture_method': value['captureMethod'],
        'client_secret': value['clientSecret'],
        'confirmation_method': value['confirmationMethod'],
        'created': value['created'],
        'currency': value['currency'],
        'customer': CardCustomerToJSON(value['customer']),
        'customer_account': value['customerAccount'],
        'excluded_payment_method_types': value['excludedPaymentMethodTypes'],
        'hooks': value['hooks'],
        'id': value['id'],
        'last_payment_error': ToJSON(value['lastPaymentError']),
        'latest_charge': value['latestCharge'],
        'livemode': value['livemode'],
        'metadata': value['metadata'],
        'next_action': ToJSON(value['nextAction']),
        'object': value['object'],
        'on_behalf_of': value['onBehalfOf'],
        'payment_details': value['paymentDetails'],
        'payment_method': value['paymentMethod'],
        'payment_method_configuration_details': ToJSON(value['paymentMethodConfigurationDetails']),
        'payment_method_options': ToJSON(value['paymentMethodOptions']),
        'payment_method_types': value['paymentMethodTypes'],
        'presentment_details': value['presentmentDetails'],
        'processing': ToJSON(value['processing']),
        'receipt_email': value['receiptEmail'],
        'review': value['review'],
        'setup_future_usage': value['setupFutureUsage'],
        'shipping': ShippingToJSON(value['shipping']),
        'statement_descriptor': value['statementDescriptor'],
        'statement_descriptor_suffix': value['statementDescriptorSuffix'],
        'status': value['status'],
        'transfer_data': ToJSON(value['transferData']),
        'transfer_group': value['transferGroup'],
    };
}

