// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/InvoicesResourceStatusTransitions.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface InvoicesResourceStatusTransitions
 */
export interface InvoicesResourceStatusTransitions {
    /**
     * N/A
     * @type {number}
     * @memberof InvoicesResourceStatusTransitions
     */
    finalizedAt?: number;
    /**
     * N/A
     * @type {number}
     * @memberof InvoicesResourceStatusTransitions
     */
    markedUncollectibleAt?: number;
    /**
     * N/A
     * @type {number}
     * @memberof InvoicesResourceStatusTransitions
     */
    paidAt?: number;
    /**
     * N/A
     * @type {number}
     * @memberof InvoicesResourceStatusTransitions
     */
    voidedAt?: number;
}

/**
 * Check if a given object implements the InvoicesResourceStatusTransitions interface.
 */
export function instanceOfInvoicesResourceStatusTransitions(value: object): value is InvoicesResourceStatusTransitions {
    return true;
}

export function InvoicesResourceStatusTransitionsFromJSON(json: any): InvoicesResourceStatusTransitions {
    return InvoicesResourceStatusTransitionsFromJSONTyped(json, false);
}

export function InvoicesResourceStatusTransitionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoicesResourceStatusTransitions {
    if (json == null) {
        return json;
    }
    return {
        
        'finalizedAt': json['finalized_at'] == null ? undefined : json['finalized_at'],
        'markedUncollectibleAt': json['marked_uncollectible_at'] == null ? undefined : json['marked_uncollectible_at'],
        'paidAt': json['paid_at'] == null ? undefined : json['paid_at'],
        'voidedAt': json['voided_at'] == null ? undefined : json['voided_at'],
    };
}

export function InvoicesResourceStatusTransitionsToJSON(json: any): InvoicesResourceStatusTransitions {
    return InvoicesResourceStatusTransitionsToJSONTyped(json, false);
}

export function InvoicesResourceStatusTransitionsToJSONTyped(value?: InvoicesResourceStatusTransitions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'finalized_at': value['finalizedAt'],
        'marked_uncollectible_at': value['markedUncollectibleAt'],
        'paid_at': value['paidAt'],
        'voided_at': value['voidedAt'],
    };
}

