// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/IssuingNetworkTokenVisa-1.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface IssuingNetworkTokenVisa
 */
export interface IssuingNetworkTokenVisa {
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenVisa
     */
    cardReferenceId: string;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenVisa
     */
    tokenReferenceId: string;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenVisa
     */
    tokenRequestorId: string;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenVisa
     */
    tokenRiskScore?: string;
}

/**
 * Check if a given object implements the IssuingNetworkTokenVisa interface.
 */
export function instanceOfIssuingNetworkTokenVisa(value: object): value is IssuingNetworkTokenVisa {
    if (!('cardReferenceId' in value) || value['cardReferenceId'] === undefined) return false;
    if (!('tokenReferenceId' in value) || value['tokenReferenceId'] === undefined) return false;
    if (!('tokenRequestorId' in value) || value['tokenRequestorId'] === undefined) return false;
    return true;
}

export function IssuingNetworkTokenVisaFromJSON(json: any): IssuingNetworkTokenVisa {
    return IssuingNetworkTokenVisaFromJSONTyped(json, false);
}

export function IssuingNetworkTokenVisaFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuingNetworkTokenVisa {
    if (json == null) {
        return json;
    }
    return {
        
        'cardReferenceId': json['card_reference_id'],
        'tokenReferenceId': json['token_reference_id'],
        'tokenRequestorId': json['token_requestor_id'],
        'tokenRiskScore': json['token_risk_score'] == null ? undefined : json['token_risk_score'],
    };
}

export function IssuingNetworkTokenVisaToJSON(json: any): IssuingNetworkTokenVisa {
    return IssuingNetworkTokenVisaToJSONTyped(json, false);
}

export function IssuingNetworkTokenVisaToJSONTyped(value?: IssuingNetworkTokenVisa | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'card_reference_id': value['cardReferenceId'],
        'token_reference_id': value['tokenReferenceId'],
        'token_requestor_id': value['tokenRequestorId'],
        'token_risk_score': value['tokenRiskScore'],
    };
}



================================================================================
// APPENDED FROM REPO: diplomat-bit/aibankingmtls | ORIGINAL PATH: diplomat-bit-aibankingmtls-6a06a68/models/IssuingNetworkTokenVisa.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface IssuingNetworkTokenVisa
 */
export interface IssuingNetworkTokenVisa {
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenVisa
     */
    cardReferenceId: string;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenVisa
     */
    tokenReferenceId: string;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenVisa
     */
    tokenRequestorId: string;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenVisa
     */
    tokenRiskScore?: string;
}

/**
 * Check if a given object implements the IssuingNetworkTokenVisa interface.
 */
export function instanceOfIssuingNetworkTokenVisa(value: object): value is IssuingNetworkTokenVisa {
    if (!('cardReferenceId' in value) || value['cardReferenceId'] === undefined) return false;
    if (!('tokenReferenceId' in value) || value['tokenReferenceId'] === undefined) return false;
    if (!('tokenRequestorId' in value) || value['tokenRequestorId'] === undefined) return false;
    return true;
}

export function IssuingNetworkTokenVisaFromJSON(json: any): IssuingNetworkTokenVisa {
    return IssuingNetworkTokenVisaFromJSONTyped(json, false);
}

export function IssuingNetworkTokenVisaFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuingNetworkTokenVisa {
    if (json == null) {
        return json;
    }
    return {
        
        'cardReferenceId': json['card_reference_id'],
        'tokenReferenceId': json['token_reference_id'],
        'tokenRequestorId': json['token_requestor_id'],
        'tokenRiskScore': json['token_risk_score'] == null ? undefined : json['token_risk_score'],
    };
}

export function IssuingNetworkTokenVisaToJSON(json: any): IssuingNetworkTokenVisa {
    return IssuingNetworkTokenVisaToJSONTyped(json, false);
}

export function IssuingNetworkTokenVisaToJSONTyped(value?: IssuingNetworkTokenVisa | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'card_reference_id': value['cardReferenceId'],
        'token_reference_id': value['tokenReferenceId'],
        'token_requestor_id': value['tokenRequestorId'],
        'token_risk_score': value['tokenRiskScore'],
    };
}

