// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/IssuingNetworkTokenCard.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IssuingCardShipping } from './IssuingCardShipping';
import {
    IssuingCardShippingFromJSON,
    IssuingCardShippingFromJSONTyped,
    IssuingCardShippingToJSON,
    IssuingCardShippingToJSONTyped,
} from './IssuingCardShipping';
import type { IssuingCardFraudWarning } from './IssuingCardFraudWarning';
import {
    IssuingCardFraudWarningFromJSON,
    IssuingCardFraudWarningFromJSONTyped,
    IssuingCardFraudWarningToJSON,
    IssuingCardFraudWarningToJSONTyped,
} from './IssuingCardFraudWarning';
import type { IssuingCardAuthorizationControls } from './IssuingCardAuthorizationControls';
import {
    IssuingCardAuthorizationControlsFromJSON,
    IssuingCardAuthorizationControlsFromJSONTyped,
    IssuingCardAuthorizationControlsToJSON,
    IssuingCardAuthorizationControlsToJSONTyped,
} from './IssuingCardAuthorizationControls';
import type { IssuingCardPersonalizationDesign } from './IssuingCardPersonalizationDesign';
import {
    IssuingCardPersonalizationDesignFromJSON,
    IssuingCardPersonalizationDesignFromJSONTyped,
    IssuingCardPersonalizationDesignToJSON,
    IssuingCardPersonalizationDesignToJSONTyped,
} from './IssuingCardPersonalizationDesign';
import type { IssuingCard } from './IssuingCard';
import {
    IssuingCardFromJSON,
    IssuingCardFromJSONTyped,
    IssuingCardToJSON,
    IssuingCardToJSONTyped,
} from './IssuingCard';
import type { IssuingCardholder } from './IssuingCardholder';
import {
    IssuingCardholderFromJSON,
    IssuingCardholderFromJSONTyped,
    IssuingCardholderToJSON,
    IssuingCardholderToJSONTyped,
} from './IssuingCardholder';
import type { IssuingCardWallets } from './IssuingCardWallets';
import {
    IssuingCardWalletsFromJSON,
    IssuingCardWalletsFromJSONTyped,
    IssuingCardWalletsToJSON,
    IssuingCardWalletsToJSONTyped,
} from './IssuingCardWallets';

/**
 * N/A
 * @export
 * @interface IssuingNetworkTokenCard
 */
export interface IssuingNetworkTokenCard {
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenCard
     */
    brand: string;
    /**
     * N/A
     * @type {IssuingNetworkTokenCardCancellationReasonEnum}
     * @memberof IssuingNetworkTokenCard
     */
    cancellationReason?: IssuingNetworkTokenCardCancellationReasonEnum;
    /**
     * 
     * @type {IssuingCardholder}
     * @memberof IssuingNetworkTokenCard
     */
    cardholder: IssuingCardholder;
    /**
     * N/A
     * @type {number}
     * @memberof IssuingNetworkTokenCard
     */
    created: number;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenCard
     */
    currency: string;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenCard
     */
    cvc?: string;
    /**
     * N/A
     * @type {number}
     * @memberof IssuingNetworkTokenCard
     */
    expMonth: number;
    /**
     * N/A
     * @type {number}
     * @memberof IssuingNetworkTokenCard
     */
    expYear: number;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenCard
     */
    financialAccount?: string;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenCard
     */
    id: string;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenCard
     */
    last4: string;
    /**
     * 
     * @type {IssuingCardFraudWarning}
     * @memberof IssuingNetworkTokenCard
     */
    latestFraudWarning?: IssuingCardFraudWarning;
    /**
     * N/A
     * @type {boolean}
     * @memberof IssuingNetworkTokenCard
     */
    livemode: boolean;
    /**
     * N/A
     * @type {object}
     * @memberof IssuingNetworkTokenCard
     */
    metadata: object;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenCard
     */
    number?: string;
    /**
     * N/A
     * @type {IssuingNetworkTokenCardObjectEnum}
     * @memberof IssuingNetworkTokenCard
     */
    object: IssuingNetworkTokenCardObjectEnum;
    /**
     * 
     * @type {IssuingCardPersonalizationDesign}
     * @memberof IssuingNetworkTokenCard
     */
    personalizationDesign?: IssuingCardPersonalizationDesign;
    /**
     * 
     * @type {string}
     * @memberof IssuingNetworkTokenCard
     */
    replacedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssuingNetworkTokenCard
     */
    replacementFor?: string | null;
    /**
     * N/A
     * @type {IssuingNetworkTokenCardReplacementReasonEnum}
     * @memberof IssuingNetworkTokenCard
     */
    replacementReason?: IssuingNetworkTokenCardReplacementReasonEnum;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingNetworkTokenCard
     */
    secondLine?: string;
    /**
     * 
     * @type {IssuingCardShipping}
     * @memberof IssuingNetworkTokenCard
     */
    shipping?: IssuingCardShipping;
    /**
     * 
     * @type {IssuingCardAuthorizationControls}
     * @memberof IssuingNetworkTokenCard
     */
    spendingControls: IssuingCardAuthorizationControls;
    /**
     * N/A
     * @type {IssuingNetworkTokenCardStatusEnum}
     * @memberof IssuingNetworkTokenCard
     */
    status: IssuingNetworkTokenCardStatusEnum;
    /**
     * N/A
     * @type {IssuingNetworkTokenCardTypeEnum}
     * @memberof IssuingNetworkTokenCard
     */
    type: IssuingNetworkTokenCardTypeEnum;
    /**
     * 
     * @type {IssuingCardWallets}
     * @memberof IssuingNetworkTokenCard
     */
    wallets?: IssuingCardWallets;
}


/**
 * @export
 */
export const IssuingNetworkTokenCardCancellationReasonEnum = {
    DesignRejected: 'design_rejected',
    Lost: 'lost',
    Stolen: 'stolen'
} as const;
export type IssuingNetworkTokenCardCancellationReasonEnum = typeof IssuingNetworkTokenCardCancellationReasonEnum[keyof typeof IssuingNetworkTokenCardCancellationReasonEnum];

/**
 * @export
 */
export const IssuingNetworkTokenCardObjectEnum = {
    IssuingCard: 'issuing.card'
} as const;
export type IssuingNetworkTokenCardObjectEnum = typeof IssuingNetworkTokenCardObjectEnum[keyof typeof IssuingNetworkTokenCardObjectEnum];

/**
 * @export
 */
export const IssuingNetworkTokenCardReplacementReasonEnum = {
    Damaged: 'damaged',
    Expired: 'expired',
    Lost: 'lost',
    Stolen: 'stolen'
} as const;
export type IssuingNetworkTokenCardReplacementReasonEnum = typeof IssuingNetworkTokenCardReplacementReasonEnum[keyof typeof IssuingNetworkTokenCardReplacementReasonEnum];

/**
 * @export
 */
export const IssuingNetworkTokenCardStatusEnum = {
    Active: 'active',
    Canceled: 'canceled',
    Inactive: 'inactive'
} as const;
export type IssuingNetworkTokenCardStatusEnum = typeof IssuingNetworkTokenCardStatusEnum[keyof typeof IssuingNetworkTokenCardStatusEnum];

/**
 * @export
 */
export const IssuingNetworkTokenCardTypeEnum = {
    Physical: 'physical',
    Virtual: 'virtual'
} as const;
export type IssuingNetworkTokenCardTypeEnum = typeof IssuingNetworkTokenCardTypeEnum[keyof typeof IssuingNetworkTokenCardTypeEnum];


/**
 * Check if a given object implements the IssuingNetworkTokenCard interface.
 */
export function instanceOfIssuingNetworkTokenCard(value: object): value is IssuingNetworkTokenCard {
    if (!('brand' in value) || value['brand'] === undefined) return false;
    if (!('cardholder' in value) || value['cardholder'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('expMonth' in value) || value['expMonth'] === undefined) return false;
    if (!('expYear' in value) || value['expYear'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('last4' in value) || value['last4'] === undefined) return false;
    if (!('livemode' in value) || value['livemode'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('spendingControls' in value) || value['spendingControls'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function IssuingNetworkTokenCardFromJSON(json: any): IssuingNetworkTokenCard {
    return IssuingNetworkTokenCardFromJSONTyped(json, false);
}

export function IssuingNetworkTokenCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuingNetworkTokenCard {
    if (json == null) {
        return json;
    }
    return {
        
        'brand': json['brand'],
        'cancellationReason': json['cancellation_reason'] == null ? undefined : json['cancellation_reason'],
        'cardholder': IssuingCardholderFromJSON(json['cardholder']),
        'created': json['created'],
        'currency': json['currency'],
        'cvc': json['cvc'] == null ? undefined : json['cvc'],
        'expMonth': json['exp_month'],
        'expYear': json['exp_year'],
        'financialAccount': json['financial_account'] == null ? undefined : json['financial_account'],
        'id': json['id'],
        'last4': json['last4'],
        'latestFraudWarning': json['latest_fraud_warning'] == null ? undefined : IssuingCardFraudWarningFromJSON(json['latest_fraud_warning']),
        'livemode': json['livemode'],
        'metadata': json['metadata'],
        'number': json['number'] == null ? undefined : json['number'],
        'object': json['object'],
        'personalizationDesign': json['personalization_design'] == null ? undefined : IssuingCardPersonalizationDesignFromJSON(json['personalization_design']),
        'replacedBy': json['replaced_by'] == null ? undefined : json['replaced_by'],
        'replacementFor': json['replacement_for'] == null ? undefined : json['replacement_for'],
        'replacementReason': json['replacement_reason'] == null ? undefined : json['replacement_reason'],
        'secondLine': json['second_line'] == null ? undefined : json['second_line'],
        'shipping': json['shipping'] == null ? undefined : IssuingCardShippingFromJSON(json['shipping']),
        'spendingControls': IssuingCardAuthorizationControlsFromJSON(json['spending_controls']),
        'status': json['status'],
        'type': json['type'],
        'wallets': json['wallets'] == null ? undefined : IssuingCardWalletsFromJSON(json['wallets']),
    };
}

export function IssuingNetworkTokenCardToJSON(json: any): IssuingNetworkTokenCard {
    return IssuingNetworkTokenCardToJSONTyped(json, false);
}

export function IssuingNetworkTokenCardToJSONTyped(value?: IssuingNetworkTokenCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'brand': value['brand'],
        'cancellation_reason': value['cancellationReason'],
        'cardholder': IssuingCardholderToJSON(value['cardholder']),
        'created': value['created'],
        'currency': value['currency'],
        'cvc': value['cvc'],
        'exp_month': value['expMonth'],
        'exp_year': value['expYear'],
        'financial_account': value['financialAccount'],
        'id': value['id'],
        'last4': value['last4'],
        'latest_fraud_warning': IssuingCardFraudWarningToJSON(value['latestFraudWarning']),
        'livemode': value['livemode'],
        'metadata': value['metadata'],
        'number': value['number'],
        'object': value['object'],
        'personalization_design': IssuingCardPersonalizationDesignToJSON(value['personalizationDesign']),
        'replaced_by': value['replacedBy'],
        'replacement_for': value['replacementFor'],
        'replacement_reason': value['replacementReason'],
        'second_line': value['secondLine'],
        'shipping': IssuingCardShippingToJSON(value['shipping']),
        'spending_controls': IssuingCardAuthorizationControlsToJSON(value['spendingControls']),
        'status': value['status'],
        'type': value['type'],
        'wallets': IssuingCardWalletsToJSON(value['wallets']),
    };
}

