// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/IssuingTransactionTreasury.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface IssuingTransactionTreasury
 */
export interface IssuingTransactionTreasury {
    /**
     * N/A
     * @type {string}
     * @memberof IssuingTransactionTreasury
     */
    receivedCredit?: string;
    /**
     * N/A
     * @type {string}
     * @memberof IssuingTransactionTreasury
     */
    receivedDebit?: string;
}

/**
 * Check if a given object implements the IssuingTransactionTreasury interface.
 */
export function instanceOfIssuingTransactionTreasury(value: object): value is IssuingTransactionTreasury {
    return true;
}

export function IssuingTransactionTreasuryFromJSON(json: any): IssuingTransactionTreasury {
    return IssuingTransactionTreasuryFromJSONTyped(json, false);
}

export function IssuingTransactionTreasuryFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuingTransactionTreasury {
    if (json == null) {
        return json;
    }
    return {
        
        'receivedCredit': json['received_credit'] == null ? undefined : json['received_credit'],
        'receivedDebit': json['received_debit'] == null ? undefined : json['received_debit'],
    };
}

export function IssuingTransactionTreasuryToJSON(json: any): IssuingTransactionTreasury {
    return IssuingTransactionTreasuryToJSONTyped(json, false);
}

export function IssuingTransactionTreasuryToJSONTyped(value?: IssuingTransactionTreasury | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'received_credit': value['receivedCredit'],
        'received_debit': value['receivedDebit'],
    };
}

