// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/LegalEntityCompanyVerificationDocument1-1.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface LegalEntityCompanyVerificationDocument1
 */
export interface LegalEntityCompanyVerificationDocument1 {
    /**
     * 
     * @type {string}
     * @memberof LegalEntityCompanyVerificationDocument1
     */
    back?: string;
    /**
     * N/A
     * @type {string}
     * @memberof LegalEntityCompanyVerificationDocument1
     */
    details?: string;
    /**
     * N/A
     * @type {string}
     * @memberof LegalEntityCompanyVerificationDocument1
     */
    detailsCode?: string;
    /**
     * 
     * @type {string}
     * @memberof LegalEntityCompanyVerificationDocument1
     */
    front?: string;
}

/**
 * Check if a given object implements the LegalEntityCompanyVerificationDocument1 interface.
 */
export function instanceOfLegalEntityCompanyVerificationDocument1(value: object): value is LegalEntityCompanyVerificationDocument1 {
    return true;
}

export function LegalEntityCompanyVerificationDocument1FromJSON(json: any): LegalEntityCompanyVerificationDocument1 {
    return LegalEntityCompanyVerificationDocument1FromJSONTyped(json, false);
}

export function LegalEntityCompanyVerificationDocument1FromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalEntityCompanyVerificationDocument1 {
    if (json == null) {
        return json;
    }
    return {
        
        'back': json['back'] == null ? undefined : json['back'],
        'details': json['details'] == null ? undefined : json['details'],
        'detailsCode': json['details_code'] == null ? undefined : json['details_code'],
        'front': json['front'] == null ? undefined : json['front'],
    };
}

export function LegalEntityCompanyVerificationDocument1ToJSON(json: any): LegalEntityCompanyVerificationDocument1 {
    return LegalEntityCompanyVerificationDocument1ToJSONTyped(json, false);
}

export function LegalEntityCompanyVerificationDocument1ToJSONTyped(value?: LegalEntityCompanyVerificationDocument1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'back': value['back'],
        'details': value['details'],
        'details_code': value['detailsCode'],
        'front': value['front'],
    };
}

