// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/PaymentMethod.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentMethodNaverPay } from './PaymentMethodNaverPay';
import {
    PaymentMethodNaverPayFromJSON,
    PaymentMethodNaverPayFromJSONTyped,
    PaymentMethodNaverPayToJSON,
    PaymentMethodNaverPayToJSONTyped,
} from './PaymentMethodNaverPay';
import type { PaymentMethodCashapp } from './PaymentMethodCashapp';
import {
    PaymentMethodCashappFromJSON,
    PaymentMethodCashappFromJSONTyped,
    PaymentMethodCashappToJSON,
    PaymentMethodCashappToJSONTyped,
} from './PaymentMethodCashapp';
import type { PaymentMethodKrCard } from './PaymentMethodKrCard';
import {
    PaymentMethodKrCardFromJSON,
    PaymentMethodKrCardFromJSONTyped,
    PaymentMethodKrCardToJSON,
    PaymentMethodKrCardToJSONTyped,
} from './PaymentMethodKrCard';
import type { RadarRadarOptions } from './RadarRadarOptions';
import {
    RadarRadarOptionsFromJSON,
    RadarRadarOptionsFromJSONTyped,
    RadarRadarOptionsToJSON,
    RadarRadarOptionsToJSONTyped,
} from './RadarRadarOptions';
import type { PaymentMethodSepaDebit } from './PaymentMethodSepaDebit';
import {
    PaymentMethodSepaDebitFromJSON,
    PaymentMethodSepaDebitFromJSONTyped,
    PaymentMethodSepaDebitToJSON,
    PaymentMethodSepaDebitToJSONTyped,
} from './PaymentMethodSepaDebit';
import type { PaymentMethodAuBecsDebit } from './PaymentMethodAuBecsDebit';
import {
    PaymentMethodAuBecsDebitFromJSON,
    PaymentMethodAuBecsDebitFromJSONTyped,
    PaymentMethodAuBecsDebitToJSON,
    PaymentMethodAuBecsDebitToJSONTyped,
} from './PaymentMethodAuBecsDebit';
import type { PaymentMethodCustom } from './PaymentMethodCustom';
import {
    PaymentMethodCustomFromJSON,
    PaymentMethodCustomFromJSONTyped,
    PaymentMethodCustomToJSON,
    PaymentMethodCustomToJSONTyped,
} from './PaymentMethodCustom';
import type { PaymentMethodSofort } from './PaymentMethodSofort';
import {
    PaymentMethodSofortFromJSON,
    PaymentMethodSofortFromJSONTyped,
    PaymentMethodSofortToJSON,
    PaymentMethodSofortToJSONTyped,
} from './PaymentMethodSofort';
import type { PaymentMethodCard } from './PaymentMethodCard';
import {
    PaymentMethodCardFromJSON,
    PaymentMethodCardFromJSONTyped,
    PaymentMethodCardToJSON,
    PaymentMethodCardToJSONTyped,
} from './PaymentMethodCard';
import type { PaymentMethodInteracPresent } from './PaymentMethodInteracPresent';
import {
    PaymentMethodInteracPresentFromJSON,
    PaymentMethodInteracPresentFromJSONTyped,
    PaymentMethodInteracPresentToJSON,
    PaymentMethodInteracPresentToJSONTyped,
} from './PaymentMethodInteracPresent';
import type { PaymentMethodPayto } from './PaymentMethodPayto';
import {
    PaymentMethodPaytoFromJSON,
    PaymentMethodPaytoFromJSONTyped,
    PaymentMethodPaytoToJSON,
    PaymentMethodPaytoToJSONTyped,
} from './PaymentMethodPayto';
import type { PaymentMethodKlarna } from './PaymentMethodKlarna';
import {
    PaymentMethodKlarnaFromJSON,
    PaymentMethodKlarnaFromJSONTyped,
    PaymentMethodKlarnaToJSON,
    PaymentMethodKlarnaToJSONTyped,
} from './PaymentMethodKlarna';
import type { PaymentMethodLink } from './PaymentMethodLink';
import {
    PaymentMethodLinkFromJSON,
    PaymentMethodLinkFromJSONTyped,
    PaymentMethodLinkToJSON,
    PaymentMethodLinkToJSONTyped,
} from './PaymentMethodLink';
import type { PaymentMethodNzBankAccount } from './PaymentMethodNzBankAccount';
import {
    PaymentMethodNzBankAccountFromJSON,
    PaymentMethodNzBankAccountFromJSONTyped,
    PaymentMethodNzBankAccountToJSON,
    PaymentMethodNzBankAccountToJSONTyped,
} from './PaymentMethodNzBankAccount';
import type { PaymentMethodIdeal } from './PaymentMethodIdeal';
import {
    PaymentMethodIdealFromJSON,
    PaymentMethodIdealFromJSONTyped,
    PaymentMethodIdealToJSON,
    PaymentMethodIdealToJSONTyped,
} from './PaymentMethodIdeal';
import type { PaymentMethodCardPresent } from './PaymentMethodCardPresent';
import {
    PaymentMethodCardPresentFromJSON,
    PaymentMethodCardPresentFromJSONTyped,
    PaymentMethodCardPresentToJSON,
    PaymentMethodCardPresentToJSONTyped,
} from './PaymentMethodCardPresent';
import type { BillingDetails } from './BillingDetails';
import {
    BillingDetailsFromJSON,
    BillingDetailsFromJSONTyped,
    BillingDetailsToJSON,
    BillingDetailsToJSONTyped,
} from './BillingDetails';
import type { PaymentMethodBacsDebit } from './PaymentMethodBacsDebit';
import {
    PaymentMethodBacsDebitFromJSON,
    PaymentMethodBacsDebitFromJSONTyped,
    PaymentMethodBacsDebitToJSON,
    PaymentMethodBacsDebitToJSONTyped,
} from './PaymentMethodBacsDebit';
import type { PaymentMethodBoleto } from './PaymentMethodBoleto';
import {
    PaymentMethodBoletoFromJSON,
    PaymentMethodBoletoFromJSONTyped,
    PaymentMethodBoletoToJSON,
    PaymentMethodBoletoToJSONTyped,
} from './PaymentMethodBoleto';
import type { PaymentMethodP24 } from './PaymentMethodP24';
import {
    PaymentMethodP24FromJSON,
    PaymentMethodP24FromJSONTyped,
    PaymentMethodP24ToJSON,
    PaymentMethodP24ToJSONTyped,
} from './PaymentMethodP24';
import type { PaymentMethodPaypal } from './PaymentMethodPaypal';
import {
    PaymentMethodPaypalFromJSON,
    PaymentMethodPaypalFromJSONTyped,
    PaymentMethodPaypalToJSON,
    PaymentMethodPaypalToJSONTyped,
} from './PaymentMethodPaypal';
import type { PaymentMethodUsBankAccount } from './PaymentMethodUsBankAccount';
import {
    PaymentMethodUsBankAccountFromJSON,
    PaymentMethodUsBankAccountFromJSONTyped,
    PaymentMethodUsBankAccountToJSON,
    PaymentMethodUsBankAccountToJSONTyped,
} from './PaymentMethodUsBankAccount';
import type { PaymentMethodEps } from './PaymentMethodEps';
import {
    PaymentMethodEpsFromJSON,
    PaymentMethodEpsFromJSONTyped,
    PaymentMethodEpsToJSON,
    PaymentMethodEpsToJSONTyped,
} from './PaymentMethodEps';
import type { PaymentMethodFpx } from './PaymentMethodFpx';
import {
    PaymentMethodFpxFromJSON,
    PaymentMethodFpxFromJSONTyped,
    PaymentMethodFpxToJSON,
    PaymentMethodFpxToJSONTyped,
} from './PaymentMethodFpx';
import type { PaymentMethodAcssDebit } from './PaymentMethodAcssDebit';
import {
    PaymentMethodAcssDebitFromJSON,
    PaymentMethodAcssDebitFromJSONTyped,
    PaymentMethodAcssDebitToJSON,
    PaymentMethodAcssDebitToJSONTyped,
} from './PaymentMethodAcssDebit';

/**
 * N/A
 * @export
 * @interface PaymentMethod
 */
export interface PaymentMethod {
    /**
     * 
     * @type {PaymentMethodAcssDebit}
     * @memberof PaymentMethod
     */
    acssDebit?: PaymentMethodAcssDebit;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    affirm?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    afterpayClearpay?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    alipay?: object;
    /**
     * N/A
     * @type {PaymentMethodAllowRedisplayEnum}
     * @memberof PaymentMethod
     */
    allowRedisplay?: PaymentMethodAllowRedisplayEnum;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    alma?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    amazonPay?: object;
    /**
     * 
     * @type {PaymentMethodAuBecsDebit}
     * @memberof PaymentMethod
     */
    auBecsDebit?: PaymentMethodAuBecsDebit;
    /**
     * 
     * @type {PaymentMethodBacsDebit}
     * @memberof PaymentMethod
     */
    bacsDebit?: PaymentMethodBacsDebit;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    bancontact?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    billie?: object;
    /**
     * 
     * @type {BillingDetails}
     * @memberof PaymentMethod
     */
    billingDetails: BillingDetails;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    blik?: object;
    /**
     * 
     * @type {PaymentMethodBoleto}
     * @memberof PaymentMethod
     */
    boleto?: PaymentMethodBoleto;
    /**
     * 
     * @type {PaymentMethodCard}
     * @memberof PaymentMethod
     */
    card?: PaymentMethodCard;
    /**
     * 
     * @type {PaymentMethodCardPresent}
     * @memberof PaymentMethod
     */
    cardPresent?: PaymentMethodCardPresent;
    /**
     * 
     * @type {PaymentMethodCashapp}
     * @memberof PaymentMethod
     */
    cashapp?: PaymentMethodCashapp;
    /**
     * N/A
     * @type {number}
     * @memberof PaymentMethod
     */
    created: number;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    crypto?: object;
    /**
     * 
     * @type {PaymentMethodCustom}
     * @memberof PaymentMethod
     */
    custom?: PaymentMethodCustom;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    customer?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    customerAccount?: string;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    customerBalance?: object;
    /**
     * 
     * @type {PaymentMethodEps}
     * @memberof PaymentMethod
     */
    eps?: PaymentMethodEps;
    /**
     * 
     * @type {PaymentMethodFpx}
     * @memberof PaymentMethod
     */
    fpx?: PaymentMethodFpx;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    giropay?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    grabpay?: object;
    /**
     * N/A
     * @type {string}
     * @memberof PaymentMethod
     */
    id: string;
    /**
     * 
     * @type {PaymentMethodIdeal}
     * @memberof PaymentMethod
     */
    ideal?: PaymentMethodIdeal;
    /**
     * 
     * @type {PaymentMethodInteracPresent}
     * @memberof PaymentMethod
     */
    interacPresent?: PaymentMethodInteracPresent;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    kakaoPay?: object;
    /**
     * 
     * @type {PaymentMethodKlarna}
     * @memberof PaymentMethod
     */
    klarna?: PaymentMethodKlarna;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    konbini?: object;
    /**
     * 
     * @type {PaymentMethodKrCard}
     * @memberof PaymentMethod
     */
    krCard?: PaymentMethodKrCard;
    /**
     * 
     * @type {PaymentMethodLink}
     * @memberof PaymentMethod
     */
    link?: PaymentMethodLink;
    /**
     * N/A
     * @type {boolean}
     * @memberof PaymentMethod
     */
    livemode: boolean;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    mbWay?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    metadata?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    mobilepay?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    multibanco?: object;
    /**
     * 
     * @type {PaymentMethodNaverPay}
     * @memberof PaymentMethod
     */
    naverPay?: PaymentMethodNaverPay;
    /**
     * 
     * @type {PaymentMethodNzBankAccount}
     * @memberof PaymentMethod
     */
    nzBankAccount?: PaymentMethodNzBankAccount;
    /**
     * N/A
     * @type {PaymentMethodObjectEnum}
     * @memberof PaymentMethod
     */
    object: PaymentMethodObjectEnum;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    oxxo?: object;
    /**
     * 
     * @type {PaymentMethodP24}
     * @memberof PaymentMethod
     */
    p24?: PaymentMethodP24;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    payByBank?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    payco?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    paynow?: object;
    /**
     * 
     * @type {PaymentMethodPaypal}
     * @memberof PaymentMethod
     */
    paypal?: PaymentMethodPaypal;
    /**
     * 
     * @type {PaymentMethodPayto}
     * @memberof PaymentMethod
     */
    payto?: PaymentMethodPayto;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    pix?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    promptpay?: object;
    /**
     * 
     * @type {RadarRadarOptions}
     * @memberof PaymentMethod
     */
    radarOptions?: RadarRadarOptions;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    revolutPay?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    samsungPay?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    satispay?: object;
    /**
     * 
     * @type {PaymentMethodSepaDebit}
     * @memberof PaymentMethod
     */
    sepaDebit?: PaymentMethodSepaDebit;
    /**
     * 
     * @type {PaymentMethodSofort}
     * @memberof PaymentMethod
     */
    sofort?: PaymentMethodSofort;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    swish?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    twint?: object;
    /**
     * N/A
     * @type {PaymentMethodTypeEnum}
     * @memberof PaymentMethod
     */
    type: PaymentMethodTypeEnum;
    /**
     * 
     * @type {PaymentMethodUsBankAccount}
     * @memberof PaymentMethod
     */
    usBankAccount?: PaymentMethodUsBankAccount;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    wechatPay?: object;
    /**
     * N/A
     * @type {object}
     * @memberof PaymentMethod
     */
    zip?: object;
}


/**
 * @export
 */
export const PaymentMethodAllowRedisplayEnum = {
    Always: 'always',
    Limited: 'limited',
    Unspecified: 'unspecified'
} as const;
export type PaymentMethodAllowRedisplayEnum = typeof PaymentMethodAllowRedisplayEnum[keyof typeof PaymentMethodAllowRedisplayEnum];

/**
 * @export
 */
export const PaymentMethodObjectEnum = {
    PaymentMethod: 'payment_method'
} as const;
export type PaymentMethodObjectEnum = typeof PaymentMethodObjectEnum[keyof typeof PaymentMethodObjectEnum];

/**
 * @export
 */
export const PaymentMethodTypeEnum = {
    AcssDebit: 'acss_debit',
    Affirm: 'affirm',
    AfterpayClearpay: 'afterpay_clearpay',
    Alipay: 'alipay',
    Alma: 'alma',
    AmazonPay: 'amazon_pay',
    AuBecsDebit: 'au_becs_debit',
    BacsDebit: 'bacs_debit',
    Bancontact: 'bancontact',
    Billie: 'billie',
    Blik: 'blik',
    Boleto: 'boleto',
    Card: 'card',
    CardPresent: 'card_present',
    Cashapp: 'cashapp',
    Crypto: 'crypto',
    Custom: 'custom',
    CustomerBalance: 'customer_balance',
    Eps: 'eps',
    Fpx: 'fpx',
    Giropay: 'giropay',
    Grabpay: 'grabpay',
    Ideal: 'ideal',
    InteracPresent: 'interac_present',
    KakaoPay: 'kakao_pay',
    Klarna: 'klarna',
    Konbini: 'konbini',
    KrCard: 'kr_card',
    Link: 'link',
    MbWay: 'mb_way',
    Mobilepay: 'mobilepay',
    Multibanco: 'multibanco',
    NaverPay: 'naver_pay',
    NzBankAccount: 'nz_bank_account',
    Oxxo: 'oxxo',
    P24: 'p24',
    PayByBank: 'pay_by_bank',
    Payco: 'payco',
    Paynow: 'paynow',
    Paypal: 'paypal',
    Payto: 'payto',
    Pix: 'pix',
    Promptpay: 'promptpay',
    RevolutPay: 'revolut_pay',
    SamsungPay: 'samsung_pay',
    Satispay: 'satispay',
    SepaDebit: 'sepa_debit',
    Sofort: 'sofort',
    Swish: 'swish',
    Twint: 'twint',
    UsBankAccount: 'us_bank_account',
    WechatPay: 'wechat_pay',
    Zip: 'zip'
} as const;
export type PaymentMethodTypeEnum = typeof PaymentMethodTypeEnum[keyof typeof PaymentMethodTypeEnum];


/**
 * Check if a given object implements the PaymentMethod interface.
 */
export function instanceOfPaymentMethod(value: object): value is PaymentMethod {
    if (!('billingDetails' in value) || value['billingDetails'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('livemode' in value) || value['livemode'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PaymentMethodFromJSON(json: any): PaymentMethod {
    return PaymentMethodFromJSONTyped(json, false);
}

export function PaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'acssDebit': json['acss_debit'] == null ? undefined : PaymentMethodAcssDebitFromJSON(json['acss_debit']),
        'affirm': json['affirm'] == null ? undefined : json['affirm'],
        'afterpayClearpay': json['afterpay_clearpay'] == null ? undefined : json['afterpay_clearpay'],
        'alipay': json['alipay'] == null ? undefined : json['alipay'],
        'allowRedisplay': json['allow_redisplay'] == null ? undefined : json['allow_redisplay'],
        'alma': json['alma'] == null ? undefined : json['alma'],
        'amazonPay': json['amazon_pay'] == null ? undefined : json['amazon_pay'],
        'auBecsDebit': json['au_becs_debit'] == null ? undefined : PaymentMethodAuBecsDebitFromJSON(json['au_becs_debit']),
        'bacsDebit': json['bacs_debit'] == null ? undefined : PaymentMethodBacsDebitFromJSON(json['bacs_debit']),
        'bancontact': json['bancontact'] == null ? undefined : json['bancontact'],
        'billie': json['billie'] == null ? undefined : json['billie'],
        'billingDetails': BillingDetailsFromJSON(json['billing_details']),
        'blik': json['blik'] == null ? undefined : json['blik'],
        'boleto': json['boleto'] == null ? undefined : PaymentMethodBoletoFromJSON(json['boleto']),
        'card': json['card'] == null ? undefined : PaymentMethodCardFromJSON(json['card']),
        'cardPresent': json['card_present'] == null ? undefined : PaymentMethodCardPresentFromJSON(json['card_present']),
        'cashapp': json['cashapp'] == null ? undefined : PaymentMethodCashappFromJSON(json['cashapp']),
        'created': json['created'],
        'crypto': json['crypto'] == null ? undefined : json['crypto'],
        'custom': json['custom'] == null ? undefined : PaymentMethodCustomFromJSON(json['custom']),
        'customer': json['customer'] == null ? undefined : json['customer'],
        'customerAccount': json['customer_account'] == null ? undefined : json['customer_account'],
        'customerBalance': json['customer_balance'] == null ? undefined : json['customer_balance'],
        'eps': json['eps'] == null ? undefined : PaymentMethodEpsFromJSON(json['eps']),
        'fpx': json['fpx'] == null ? undefined : PaymentMethodFpxFromJSON(json['fpx']),
        'giropay': json['giropay'] == null ? undefined : json['giropay'],
        'grabpay': json['grabpay'] == null ? undefined : json['grabpay'],
        'id': json['id'],
        'ideal': json['ideal'] == null ? undefined : PaymentMethodIdealFromJSON(json['ideal']),
        'interacPresent': json['interac_present'] == null ? undefined : PaymentMethodInteracPresentFromJSON(json['interac_present']),
        'kakaoPay': json['kakao_pay'] == null ? undefined : json['kakao_pay'],
        'klarna': json['klarna'] == null ? undefined : PaymentMethodKlarnaFromJSON(json['klarna']),
        'konbini': json['konbini'] == null ? undefined : json['konbini'],
        'krCard': json['kr_card'] == null ? undefined : PaymentMethodKrCardFromJSON(json['kr_card']),
        'link': json['link'] == null ? undefined : PaymentMethodLinkFromJSON(json['link']),
        'livemode': json['livemode'],
        'mbWay': json['mb_way'] == null ? undefined : json['mb_way'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'mobilepay': json['mobilepay'] == null ? undefined : json['mobilepay'],
        'multibanco': json['multibanco'] == null ? undefined : json['multibanco'],
        'naverPay': json['naver_pay'] == null ? undefined : PaymentMethodNaverPayFromJSON(json['naver_pay']),
        'nzBankAccount': json['nz_bank_account'] == null ? undefined : PaymentMethodNzBankAccountFromJSON(json['nz_bank_account']),
        'object': json['object'],
        'oxxo': json['oxxo'] == null ? undefined : json['oxxo'],
        'p24': json['p24'] == null ? undefined : PaymentMethodP24FromJSON(json['p24']),
        'payByBank': json['pay_by_bank'] == null ? undefined : json['pay_by_bank'],
        'payco': json['payco'] == null ? undefined : json['payco'],
        'paynow': json['paynow'] == null ? undefined : json['paynow'],
        'paypal': json['paypal'] == null ? undefined : PaymentMethodPaypalFromJSON(json['paypal']),
        'payto': json['payto'] == null ? undefined : PaymentMethodPaytoFromJSON(json['payto']),
        'pix': json['pix'] == null ? undefined : json['pix'],
        'promptpay': json['promptpay'] == null ? undefined : json['promptpay'],
        'radarOptions': json['radar_options'] == null ? undefined : RadarRadarOptionsFromJSON(json['radar_options']),
        'revolutPay': json['revolut_pay'] == null ? undefined : json['revolut_pay'],
        'samsungPay': json['samsung_pay'] == null ? undefined : json['samsung_pay'],
        'satispay': json['satispay'] == null ? undefined : json['satispay'],
        'sepaDebit': json['sepa_debit'] == null ? undefined : PaymentMethodSepaDebitFromJSON(json['sepa_debit']),
        'sofort': json['sofort'] == null ? undefined : PaymentMethodSofortFromJSON(json['sofort']),
        'swish': json['swish'] == null ? undefined : json['swish'],
        'twint': json['twint'] == null ? undefined : json['twint'],
        'type': json['type'],
        'usBankAccount': json['us_bank_account'] == null ? undefined : PaymentMethodUsBankAccountFromJSON(json['us_bank_account']),
        'wechatPay': json['wechat_pay'] == null ? undefined : json['wechat_pay'],
        'zip': json['zip'] == null ? undefined : json['zip'],
    };
}

export function PaymentMethodToJSON(json: any): PaymentMethod {
    return PaymentMethodToJSONTyped(json, false);
}

export function PaymentMethodToJSONTyped(value?: PaymentMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acss_debit': PaymentMethodAcssDebitToJSON(value['acssDebit']),
        'affirm': value['affirm'],
        'afterpay_clearpay': value['afterpayClearpay'],
        'alipay': value['alipay'],
        'allow_redisplay': value['allowRedisplay'],
        'alma': value['alma'],
        'amazon_pay': value['amazonPay'],
        'au_becs_debit': PaymentMethodAuBecsDebitToJSON(value['auBecsDebit']),
        'bacs_debit': PaymentMethodBacsDebitToJSON(value['bacsDebit']),
        'bancontact': value['bancontact'],
        'billie': value['billie'],
        'billing_details': BillingDetailsToJSON(value['billingDetails']),
        'blik': value['blik'],
        'boleto': PaymentMethodBoletoToJSON(value['boleto']),
        'card': PaymentMethodCardToJSON(value['card']),
        'card_present': PaymentMethodCardPresentToJSON(value['cardPresent']),
        'cashapp': PaymentMethodCashappToJSON(value['cashapp']),
        'created': value['created'],
        'crypto': value['crypto'],
        'custom': PaymentMethodCustomToJSON(value['custom']),
        'customer': value['customer'],
        'customer_account': value['customerAccount'],
        'customer_balance': value['customerBalance'],
        'eps': PaymentMethodEpsToJSON(value['eps']),
        'fpx': PaymentMethodFpxToJSON(value['fpx']),
        'giropay': value['giropay'],
        'grabpay': value['grabpay'],
        'id': value['id'],
        'ideal': PaymentMethodIdealToJSON(value['ideal']),
        'interac_present': PaymentMethodInteracPresentToJSON(value['interacPresent']),
        'kakao_pay': value['kakaoPay'],
        'klarna': PaymentMethodKlarnaToJSON(value['klarna']),
        'konbini': value['konbini'],
        'kr_card': PaymentMethodKrCardToJSON(value['krCard']),
        'link': PaymentMethodLinkToJSON(value['link']),
        'livemode': value['livemode'],
        'mb_way': value['mbWay'],
        'metadata': value['metadata'],
        'mobilepay': value['mobilepay'],
        'multibanco': value['multibanco'],
        'naver_pay': PaymentMethodNaverPayToJSON(value['naverPay']),
        'nz_bank_account': PaymentMethodNzBankAccountToJSON(value['nzBankAccount']),
        'object': value['object'],
        'oxxo': value['oxxo'],
        'p24': PaymentMethodP24ToJSON(value['p24']),
        'pay_by_bank': value['payByBank'],
        'payco': value['payco'],
        'paynow': value['paynow'],
        'paypal': PaymentMethodPaypalToJSON(value['paypal']),
        'payto': PaymentMethodPaytoToJSON(value['payto']),
        'pix': value['pix'],
        'promptpay': value['promptpay'],
        'radar_options': RadarRadarOptionsToJSON(value['radarOptions']),
        'revolut_pay': value['revolutPay'],
        'samsung_pay': value['samsungPay'],
        'satispay': value['satispay'],
        'sepa_debit': PaymentMethodSepaDebitToJSON(value['sepaDebit']),
        'sofort': PaymentMethodSofortToJSON(value['sofort']),
        'swish': value['swish'],
        'twint': value['twint'],
        'type': value['type'],
        'us_bank_account': PaymentMethodUsBankAccountToJSON(value['usBankAccount']),
        'wechat_pay': value['wechatPay'],
        'zip': value['zip'],
    };
}

