// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/RefundDestinationDetailsPaypal.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface RefundDestinationDetailsPaypal
 */
export interface RefundDestinationDetailsPaypal {
    /**
     * N/A
     * @type {string}
     * @memberof RefundDestinationDetailsPaypal
     */
    networkDeclineCode?: string;
}

/**
 * Check if a given object implements the RefundDestinationDetailsPaypal interface.
 */
export function instanceOfRefundDestinationDetailsPaypal(value: object): value is RefundDestinationDetailsPaypal {
    return true;
}

export function RefundDestinationDetailsPaypalFromJSON(json: any): RefundDestinationDetailsPaypal {
    return RefundDestinationDetailsPaypalFromJSONTyped(json, false);
}

export function RefundDestinationDetailsPaypalFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundDestinationDetailsPaypal {
    if (json == null) {
        return json;
    }
    return {
        
        'networkDeclineCode': json['network_decline_code'] == null ? undefined : json['network_decline_code'],
    };
}

export function RefundDestinationDetailsPaypalToJSON(json: any): RefundDestinationDetailsPaypal {
    return RefundDestinationDetailsPaypalToJSONTyped(json, false);
}

export function RefundDestinationDetailsPaypalToJSONTyped(value?: RefundDestinationDetailsPaypal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network_decline_code': value['networkDeclineCode'],
    };
}

