// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/SetupAttemptPaymentMethodDetailsNaverPay.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface SetupAttemptPaymentMethodDetailsNaverPay
 */
export interface SetupAttemptPaymentMethodDetailsNaverPay {
    /**
     * N/A
     * @type {string}
     * @memberof SetupAttemptPaymentMethodDetailsNaverPay
     */
    buyerId?: string;
}

/**
 * Check if a given object implements the SetupAttemptPaymentMethodDetailsNaverPay interface.
 */
export function instanceOfSetupAttemptPaymentMethodDetailsNaverPay(value: object): value is SetupAttemptPaymentMethodDetailsNaverPay {
    return true;
}

export function SetupAttemptPaymentMethodDetailsNaverPayFromJSON(json: any): SetupAttemptPaymentMethodDetailsNaverPay {
    return SetupAttemptPaymentMethodDetailsNaverPayFromJSONTyped(json, false);
}

export function SetupAttemptPaymentMethodDetailsNaverPayFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupAttemptPaymentMethodDetailsNaverPay {
    if (json == null) {
        return json;
    }
    return {
        
        'buyerId': json['buyer_id'] == null ? undefined : json['buyer_id'],
    };
}

export function SetupAttemptPaymentMethodDetailsNaverPayToJSON(json: any): SetupAttemptPaymentMethodDetailsNaverPay {
    return SetupAttemptPaymentMethodDetailsNaverPayToJSONTyped(json, false);
}

export function SetupAttemptPaymentMethodDetailsNaverPayToJSONTyped(value?: SetupAttemptPaymentMethodDetailsNaverPay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'buyer_id': value['buyerId'],
    };
}

