// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/SourceCodeVerificationFlow.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * N/A
 * @export
 * @interface SourceCodeVerificationFlow
 */
export interface SourceCodeVerificationFlow {
    /**
     * N/A
     * @type {number}
     * @memberof SourceCodeVerificationFlow
     */
    attemptsRemaining: number;
    /**
     * N/A
     * @type {string}
     * @memberof SourceCodeVerificationFlow
     */
    status: string;
}

/**
 * Check if a given object implements the SourceCodeVerificationFlow interface.
 */
export function instanceOfSourceCodeVerificationFlow(value: object): value is SourceCodeVerificationFlow {
    if (!('attemptsRemaining' in value) || value['attemptsRemaining'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SourceCodeVerificationFlowFromJSON(json: any): SourceCodeVerificationFlow {
    return SourceCodeVerificationFlowFromJSONTyped(json, false);
}

export function SourceCodeVerificationFlowFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceCodeVerificationFlow {
    if (json == null) {
        return json;
    }
    return {
        
        'attemptsRemaining': json['attempts_remaining'],
        'status': json['status'],
    };
}

export function SourceCodeVerificationFlowToJSON(json: any): SourceCodeVerificationFlow {
    return SourceCodeVerificationFlowToJSONTyped(json, false);
}

export function SourceCodeVerificationFlowToJSONTyped(value?: SourceCodeVerificationFlow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attempts_remaining': value['attemptsRemaining'],
        'status': value['status'],
    };
}

