// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCard.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardMandateOptions } from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardMandateOptions';
import {
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardMandateOptionsFromJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardMandateOptionsFromJSONTyped,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardMandateOptionsToJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardMandateOptionsToJSONTyped,
} from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardMandateOptions';

/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCard
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCard {
    /**
     * 
     * @type {V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardMandateOptions}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCard
     */
    mandateOptions?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardMandateOptions;
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCard
     */
    network?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCard
     */
    requestThreeDSecure?: string;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCard interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCard(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCard {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCard {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCard {
    if (json == null) {
        return json;
    }
    return {
        
        'mandateOptions': json['mandate_options'] == null ? undefined : V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardMandateOptionsFromJSON(json['mandate_options']),
        'network': json['network'] == null ? undefined : json['network'],
        'requestThreeDSecure': json['request_three_d_secure'] == null ? undefined : json['request_three_d_secure'],
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCard {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mandate_options': V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsCardMandateOptionsToJSON(value['mandateOptions']),
        'network': value['network'],
        'request_three_d_secure': value['requestThreeDSecure'],
    };
}

