// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptions.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0 } from './V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0';
import {
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSON,
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSONTyped,
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSON,
    V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSONTyped,
} from './V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0';

/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptions
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptions {
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptions
     */
    key0?: V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0;
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptions
     */
    key1?: V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0;
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptions
     */
    key2?: V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptions interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptions(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptions {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptionsFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptions {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptionsFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'key0': json['key_0'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSON(json['key_0']),
        'key1': json['key_1'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSON(json['key_1']),
        'key2': json['key_2'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0FromJSON(json['key_2']),
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptionsToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptions {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptionsToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptionsToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPendingUpdateSubscriptionItemsInnerPriceCurrencyOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key_0': V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSON(value['key0']),
        'key_1': V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSON(value['key1']),
        'key_2': V1CheckoutSessionsGet200ResponseDataInnerLineItemsDataInnerPriceCurrencyOptionsKey0ToJSON(value['key2']),
    };
}

