// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPayto.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoMandateOptions } from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoMandateOptions';
import {
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoMandateOptionsFromJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoMandateOptionsFromJSONTyped,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoMandateOptionsToJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoMandateOptionsToJSONTyped,
} from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoMandateOptions';

/**
 * 
 * @export
 * @interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPayto
 */
export interface V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPayto {
    /**
     * 
     * @type {V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoMandateOptions}
     * @memberof V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPayto
     */
    mandateOptions?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoMandateOptions;
}

/**
 * Check if a given object implements the V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPayto interface.
 */
export function instanceOfV1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPayto(value: object): value is V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPayto {
    return true;
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoFromJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPayto {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoFromJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPayto {
    if (json == null) {
        return json;
    }
    return {
        
        'mandateOptions': json['mandate_options'] == null ? undefined : V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoMandateOptionsFromJSON(json['mandate_options']),
    };
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoToJSON(json: any): V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPayto {
    return V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoToJSONTyped(json, false);
}

export function V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoToJSONTyped(value?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPayto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mandate_options': V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCustomerSubscriptionsDataInnerPaymentSettingsPaymentMethodOptionsPaytoMandateOptionsToJSON(value['mandateOptions']),
    };
}

