// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPayment.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPayment
 */
export interface V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPayment {
    /**
     * 
     * @type {string}
     * @memberof V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPayment
     */
    paymentIntent?: string;
}

/**
 * Check if a given object implements the V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPayment interface.
 */
export function instanceOfV1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPayment(value: object): value is V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPayment {
    return true;
}

export function V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPaymentFromJSON(json: any): V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPayment {
    return V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPaymentFromJSONTyped(json, false);
}

export function V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPayment {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentIntent': json['payment_intent'] == null ? undefined : json['payment_intent'],
    };
}

export function V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPaymentToJSON(json: any): V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPayment {
    return V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPaymentToJSONTyped(json, false);
}

export function V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPaymentToJSONTyped(value?: V1CustomersCustomerCashBalanceTransactionsGet200ResponseDataInnerAppliedToPayment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_intent': value['paymentIntent'],
    };
}

