// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsCurrencyOptions } from './V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsCurrencyOptions';
import {
    V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsCurrencyOptionsFromJSON,
    V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsCurrencyOptionsFromJSONTyped,
    V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsCurrencyOptionsToJSON,
    V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsCurrencyOptionsToJSONTyped,
} from './V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsCurrencyOptions';

/**
 * 
 * @export
 * @interface V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions
 */
export interface V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions {
    /**
     * 
     * @type {boolean}
     * @memberof V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions
     */
    firstTimeTransaction?: boolean;
    /**
     * 
     * @type {V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsCurrencyOptions}
     * @memberof V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions
     */
    currencyOptions?: V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsCurrencyOptions;
    /**
     * 
     * @type {number}
     * @memberof V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions
     */
    minimumAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions
     */
    minimumAmountCurrency?: string;
}

/**
 * Check if a given object implements the V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions interface.
 */
export function instanceOfV1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions(value: object): value is V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions {
    return true;
}

export function V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsFromJSON(json: any): V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions {
    return V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsFromJSONTyped(json, false);
}

export function V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions {
    if (json == null) {
        return json;
    }
    return {
        
        'firstTimeTransaction': json['first_time_transaction'] == null ? undefined : json['first_time_transaction'],
        'currencyOptions': json['currency_options'] == null ? undefined : V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsCurrencyOptionsFromJSON(json['currency_options']),
        'minimumAmount': json['minimum_amount'] == null ? undefined : json['minimum_amount'],
        'minimumAmountCurrency': json['minimum_amount_currency'] == null ? undefined : json['minimum_amount_currency'],
    };
}

export function V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsToJSON(json: any): V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions {
    return V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsToJSONTyped(json, false);
}

export function V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsToJSONTyped(value?: V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_time_transaction': value['firstTimeTransaction'],
        'currency_options': V1CustomersCustomerDiscountDelete200ResponsePromotionCodeRestrictionsCurrencyOptionsToJSON(value['currencyOptions']),
        'minimum_amount': value['minimumAmount'],
        'minimum_amount_currency': value['minimumAmountCurrency'],
    };
}

