// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsErrorsInner } from './V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsErrorsInner';
import {
    V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsErrorsInnerFromJSON,
    V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsErrorsInnerFromJSONTyped,
    V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsErrorsInnerToJSON,
    V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsErrorsInnerToJSONTyped,
} from './V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsErrorsInner';

/**
 * 
 * @export
 * @interface V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements
 */
export interface V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements {
    /**
     * 
     * @type {Array<string>}
     * @memberof V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements
     */
    currentlyDue?: Array<string>;
    /**
     * 
     * @type {Array<V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsErrorsInner>}
     * @memberof V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements
     */
    errors?: Array<V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsErrorsInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements
     */
    pastDue?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements
     */
    pendingVerification?: Array<string>;
}

/**
 * Check if a given object implements the V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements interface.
 */
export function instanceOfV1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements(value: object): value is V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements {
    return true;
}

export function V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsFromJSON(json: any): V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements {
    return V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsFromJSONTyped(json, false);
}

export function V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements {
    if (json == null) {
        return json;
    }
    return {
        
        'currentlyDue': json['currently_due'] == null ? undefined : json['currently_due'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsErrorsInnerFromJSON)),
        'pastDue': json['past_due'] == null ? undefined : json['past_due'],
        'pendingVerification': json['pending_verification'] == null ? undefined : json['pending_verification'],
    };
}

export function V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsToJSON(json: any): V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements {
    return V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsToJSONTyped(json, false);
}

export function V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsToJSONTyped(value?: V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirements | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currently_due': value['currentlyDue'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(V1CustomersCustomerBankAccountsGet200ResponseDataInnerFutureRequirementsErrorsInnerToJSON)),
        'past_due': value['pastDue'],
        'pending_verification': value['pendingVerification'],
    };
}

