// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1CustomersCustomerSubscriptionsPost200ResponseItems.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CustomersCustomerSubscriptionsPost200ResponseItemsDataInner } from './V1CustomersCustomerSubscriptionsPost200ResponseItemsDataInner';
import {
    V1CustomersCustomerSubscriptionsPost200ResponseItemsDataInnerFromJSON,
    V1CustomersCustomerSubscriptionsPost200ResponseItemsDataInnerFromJSONTyped,
    V1CustomersCustomerSubscriptionsPost200ResponseItemsDataInnerToJSON,
    V1CustomersCustomerSubscriptionsPost200ResponseItemsDataInnerToJSONTyped,
} from './V1CustomersCustomerSubscriptionsPost200ResponseItemsDataInner';

/**
 * 
 * @export
 * @interface V1CustomersCustomerSubscriptionsPost200ResponseItems
 */
export interface V1CustomersCustomerSubscriptionsPost200ResponseItems {
    /**
     * 
     * @type {Array<V1CustomersCustomerSubscriptionsPost200ResponseItemsDataInner>}
     * @memberof V1CustomersCustomerSubscriptionsPost200ResponseItems
     */
    data?: Array<V1CustomersCustomerSubscriptionsPost200ResponseItemsDataInner>;
    /**
     * 
     * @type {boolean}
     * @memberof V1CustomersCustomerSubscriptionsPost200ResponseItems
     */
    hasMore?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1CustomersCustomerSubscriptionsPost200ResponseItems
     */
    object?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CustomersCustomerSubscriptionsPost200ResponseItems
     */
    url?: string;
}

/**
 * Check if a given object implements the V1CustomersCustomerSubscriptionsPost200ResponseItems interface.
 */
export function instanceOfV1CustomersCustomerSubscriptionsPost200ResponseItems(value: object): value is V1CustomersCustomerSubscriptionsPost200ResponseItems {
    return true;
}

export function V1CustomersCustomerSubscriptionsPost200ResponseItemsFromJSON(json: any): V1CustomersCustomerSubscriptionsPost200ResponseItems {
    return V1CustomersCustomerSubscriptionsPost200ResponseItemsFromJSONTyped(json, false);
}

export function V1CustomersCustomerSubscriptionsPost200ResponseItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CustomersCustomerSubscriptionsPost200ResponseItems {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V1CustomersCustomerSubscriptionsPost200ResponseItemsDataInnerFromJSON)),
        'hasMore': json['has_more'] == null ? undefined : json['has_more'],
        'object': json['object'] == null ? undefined : json['object'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function V1CustomersCustomerSubscriptionsPost200ResponseItemsToJSON(json: any): V1CustomersCustomerSubscriptionsPost200ResponseItems {
    return V1CustomersCustomerSubscriptionsPost200ResponseItemsToJSONTyped(json, false);
}

export function V1CustomersCustomerSubscriptionsPost200ResponseItemsToJSONTyped(value?: V1CustomersCustomerSubscriptionsPost200ResponseItems | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V1CustomersCustomerSubscriptionsPost200ResponseItemsDataInnerToJSON)),
        'has_more': value['hasMore'],
        'object': value['object'],
        'url': value['url'],
    };
}

