// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1DisputesGet200ResponseDataInnerPaymentMethodDetails.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1DisputesGet200ResponseDataInnerPaymentMethodDetailsAmazonPay } from './V1DisputesGet200ResponseDataInnerPaymentMethodDetailsAmazonPay';
import {
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsAmazonPayFromJSON,
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsAmazonPayFromJSONTyped,
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsAmazonPayToJSON,
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsAmazonPayToJSONTyped,
} from './V1DisputesGet200ResponseDataInnerPaymentMethodDetailsAmazonPay';
import type { V1DisputesGet200ResponseDataInnerPaymentMethodDetailsKlarna } from './V1DisputesGet200ResponseDataInnerPaymentMethodDetailsKlarna';
import {
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsKlarnaFromJSON,
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsKlarnaFromJSONTyped,
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsKlarnaToJSON,
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsKlarnaToJSONTyped,
} from './V1DisputesGet200ResponseDataInnerPaymentMethodDetailsKlarna';
import type { V1DisputesGet200ResponseDataInnerPaymentMethodDetailsCard } from './V1DisputesGet200ResponseDataInnerPaymentMethodDetailsCard';
import {
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsCardFromJSON,
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsCardFromJSONTyped,
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsCardToJSON,
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsCardToJSONTyped,
} from './V1DisputesGet200ResponseDataInnerPaymentMethodDetailsCard';
import type { V1DisputesGet200ResponseDataInnerPaymentMethodDetailsPaypal } from './V1DisputesGet200ResponseDataInnerPaymentMethodDetailsPaypal';
import {
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsPaypalFromJSON,
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsPaypalFromJSONTyped,
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsPaypalToJSON,
    V1DisputesGet200ResponseDataInnerPaymentMethodDetailsPaypalToJSONTyped,
} from './V1DisputesGet200ResponseDataInnerPaymentMethodDetailsPaypal';

/**
 * 
 * @export
 * @interface V1DisputesGet200ResponseDataInnerPaymentMethodDetails
 */
export interface V1DisputesGet200ResponseDataInnerPaymentMethodDetails {
    /**
     * 
     * @type {string}
     * @memberof V1DisputesGet200ResponseDataInnerPaymentMethodDetails
     */
    type?: string;
    /**
     * 
     * @type {V1DisputesGet200ResponseDataInnerPaymentMethodDetailsAmazonPay}
     * @memberof V1DisputesGet200ResponseDataInnerPaymentMethodDetails
     */
    amazonPay?: V1DisputesGet200ResponseDataInnerPaymentMethodDetailsAmazonPay;
    /**
     * 
     * @type {V1DisputesGet200ResponseDataInnerPaymentMethodDetailsCard}
     * @memberof V1DisputesGet200ResponseDataInnerPaymentMethodDetails
     */
    card?: V1DisputesGet200ResponseDataInnerPaymentMethodDetailsCard;
    /**
     * 
     * @type {V1DisputesGet200ResponseDataInnerPaymentMethodDetailsKlarna}
     * @memberof V1DisputesGet200ResponseDataInnerPaymentMethodDetails
     */
    klarna?: V1DisputesGet200ResponseDataInnerPaymentMethodDetailsKlarna;
    /**
     * 
     * @type {V1DisputesGet200ResponseDataInnerPaymentMethodDetailsPaypal}
     * @memberof V1DisputesGet200ResponseDataInnerPaymentMethodDetails
     */
    paypal?: V1DisputesGet200ResponseDataInnerPaymentMethodDetailsPaypal;
}

/**
 * Check if a given object implements the V1DisputesGet200ResponseDataInnerPaymentMethodDetails interface.
 */
export function instanceOfV1DisputesGet200ResponseDataInnerPaymentMethodDetails(value: object): value is V1DisputesGet200ResponseDataInnerPaymentMethodDetails {
    return true;
}

export function V1DisputesGet200ResponseDataInnerPaymentMethodDetailsFromJSON(json: any): V1DisputesGet200ResponseDataInnerPaymentMethodDetails {
    return V1DisputesGet200ResponseDataInnerPaymentMethodDetailsFromJSONTyped(json, false);
}

export function V1DisputesGet200ResponseDataInnerPaymentMethodDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DisputesGet200ResponseDataInnerPaymentMethodDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'amazonPay': json['amazon_pay'] == null ? undefined : V1DisputesGet200ResponseDataInnerPaymentMethodDetailsAmazonPayFromJSON(json['amazon_pay']),
        'card': json['card'] == null ? undefined : V1DisputesGet200ResponseDataInnerPaymentMethodDetailsCardFromJSON(json['card']),
        'klarna': json['klarna'] == null ? undefined : V1DisputesGet200ResponseDataInnerPaymentMethodDetailsKlarnaFromJSON(json['klarna']),
        'paypal': json['paypal'] == null ? undefined : V1DisputesGet200ResponseDataInnerPaymentMethodDetailsPaypalFromJSON(json['paypal']),
    };
}

export function V1DisputesGet200ResponseDataInnerPaymentMethodDetailsToJSON(json: any): V1DisputesGet200ResponseDataInnerPaymentMethodDetails {
    return V1DisputesGet200ResponseDataInnerPaymentMethodDetailsToJSONTyped(json, false);
}

export function V1DisputesGet200ResponseDataInnerPaymentMethodDetailsToJSONTyped(value?: V1DisputesGet200ResponseDataInnerPaymentMethodDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'amazon_pay': V1DisputesGet200ResponseDataInnerPaymentMethodDetailsAmazonPayToJSON(value['amazonPay']),
        'card': V1DisputesGet200ResponseDataInnerPaymentMethodDetailsCardToJSON(value['card']),
        'klarna': V1DisputesGet200ResponseDataInnerPaymentMethodDetailsKlarnaToJSON(value['klarna']),
        'paypal': V1DisputesGet200ResponseDataInnerPaymentMethodDetailsPaypalToJSON(value['paypal']),
    };
}

