// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1InvoicesGet200ResponseDataInnerFromInvoice.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1InvoicesGet200ResponseDataInnerFromInvoice
 */
export interface V1InvoicesGet200ResponseDataInnerFromInvoice {
    /**
     * 
     * @type {string}
     * @memberof V1InvoicesGet200ResponseDataInnerFromInvoice
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof V1InvoicesGet200ResponseDataInnerFromInvoice
     */
    invoice?: string;
}

/**
 * Check if a given object implements the V1InvoicesGet200ResponseDataInnerFromInvoice interface.
 */
export function instanceOfV1InvoicesGet200ResponseDataInnerFromInvoice(value: object): value is V1InvoicesGet200ResponseDataInnerFromInvoice {
    return true;
}

export function V1InvoicesGet200ResponseDataInnerFromInvoiceFromJSON(json: any): V1InvoicesGet200ResponseDataInnerFromInvoice {
    return V1InvoicesGet200ResponseDataInnerFromInvoiceFromJSONTyped(json, false);
}

export function V1InvoicesGet200ResponseDataInnerFromInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1InvoicesGet200ResponseDataInnerFromInvoice {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'] == null ? undefined : json['action'],
        'invoice': json['invoice'] == null ? undefined : json['invoice'],
    };
}

export function V1InvoicesGet200ResponseDataInnerFromInvoiceToJSON(json: any): V1InvoicesGet200ResponseDataInnerFromInvoice {
    return V1InvoicesGet200ResponseDataInnerFromInvoiceToJSONTyped(json, false);
}

export function V1InvoicesGet200ResponseDataInnerFromInvoiceToJSONTyped(value?: V1InvoicesGet200ResponseDataInnerFromInvoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'invoice': value['invoice'],
    };
}

