// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1InvoicesGet200ResponseDataInnerLinesDataInnerParentInvoiceItemDetailsProrationDetails } from './V1InvoicesGet200ResponseDataInnerLinesDataInnerParentInvoiceItemDetailsProrationDetails';
import {
    V1InvoicesGet200ResponseDataInnerLinesDataInnerParentInvoiceItemDetailsProrationDetailsFromJSON,
    V1InvoicesGet200ResponseDataInnerLinesDataInnerParentInvoiceItemDetailsProrationDetailsFromJSONTyped,
    V1InvoicesGet200ResponseDataInnerLinesDataInnerParentInvoiceItemDetailsProrationDetailsToJSON,
    V1InvoicesGet200ResponseDataInnerLinesDataInnerParentInvoiceItemDetailsProrationDetailsToJSONTyped,
} from './V1InvoicesGet200ResponseDataInnerLinesDataInnerParentInvoiceItemDetailsProrationDetails';

/**
 * 
 * @export
 * @interface V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails
 */
export interface V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails {
    /**
     * 
     * @type {boolean}
     * @memberof V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails
     */
    proration?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails
     */
    subscriptionItem?: string;
    /**
     * 
     * @type {string}
     * @memberof V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails
     */
    invoiceItem?: string;
    /**
     * 
     * @type {V1InvoicesGet200ResponseDataInnerLinesDataInnerParentInvoiceItemDetailsProrationDetails}
     * @memberof V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails
     */
    prorationDetails?: V1InvoicesGet200ResponseDataInnerLinesDataInnerParentInvoiceItemDetailsProrationDetails;
    /**
     * 
     * @type {string}
     * @memberof V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails
     */
    subscription?: string;
}

/**
 * Check if a given object implements the V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails interface.
 */
export function instanceOfV1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails(value: object): value is V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails {
    return true;
}

export function V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetailsFromJSON(json: any): V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails {
    return V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetailsFromJSONTyped(json, false);
}

export function V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'proration': json['proration'] == null ? undefined : json['proration'],
        'subscriptionItem': json['subscription_item'] == null ? undefined : json['subscription_item'],
        'invoiceItem': json['invoice_item'] == null ? undefined : json['invoice_item'],
        'prorationDetails': json['proration_details'] == null ? undefined : V1InvoicesGet200ResponseDataInnerLinesDataInnerParentInvoiceItemDetailsProrationDetailsFromJSON(json['proration_details']),
        'subscription': json['subscription'] == null ? undefined : json['subscription'],
    };
}

export function V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetailsToJSON(json: any): V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails {
    return V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetailsToJSONTyped(json, false);
}

export function V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetailsToJSONTyped(value?: V1InvoicesGet200ResponseDataInnerLinesDataInnerParentSubscriptionItemDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'proration': value['proration'],
        'subscription_item': value['subscriptionItem'],
        'invoice_item': value['invoiceItem'],
        'proration_details': V1InvoicesGet200ResponseDataInnerLinesDataInnerParentInvoiceItemDetailsProrationDetailsToJSON(value['prorationDetails']),
        'subscription': value['subscription'],
    };
}

