// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasons.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasons
 */
export interface V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasons {
    /**
     * 
     * @type {Array<string>}
     * @memberof V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasons
     */
    cardLogo?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasons
     */
    carrierText?: Array<string>;
}

/**
 * Check if a given object implements the V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasons interface.
 */
export function instanceOfV1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasons(value: object): value is V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasons {
    return true;
}

export function V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasonsFromJSON(json: any): V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasons {
    return V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasonsFromJSONTyped(json, false);
}

export function V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasonsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasons {
    if (json == null) {
        return json;
    }
    return {
        
        'cardLogo': json['card_logo'] == null ? undefined : json['card_logo'],
        'carrierText': json['carrier_text'] == null ? undefined : json['carrier_text'],
    };
}

export function V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasonsToJSON(json: any): V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasons {
    return V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasonsToJSONTyped(json, false);
}

export function V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasonsToJSONTyped(value?: V1IssuingPersonalizationDesignsGet200ResponseDataInnerRejectionReasons | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'card_logo': value['cardLogo'],
        'carrier_text': value['carrierText'],
    };
}

