// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetails.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetails
 */
export interface V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetails {
    /**
     * 
     * @type {number}
     * @memberof V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetails
     */
    atmFee?: number;
    /**
     * 
     * @type {number}
     * @memberof V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetails
     */
    cashbackAmount?: number;
}

/**
 * Check if a given object implements the V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetails interface.
 */
export function instanceOfV1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetails(value: object): value is V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetails {
    return true;
}

export function V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetailsFromJSON(json: any): V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetails {
    return V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetailsFromJSONTyped(json, false);
}

export function V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'atmFee': json['atm_fee'] == null ? undefined : json['atm_fee'],
        'cashbackAmount': json['cashback_amount'] == null ? undefined : json['cashback_amount'],
    };
}

export function V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetailsToJSON(json: any): V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetails {
    return V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetailsToJSONTyped(json, false);
}

export function V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetailsToJSONTyped(value?: V1IssuingAuthorizationsGet200ResponseDataInnerRequestHistoryInnerAmountDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'atm_fee': value['atmFee'],
        'cashback_amount': value['cashbackAmount'],
    };
}

