// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1PricesSearchGet200Response.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1CustomersCustomerSubscriptionsGet200ResponseDataInnerItemsDataInnerPrice } from './V1CustomersCustomerSubscriptionsGet200ResponseDataInnerItemsDataInnerPrice';
import {
    V1CustomersCustomerSubscriptionsGet200ResponseDataInnerItemsDataInnerPriceFromJSON,
    V1CustomersCustomerSubscriptionsGet200ResponseDataInnerItemsDataInnerPriceFromJSONTyped,
    V1CustomersCustomerSubscriptionsGet200ResponseDataInnerItemsDataInnerPriceToJSON,
    V1CustomersCustomerSubscriptionsGet200ResponseDataInnerItemsDataInnerPriceToJSONTyped,
} from './V1CustomersCustomerSubscriptionsGet200ResponseDataInnerItemsDataInnerPrice';

/**
 * 
 * @export
 * @interface V1PricesSearchGet200Response
 */
export interface V1PricesSearchGet200Response {
    /**
     * 
     * @type {Array<V1CustomersCustomerSubscriptionsGet200ResponseDataInnerItemsDataInnerPrice>}
     * @memberof V1PricesSearchGet200Response
     */
    data?: Array<V1CustomersCustomerSubscriptionsGet200ResponseDataInnerItemsDataInnerPrice>;
    /**
     * 
     * @type {boolean}
     * @memberof V1PricesSearchGet200Response
     */
    hasMore?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1PricesSearchGet200Response
     */
    object?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PricesSearchGet200Response
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PricesSearchGet200Response
     */
    nextPage?: string;
    /**
     * 
     * @type {number}
     * @memberof V1PricesSearchGet200Response
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the V1PricesSearchGet200Response interface.
 */
export function instanceOfV1PricesSearchGet200Response(value: object): value is V1PricesSearchGet200Response {
    return true;
}

export function V1PricesSearchGet200ResponseFromJSON(json: any): V1PricesSearchGet200Response {
    return V1PricesSearchGet200ResponseFromJSONTyped(json, false);
}

export function V1PricesSearchGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PricesSearchGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V1CustomersCustomerSubscriptionsGet200ResponseDataInnerItemsDataInnerPriceFromJSON)),
        'hasMore': json['has_more'] == null ? undefined : json['has_more'],
        'object': json['object'] == null ? undefined : json['object'],
        'url': json['url'] == null ? undefined : json['url'],
        'nextPage': json['next_page'] == null ? undefined : json['next_page'],
        'totalCount': json['total_count'] == null ? undefined : json['total_count'],
    };
}

export function V1PricesSearchGet200ResponseToJSON(json: any): V1PricesSearchGet200Response {
    return V1PricesSearchGet200ResponseToJSONTyped(json, false);
}

export function V1PricesSearchGet200ResponseToJSONTyped(value?: V1PricesSearchGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V1CustomersCustomerSubscriptionsGet200ResponseDataInnerItemsDataInnerPriceToJSON)),
        'has_more': value['hasMore'],
        'object': value['object'],
        'url': value['url'],
        'next_page': value['nextPage'],
        'total_count': value['totalCount'],
    };
}

