// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1QuotesPost200ResponseSubscriptionData.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1QuotesGet200ResponseDataInnerSubscriptionDataBillingMode } from './V1QuotesGet200ResponseDataInnerSubscriptionDataBillingMode';
import {
    V1QuotesGet200ResponseDataInnerSubscriptionDataBillingModeFromJSON,
    V1QuotesGet200ResponseDataInnerSubscriptionDataBillingModeFromJSONTyped,
    V1QuotesGet200ResponseDataInnerSubscriptionDataBillingModeToJSON,
    V1QuotesGet200ResponseDataInnerSubscriptionDataBillingModeToJSONTyped,
} from './V1QuotesGet200ResponseDataInnerSubscriptionDataBillingMode';
import type { V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataMetadata } from './V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataMetadata';
import {
    V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataMetadataFromJSON,
    V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataMetadataFromJSONTyped,
    V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataMetadataToJSON,
    V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataMetadataToJSONTyped,
} from './V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataMetadata';

/**
 * 
 * @export
 * @interface V1QuotesPost200ResponseSubscriptionData
 */
export interface V1QuotesPost200ResponseSubscriptionData {
    /**
     * 
     * @type {V1QuotesGet200ResponseDataInnerSubscriptionDataBillingMode}
     * @memberof V1QuotesPost200ResponseSubscriptionData
     */
    billingMode?: V1QuotesGet200ResponseDataInnerSubscriptionDataBillingMode;
    /**
     * 
     * @type {number}
     * @memberof V1QuotesPost200ResponseSubscriptionData
     */
    effectiveDate?: number;
    /**
     * 
     * @type {V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataMetadata}
     * @memberof V1QuotesPost200ResponseSubscriptionData
     */
    metadata?: V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataMetadata;
    /**
     * 
     * @type {number}
     * @memberof V1QuotesPost200ResponseSubscriptionData
     */
    trialPeriodDays?: number;
}

/**
 * Check if a given object implements the V1QuotesPost200ResponseSubscriptionData interface.
 */
export function instanceOfV1QuotesPost200ResponseSubscriptionData(value: object): value is V1QuotesPost200ResponseSubscriptionData {
    return true;
}

export function V1QuotesPost200ResponseSubscriptionDataFromJSON(json: any): V1QuotesPost200ResponseSubscriptionData {
    return V1QuotesPost200ResponseSubscriptionDataFromJSONTyped(json, false);
}

export function V1QuotesPost200ResponseSubscriptionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1QuotesPost200ResponseSubscriptionData {
    if (json == null) {
        return json;
    }
    return {
        
        'billingMode': json['billing_mode'] == null ? undefined : V1QuotesGet200ResponseDataInnerSubscriptionDataBillingModeFromJSON(json['billing_mode']),
        'effectiveDate': json['effective_date'] == null ? undefined : json['effective_date'],
        'metadata': json['metadata'] == null ? undefined : V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataMetadataFromJSON(json['metadata']),
        'trialPeriodDays': json['trial_period_days'] == null ? undefined : json['trial_period_days'],
    };
}

export function V1QuotesPost200ResponseSubscriptionDataToJSON(json: any): V1QuotesPost200ResponseSubscriptionData {
    return V1QuotesPost200ResponseSubscriptionDataToJSONTyped(json, false);
}

export function V1QuotesPost200ResponseSubscriptionDataToJSONTyped(value?: V1QuotesPost200ResponseSubscriptionData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'billing_mode': V1QuotesGet200ResponseDataInnerSubscriptionDataBillingModeToJSON(value['billingMode']),
        'effective_date': value['effectiveDate'],
        'metadata': V1CheckoutSessionsGet200ResponseDataInnerInvoiceCreationInvoiceDataMetadataToJSON(value['metadata']),
        'trial_period_days': value['trialPeriodDays'],
    };
}

