// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaised.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentWallet } from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentWallet';
import {
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentWalletFromJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentWalletFromJSONTyped,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentWalletToJSON,
    V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentWalletToJSONTyped,
} from './V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentWallet';

/**
 * 
 * @export
 * @interface V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaised
 */
export interface V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaised {
    /**
     * 
     * @type {string}
     * @memberof V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaised
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaised
     */
    type?: string;
    /**
     * 
     * @type {V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentWallet}
     * @memberof V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaised
     */
    custom?: V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentWallet;
}

/**
 * Check if a given object implements the V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaised interface.
 */
export function instanceOfV1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaised(value: object): value is V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaised {
    return true;
}

export function V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaisedFromJSON(json: any): V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaised {
    return V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaisedFromJSONTyped(json, false);
}

export function V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaisedFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaised {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'type': json['type'] == null ? undefined : json['type'],
        'custom': json['custom'] == null ? undefined : V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentWalletFromJSON(json['custom']),
    };
}

export function V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaisedToJSON(json: any): V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaised {
    return V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaisedToJSONTyped(json, false);
}

export function V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaisedToJSONTyped(value?: V1RadarPaymentEvaluationsPost200ResponseEventsInnerUserInterventionRaised | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'type': value['type'],
        'custom': V1ConfirmationTokensConfirmationTokenGet200ResponsePaymentMethodPreviewCardGeneratedFromPaymentMethodDetailsCardPresentWalletToJSON(value['custom']),
    };
}

