// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1RadarEarlyFraudWarningsGet200ResponseDataInner.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1RadarEarlyFraudWarningsGet200ResponseDataInner
 */
export interface V1RadarEarlyFraudWarningsGet200ResponseDataInner {
    /**
     * 
     * @type {boolean}
     * @memberof V1RadarEarlyFraudWarningsGet200ResponseDataInner
     */
    actionable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1RadarEarlyFraudWarningsGet200ResponseDataInner
     */
    charge?: string;
    /**
     * 
     * @type {number}
     * @memberof V1RadarEarlyFraudWarningsGet200ResponseDataInner
     */
    created?: number;
    /**
     * 
     * @type {string}
     * @memberof V1RadarEarlyFraudWarningsGet200ResponseDataInner
     */
    fraudType?: string;
    /**
     * 
     * @type {string}
     * @memberof V1RadarEarlyFraudWarningsGet200ResponseDataInner
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1RadarEarlyFraudWarningsGet200ResponseDataInner
     */
    livemode?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1RadarEarlyFraudWarningsGet200ResponseDataInner
     */
    object?: string;
    /**
     * 
     * @type {string}
     * @memberof V1RadarEarlyFraudWarningsGet200ResponseDataInner
     */
    paymentIntent?: string;
}

/**
 * Check if a given object implements the V1RadarEarlyFraudWarningsGet200ResponseDataInner interface.
 */
export function instanceOfV1RadarEarlyFraudWarningsGet200ResponseDataInner(value: object): value is V1RadarEarlyFraudWarningsGet200ResponseDataInner {
    return true;
}

export function V1RadarEarlyFraudWarningsGet200ResponseDataInnerFromJSON(json: any): V1RadarEarlyFraudWarningsGet200ResponseDataInner {
    return V1RadarEarlyFraudWarningsGet200ResponseDataInnerFromJSONTyped(json, false);
}

export function V1RadarEarlyFraudWarningsGet200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1RadarEarlyFraudWarningsGet200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'actionable': json['actionable'] == null ? undefined : json['actionable'],
        'charge': json['charge'] == null ? undefined : json['charge'],
        'created': json['created'] == null ? undefined : json['created'],
        'fraudType': json['fraud_type'] == null ? undefined : json['fraud_type'],
        'id': json['id'] == null ? undefined : json['id'],
        'livemode': json['livemode'] == null ? undefined : json['livemode'],
        'object': json['object'] == null ? undefined : json['object'],
        'paymentIntent': json['payment_intent'] == null ? undefined : json['payment_intent'],
    };
}

export function V1RadarEarlyFraudWarningsGet200ResponseDataInnerToJSON(json: any): V1RadarEarlyFraudWarningsGet200ResponseDataInner {
    return V1RadarEarlyFraudWarningsGet200ResponseDataInnerToJSONTyped(json, false);
}

export function V1RadarEarlyFraudWarningsGet200ResponseDataInnerToJSONTyped(value?: V1RadarEarlyFraudWarningsGet200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actionable': value['actionable'],
        'charge': value['charge'],
        'created': value['created'],
        'fraud_type': value['fraudType'],
        'id': value['id'],
        'livemode': value['livemode'],
        'object': value['object'],
        'payment_intent': value['paymentIntent'],
    };
}

