// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1TestHelpersTreasuryReceivedDebitsPost200Response } from './V1TestHelpersTreasuryReceivedDebitsPost200Response';
import {
    V1TestHelpersTreasuryReceivedDebitsPost200ResponseFromJSON,
    V1TestHelpersTreasuryReceivedDebitsPost200ResponseFromJSONTyped,
    V1TestHelpersTreasuryReceivedDebitsPost200ResponseToJSON,
    V1TestHelpersTreasuryReceivedDebitsPost200ResponseToJSONTyped,
} from './V1TestHelpersTreasuryReceivedDebitsPost200Response';
import type { V1TreasuryCreditReversalsGet200ResponseDataInner } from './V1TreasuryCreditReversalsGet200ResponseDataInner';
import {
    V1TreasuryCreditReversalsGet200ResponseDataInnerFromJSON,
    V1TreasuryCreditReversalsGet200ResponseDataInnerFromJSONTyped,
    V1TreasuryCreditReversalsGet200ResponseDataInnerToJSON,
    V1TreasuryCreditReversalsGet200ResponseDataInnerToJSONTyped,
} from './V1TreasuryCreditReversalsGet200ResponseDataInner';
import type { V1TreasuryOutboundPaymentsGet200ResponseDataInner } from './V1TreasuryOutboundPaymentsGet200ResponseDataInner';
import {
    V1TreasuryOutboundPaymentsGet200ResponseDataInnerFromJSON,
    V1TreasuryOutboundPaymentsGet200ResponseDataInnerFromJSONTyped,
    V1TreasuryOutboundPaymentsGet200ResponseDataInnerToJSON,
    V1TreasuryOutboundPaymentsGet200ResponseDataInnerToJSONTyped,
} from './V1TreasuryOutboundPaymentsGet200ResponseDataInner';
import type { V1ChargesChargeGet200Response } from './V1ChargesChargeGet200Response';
import {
    V1ChargesChargeGet200ResponseFromJSON,
    V1ChargesChargeGet200ResponseFromJSONTyped,
    V1ChargesChargeGet200ResponseToJSON,
    V1ChargesChargeGet200ResponseToJSONTyped,
} from './V1ChargesChargeGet200Response';
import type { V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsReceivedCredit } from './V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsReceivedCredit';
import {
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsReceivedCreditFromJSON,
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsReceivedCreditFromJSONTyped,
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsReceivedCreditToJSON,
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsReceivedCreditToJSONTyped,
} from './V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsReceivedCredit';
import type { V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsIssuingAuthorization } from './V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsIssuingAuthorization';
import {
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsIssuingAuthorizationFromJSON,
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsIssuingAuthorizationFromJSONTyped,
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsIssuingAuthorizationToJSON,
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsIssuingAuthorizationToJSONTyped,
} from './V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsIssuingAuthorization';
import type { V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsOutboundTransfer } from './V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsOutboundTransfer';
import {
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsOutboundTransferFromJSON,
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsOutboundTransferFromJSONTyped,
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsOutboundTransferToJSON,
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsOutboundTransferToJSONTyped,
} from './V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsOutboundTransfer';
import type { V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsDebitReversal } from './V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsDebitReversal';
import {
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsDebitReversalFromJSON,
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsDebitReversalFromJSONTyped,
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsDebitReversalToJSON,
    V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsDebitReversalToJSONTyped,
} from './V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsDebitReversal';

/**
 * 
 * @export
 * @interface V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails
 */
export interface V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails {
    /**
     * 
     * @type {string}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails
     */
    type?: string;
    /**
     * 
     * @type {V1TreasuryCreditReversalsGet200ResponseDataInner}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails
     */
    creditReversal?: V1TreasuryCreditReversalsGet200ResponseDataInner;
    /**
     * 
     * @type {V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsDebitReversal}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails
     */
    debitReversal?: V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsDebitReversal;
    /**
     * 
     * @type {V1ChargesChargeGet200Response}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails
     */
    inboundTransfer?: V1ChargesChargeGet200Response;
    /**
     * 
     * @type {V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsIssuingAuthorization}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails
     */
    issuingAuthorization?: V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsIssuingAuthorization;
    /**
     * 
     * @type {V1TreasuryOutboundPaymentsGet200ResponseDataInner}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails
     */
    outboundPayment?: V1TreasuryOutboundPaymentsGet200ResponseDataInner;
    /**
     * 
     * @type {V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsOutboundTransfer}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails
     */
    outboundTransfer?: V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsOutboundTransfer;
    /**
     * 
     * @type {V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsReceivedCredit}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails
     */
    receivedCredit?: V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsReceivedCredit;
    /**
     * 
     * @type {V1TestHelpersTreasuryReceivedDebitsPost200Response}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails
     */
    receivedDebit?: V1TestHelpersTreasuryReceivedDebitsPost200Response;
}

/**
 * Check if a given object implements the V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails interface.
 */
export function instanceOfV1TreasuryTransactionsGet200ResponseDataInnerFlowDetails(value: object): value is V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails {
    return true;
}

export function V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsFromJSON(json: any): V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails {
    return V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsFromJSONTyped(json, false);
}

export function V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'creditReversal': json['credit_reversal'] == null ? undefined : V1TreasuryCreditReversalsGet200ResponseDataInnerFromJSON(json['credit_reversal']),
        'debitReversal': json['debit_reversal'] == null ? undefined : V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsDebitReversalFromJSON(json['debit_reversal']),
        'inboundTransfer': json['inbound_transfer'] == null ? undefined : V1ChargesChargeGet200ResponseFromJSON(json['inbound_transfer']),
        'issuingAuthorization': json['issuing_authorization'] == null ? undefined : V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsIssuingAuthorizationFromJSON(json['issuing_authorization']),
        'outboundPayment': json['outbound_payment'] == null ? undefined : V1TreasuryOutboundPaymentsGet200ResponseDataInnerFromJSON(json['outbound_payment']),
        'outboundTransfer': json['outbound_transfer'] == null ? undefined : V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsOutboundTransferFromJSON(json['outbound_transfer']),
        'receivedCredit': json['received_credit'] == null ? undefined : V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsReceivedCreditFromJSON(json['received_credit']),
        'receivedDebit': json['received_debit'] == null ? undefined : V1TestHelpersTreasuryReceivedDebitsPost200ResponseFromJSON(json['received_debit']),
    };
}

export function V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsToJSON(json: any): V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails {
    return V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsToJSONTyped(json, false);
}

export function V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsToJSONTyped(value?: V1TreasuryTransactionsGet200ResponseDataInnerFlowDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'credit_reversal': V1TreasuryCreditReversalsGet200ResponseDataInnerToJSON(value['creditReversal']),
        'debit_reversal': V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsDebitReversalToJSON(value['debitReversal']),
        'inbound_transfer': V1ChargesChargeGet200ResponseToJSON(value['inboundTransfer']),
        'issuing_authorization': V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsIssuingAuthorizationToJSON(value['issuingAuthorization']),
        'outbound_payment': V1TreasuryOutboundPaymentsGet200ResponseDataInnerToJSON(value['outboundPayment']),
        'outbound_transfer': V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsOutboundTransferToJSON(value['outboundTransfer']),
        'received_credit': V1TreasuryTransactionsGet200ResponseDataInnerFlowDetailsReceivedCreditToJSON(value['receivedCredit']),
        'received_debit': V1TestHelpersTreasuryReceivedDebitsPost200ResponseToJSON(value['receivedDebit']),
    };
}

