// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1TreasuryTransactionsGet200ResponseDataInnerEntries.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInner } from './V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInner';
import {
    V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFromJSON,
    V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFromJSONTyped,
    V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerToJSON,
    V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerToJSONTyped,
} from './V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInner';

/**
 * 
 * @export
 * @interface V1TreasuryTransactionsGet200ResponseDataInnerEntries
 */
export interface V1TreasuryTransactionsGet200ResponseDataInnerEntries {
    /**
     * 
     * @type {Array<V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInner>}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerEntries
     */
    data?: Array<V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInner>;
    /**
     * 
     * @type {boolean}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerEntries
     */
    hasMore?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerEntries
     */
    object?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TreasuryTransactionsGet200ResponseDataInnerEntries
     */
    url?: string;
}

/**
 * Check if a given object implements the V1TreasuryTransactionsGet200ResponseDataInnerEntries interface.
 */
export function instanceOfV1TreasuryTransactionsGet200ResponseDataInnerEntries(value: object): value is V1TreasuryTransactionsGet200ResponseDataInnerEntries {
    return true;
}

export function V1TreasuryTransactionsGet200ResponseDataInnerEntriesFromJSON(json: any): V1TreasuryTransactionsGet200ResponseDataInnerEntries {
    return V1TreasuryTransactionsGet200ResponseDataInnerEntriesFromJSONTyped(json, false);
}

export function V1TreasuryTransactionsGet200ResponseDataInnerEntriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TreasuryTransactionsGet200ResponseDataInnerEntries {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerFromJSON)),
        'hasMore': json['has_more'] == null ? undefined : json['has_more'],
        'object': json['object'] == null ? undefined : json['object'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function V1TreasuryTransactionsGet200ResponseDataInnerEntriesToJSON(json: any): V1TreasuryTransactionsGet200ResponseDataInnerEntries {
    return V1TreasuryTransactionsGet200ResponseDataInnerEntriesToJSONTyped(json, false);
}

export function V1TreasuryTransactionsGet200ResponseDataInnerEntriesToJSONTyped(value?: V1TreasuryTransactionsGet200ResponseDataInnerEntries | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V1TreasuryTransactionsGet200ResponseDataInnerEntriesDataInnerToJSON)),
        'has_more': value['hasMore'],
        'object': value['object'],
        'url': value['url'],
    };
}

