// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1TreasuryOutboundPaymentsGet200ResponseDataInner } from './V1TreasuryOutboundPaymentsGet200ResponseDataInner';
import {
    V1TreasuryOutboundPaymentsGet200ResponseDataInnerFromJSON,
    V1TreasuryOutboundPaymentsGet200ResponseDataInnerFromJSONTyped,
    V1TreasuryOutboundPaymentsGet200ResponseDataInnerToJSON,
    V1TreasuryOutboundPaymentsGet200ResponseDataInnerToJSONTyped,
} from './V1TreasuryOutboundPaymentsGet200ResponseDataInner';
import type { V1TreasuryCreditReversalsPost200Response } from './V1TreasuryCreditReversalsPost200Response';
import {
    V1TreasuryCreditReversalsPost200ResponseFromJSON,
    V1TreasuryCreditReversalsPost200ResponseFromJSONTyped,
    V1TreasuryCreditReversalsPost200ResponseToJSON,
    V1TreasuryCreditReversalsPost200ResponseToJSONTyped,
} from './V1TreasuryCreditReversalsPost200Response';
import type { V1PayoutsPost200Response } from './V1PayoutsPost200Response';
import {
    V1PayoutsPost200ResponseFromJSON,
    V1PayoutsPost200ResponseFromJSONTyped,
    V1PayoutsPost200ResponseToJSON,
    V1PayoutsPost200ResponseToJSONTyped,
} from './V1PayoutsPost200Response';
import type { V1TreasuryOutboundTransfersGet200ResponseDataInner } from './V1TreasuryOutboundTransfersGet200ResponseDataInner';
import {
    V1TreasuryOutboundTransfersGet200ResponseDataInnerFromJSON,
    V1TreasuryOutboundTransfersGet200ResponseDataInnerFromJSONTyped,
    V1TreasuryOutboundTransfersGet200ResponseDataInnerToJSON,
    V1TreasuryOutboundTransfersGet200ResponseDataInnerToJSONTyped,
} from './V1TreasuryOutboundTransfersGet200ResponseDataInner';

/**
 * 
 * @export
 * @interface V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails
 */
export interface V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails {
    /**
     * 
     * @type {string}
     * @memberof V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails
     */
    type?: string;
    /**
     * 
     * @type {V1TreasuryCreditReversalsPost200Response}
     * @memberof V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails
     */
    creditReversal?: V1TreasuryCreditReversalsPost200Response;
    /**
     * 
     * @type {V1TreasuryOutboundPaymentsGet200ResponseDataInner}
     * @memberof V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails
     */
    outboundPayment?: V1TreasuryOutboundPaymentsGet200ResponseDataInner;
    /**
     * 
     * @type {V1TreasuryOutboundTransfersGet200ResponseDataInner}
     * @memberof V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails
     */
    outboundTransfer?: V1TreasuryOutboundTransfersGet200ResponseDataInner;
    /**
     * 
     * @type {V1PayoutsPost200Response}
     * @memberof V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails
     */
    payout?: V1PayoutsPost200Response;
}

/**
 * Check if a given object implements the V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails interface.
 */
export function instanceOfV1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails(value: object): value is V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails {
    return true;
}

export function V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetailsFromJSON(json: any): V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails {
    return V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetailsFromJSONTyped(json, false);
}

export function V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'creditReversal': json['credit_reversal'] == null ? undefined : V1TreasuryCreditReversalsPost200ResponseFromJSON(json['credit_reversal']),
        'outboundPayment': json['outbound_payment'] == null ? undefined : V1TreasuryOutboundPaymentsGet200ResponseDataInnerFromJSON(json['outbound_payment']),
        'outboundTransfer': json['outbound_transfer'] == null ? undefined : V1TreasuryOutboundTransfersGet200ResponseDataInnerFromJSON(json['outbound_transfer']),
        'payout': json['payout'] == null ? undefined : V1PayoutsPost200ResponseFromJSON(json['payout']),
    };
}

export function V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetailsToJSON(json: any): V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails {
    return V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetailsToJSONTyped(json, false);
}

export function V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetailsToJSONTyped(value?: V1TreasuryTransactionsIdGet200ResponseEntriesDataInnerFlowDetailsReceivedCreditLinkedFlowsSourceFlowDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'credit_reversal': V1TreasuryCreditReversalsPost200ResponseToJSON(value['creditReversal']),
        'outbound_payment': V1TreasuryOutboundPaymentsGet200ResponseDataInnerToJSON(value['outboundPayment']),
        'outbound_transfer': V1TreasuryOutboundTransfersGet200ResponseDataInnerToJSON(value['outboundTransfer']),
        'payout': V1PayoutsPost200ResponseToJSON(value['payout']),
    };
}

