// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/V1TransfersGet200Response.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1TransfersGet200ResponseDataInner } from './V1TransfersGet200ResponseDataInner';
import {
    V1TransfersGet200ResponseDataInnerFromJSON,
    V1TransfersGet200ResponseDataInnerFromJSONTyped,
    V1TransfersGet200ResponseDataInnerToJSON,
    V1TransfersGet200ResponseDataInnerToJSONTyped,
} from './V1TransfersGet200ResponseDataInner';

/**
 * 
 * @export
 * @interface V1TransfersGet200Response
 */
export interface V1TransfersGet200Response {
    /**
     * 
     * @type {Array<V1TransfersGet200ResponseDataInner>}
     * @memberof V1TransfersGet200Response
     */
    data?: Array<V1TransfersGet200ResponseDataInner>;
    /**
     * 
     * @type {boolean}
     * @memberof V1TransfersGet200Response
     */
    hasMore?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1TransfersGet200Response
     */
    object?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TransfersGet200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the V1TransfersGet200Response interface.
 */
export function instanceOfV1TransfersGet200Response(value: object): value is V1TransfersGet200Response {
    return true;
}

export function V1TransfersGet200ResponseFromJSON(json: any): V1TransfersGet200Response {
    return V1TransfersGet200ResponseFromJSONTyped(json, false);
}

export function V1TransfersGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TransfersGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V1TransfersGet200ResponseDataInnerFromJSON)),
        'hasMore': json['has_more'] == null ? undefined : json['has_more'],
        'object': json['object'] == null ? undefined : json['object'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function V1TransfersGet200ResponseToJSON(json: any): V1TransfersGet200Response {
    return V1TransfersGet200ResponseToJSONTyped(json, false);
}

export function V1TransfersGet200ResponseToJSONTyped(value?: V1TransfersGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V1TransfersGet200ResponseDataInnerToJSON)),
        'has_more': value['hasMore'],
        'object': value['object'],
        'url': value['url'],
    };
}

