// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerData.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerData
 */
export interface WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerData {
    /**
     * 
     * @type {string}
     * @memberof WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerData
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerData
     */
    full?: string;
}

/**
 * Check if a given object implements the WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerData interface.
 */
export function instanceOfWatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerData(value: object): value is WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerData {
    return true;
}

export function WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerDataFromJSON(json: any): WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerData {
    return WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerDataFromJSONTyped(json, false);
}

export function WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerData {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'] == null ? undefined : json['country'],
        'full': json['full'] == null ? undefined : json['full'],
    };
}

export function WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerDataToJSON(json: any): WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerData {
    return WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerDataToJSONTyped(json, false);
}

export function WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerDataToJSONTyped(value?: WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerDataLocationsInnerData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country': value['country'],
        'full': value['full'],
    };
}

