// REPOSITORY SOURCE: diplomat-bit/aibankingmtls | PATH: diplomat-bit-aibankingmtls-6a06a68/models/WatchlistScreeningIndividualHitListPostDefaultResponse.ts
================================================================================

/* tslint:disable */
/* eslint-disable */
/**
 * jmaesburvelocallaghaniii
 * N/A
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInner } from './WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInner';
import {
    WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerFromJSON,
    WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerFromJSONTyped,
    WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerToJSON,
    WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerToJSONTyped,
} from './WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInner';

/**
 * 
 * @export
 * @interface WatchlistScreeningIndividualHitListPostDefaultResponse
 */
export interface WatchlistScreeningIndividualHitListPostDefaultResponse {
    /**
     * 
     * @type {string}
     * @memberof WatchlistScreeningIndividualHitListPostDefaultResponse
     */
    requestId?: string;
    /**
     * 
     * @type {Array<WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInner>}
     * @memberof WatchlistScreeningIndividualHitListPostDefaultResponse
     */
    watchlistScreeningHits?: Array<WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInner>;
}

/**
 * Check if a given object implements the WatchlistScreeningIndividualHitListPostDefaultResponse interface.
 */
export function instanceOfWatchlistScreeningIndividualHitListPostDefaultResponse(value: object): value is WatchlistScreeningIndividualHitListPostDefaultResponse {
    return true;
}

export function WatchlistScreeningIndividualHitListPostDefaultResponseFromJSON(json: any): WatchlistScreeningIndividualHitListPostDefaultResponse {
    return WatchlistScreeningIndividualHitListPostDefaultResponseFromJSONTyped(json, false);
}

export function WatchlistScreeningIndividualHitListPostDefaultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchlistScreeningIndividualHitListPostDefaultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'watchlistScreeningHits': json['watchlist_screening_hits'] == null ? undefined : ((json['watchlist_screening_hits'] as Array<any>).map(WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerFromJSON)),
    };
}

export function WatchlistScreeningIndividualHitListPostDefaultResponseToJSON(json: any): WatchlistScreeningIndividualHitListPostDefaultResponse {
    return WatchlistScreeningIndividualHitListPostDefaultResponseToJSONTyped(json, false);
}

export function WatchlistScreeningIndividualHitListPostDefaultResponseToJSONTyped(value?: WatchlistScreeningIndividualHitListPostDefaultResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_id': value['requestId'],
        'watchlist_screening_hits': value['watchlistScreeningHits'] == null ? undefined : ((value['watchlistScreeningHits'] as Array<any>).map(WatchlistScreeningIndividualHitListPostDefaultResponseWatchlistScreeningHitsInnerToJSON)),
    };
}

